<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Data Dx | ReCentering Psych Stats: Multivariate Modeling</title>
  <meta name="description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Data Dx | ReCentering Psych Stats: Multivariate Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Data Dx | ReCentering Psych Stats: Multivariate Modeling" />
  
  <meta name="twitter:description" content="This is an open-access, book-in-progress. My goal in offering it is to re-center the materials used in training statistics and research methods in graduate and post-graduate psychology programs." />
  

<meta name="author" content="Lynette H Bikos, PhD, ABPP" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="score.html"/>
<link rel="next" href="multimp.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>ReCentering Psych Stats: Multivariate Modeling</strong><br>by Lynette H Bikos, PhD, ABPP</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>BOOK COVER</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>PREFACE</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>ACKNOWLEDGEMENTS</a></li>
<li class="chapter" data-level="1" data-path="ReCintro.html"><a href="ReCintro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ReCintro.html"><a href="ReCintro.html#what-to-expect-in-each-chapter"><i class="fa fa-check"></i><b>1.1</b> What to expect in each chapter</a></li>
<li class="chapter" data-level="1.2" data-path="ReCintro.html"><a href="ReCintro.html#strategies-for-accessing-and-using-this-oer"><i class="fa fa-check"></i><b>1.2</b> Strategies for Accessing and Using this OER</a></li>
<li class="chapter" data-level="1.3" data-path="ReCintro.html"><a href="ReCintro.html#if-you-are-new-to-r"><i class="fa fa-check"></i><b>1.3</b> If You are New to R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="ReCintro.html"><a href="ReCintro.html#base-r"><i class="fa fa-check"></i><b>1.3.1</b> Base R</a></li>
<li class="chapter" data-level="1.3.2" data-path="ReCintro.html"><a href="ReCintro.html#r-studio"><i class="fa fa-check"></i><b>1.3.2</b> R Studio</a></li>
<li class="chapter" data-level="1.3.3" data-path="ReCintro.html"><a href="ReCintro.html#r-hygiene"><i class="fa fa-check"></i><b>1.3.3</b> R Hygiene</a>
<ul>
<li class="chapter" data-level="1.3.3.1" data-path="ReCintro.html"><a href="ReCintro.html#everything-is-documented-in-the-.rmd-file"><i class="fa fa-check"></i><b>1.3.3.1</b> Everything is documented in the .rmd file</a></li>
<li class="chapter" data-level="1.3.3.2" data-path="ReCintro.html"><a href="ReCintro.html#file-organization"><i class="fa fa-check"></i><b>1.3.3.2</b> File organization</a></li>
<li class="chapter" data-level="1.3.3.3" data-path="ReCintro.html"><a href="ReCintro.html#chunks"><i class="fa fa-check"></i><b>1.3.3.3</b> Chunks</a></li>
<li class="chapter" data-level="1.3.3.4" data-path="ReCintro.html"><a href="ReCintro.html#packages"><i class="fa fa-check"></i><b>1.3.3.4</b> Packages</a></li>
<li class="chapter" data-level="1.3.3.5" data-path="ReCintro.html"><a href="ReCintro.html#knitting"><i class="fa fa-check"></i><b>1.3.3.5</b> Knitting</a></li>
</ul></li>
<li class="chapter" data-level="1.3.4" data-path="ReCintro.html"><a href="ReCintro.html#troubleshooting-in-r-markdown"><i class="fa fa-check"></i><b>1.3.4</b> tRoubleshooting in R maRkdown</a></li>
<li class="chapter" data-level="1.3.5" data-path="ReCintro.html"><a href="ReCintro.html#strategies-for-success"><i class="fa fa-check"></i><b>1.3.5</b> stRategies for success</a></li>
<li class="chapter" data-level="1.3.6" data-path="ReCintro.html"><a href="ReCintro.html#resources-for-getting-started"><i class="fa fa-check"></i><b>1.3.6</b> Resources for getting staRted</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="dataprep.html"><a href="dataprep.html"><i class="fa fa-check"></i>DATA PREP</a></li>
<li class="chapter" data-level="2" data-path="scrub.html"><a href="scrub.html"><i class="fa fa-check"></i><b>2</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scrub.html"><a href="scrub.html#navigating-this-lesson"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scrub.html"><a href="scrub.html#learning-objectives"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="scrub.html"><a href="scrub.html#planning-for-practice"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="scrub.html"><a href="scrub.html#readings-resources"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="2.1.4" data-path="scrub.html"><a href="scrub.html#packages-1"><i class="fa fa-check"></i><b>2.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="scrub.html"><a href="scrub.html#workflow-for-scrubbing-and-scoring"><i class="fa fa-check"></i><b>2.2</b> Workflow for Scrubbing and Scoring</a></li>
<li class="chapter" data-level="2.3" data-path="scrub.html"><a href="scrub.html#research-vignette"><i class="fa fa-check"></i><b>2.3</b> Research Vignette</a></li>
<li class="chapter" data-level="2.4" data-path="scrub.html"><a href="scrub.html#working-the-problem"><i class="fa fa-check"></i><b>2.4</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="scrub.html"><a href="scrub.html#intravenous-qualtrics"><i class="fa fa-check"></i><b>2.4.1</b> intRavenous Qualtrics</a></li>
<li class="chapter" data-level="2.4.2" data-path="scrub.html"><a href="scrub.html#about-the-rate-a-recent-course-survey"><i class="fa fa-check"></i><b>2.4.2</b> About the <em>Rate-a-Recent-Course</em> Survey</a></li>
<li class="chapter" data-level="2.4.3" data-path="scrub.html"><a href="scrub.html#the-codebook"><i class="fa fa-check"></i><b>2.4.3</b> The Codebook</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="scrub.html"><a href="scrub.html#scrubbing"><i class="fa fa-check"></i><b>2.5</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="scrub.html"><a href="scrub.html#tools-for-data-manipulations"><i class="fa fa-check"></i><b>2.5.1</b> Tools for Data Manipulations</a></li>
<li class="chapter" data-level="2.5.2" data-path="scrub.html"><a href="scrub.html#inclusion-and-exclusion-criteria"><i class="fa fa-check"></i><b>2.5.2</b> Inclusion and Exclusion Criteria</a></li>
<li class="chapter" data-level="2.5.3" data-path="scrub.html"><a href="scrub.html#renaming-variables"><i class="fa fa-check"></i><b>2.5.3</b> Renaming Variables</a></li>
<li class="chapter" data-level="2.5.4" data-path="scrub.html"><a href="scrub.html#downsizing-the-dataframe"><i class="fa fa-check"></i><b>2.5.4</b> Downsizing the Dataframe</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="scrub.html"><a href="scrub.html#toward-the-apa-style-write-up"><i class="fa fa-check"></i><b>2.6</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="scrub.html"><a href="scrub.html#methodprocedure"><i class="fa fa-check"></i><b>2.6.1</b> Method/Procedure</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="scrub.html"><a href="scrub.html#practice-problems"><i class="fa fa-check"></i><b>2.7</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="scrub.html"><a href="scrub.html#problem-1-rework-the-chapter-problem"><i class="fa fa-check"></i><b>2.7.1</b> Problem #1: Rework the Chapter Problem</a></li>
<li class="chapter" data-level="2.7.2" data-path="scrub.html"><a href="scrub.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables"><i class="fa fa-check"></i><b>2.7.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="2.7.3" data-path="scrub.html"><a href="scrub.html#problem-3-other-data"><i class="fa fa-check"></i><b>2.7.3</b> Problem #3: Other data</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="scrub.html"><a href="scrub.html#bonus-track"><i class="fa fa-check"></i><b>2.8</b> Bonus Track:</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="scrub.html"><a href="scrub.html#importing-data-from-an-exported-qualtrics-.csv-file"><i class="fa fa-check"></i><b>2.8.1</b> Importing data from an exported Qualtrics .csv file</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="score.html"><a href="score.html"><i class="fa fa-check"></i><b>3</b> Scoring</a>
<ul>
<li class="chapter" data-level="3.1" data-path="score.html"><a href="score.html#navigating-this-lesson-1"><i class="fa fa-check"></i><b>3.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="score.html"><a href="score.html#learning-objectives-1"><i class="fa fa-check"></i><b>3.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="score.html"><a href="score.html#planning-for-practice-1"><i class="fa fa-check"></i><b>3.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="3.1.3" data-path="score.html"><a href="score.html#readings-resources-1"><i class="fa fa-check"></i><b>3.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="3.1.4" data-path="score.html"><a href="score.html#packages-2"><i class="fa fa-check"></i><b>3.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="score.html"><a href="score.html#workflow-for-scrubbing-and-scoring-1"><i class="fa fa-check"></i><b>3.2</b> Workflow for Scrubbing and Scoring</a></li>
<li class="chapter" data-level="3.3" data-path="score.html"><a href="score.html#research-vignette-1"><i class="fa fa-check"></i><b>3.3</b> Research Vignette</a></li>
<li class="chapter" data-level="3.4" data-path="score.html"><a href="score.html#on-missing-data"><i class="fa fa-check"></i><b>3.4</b> On Missing Data</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="score.html"><a href="score.html#data-loss-mechanisms"><i class="fa fa-check"></i><b>3.4.1</b> Data Loss Mechanisms</a></li>
<li class="chapter" data-level="3.4.2" data-path="score.html"><a href="score.html#diagnosing-missing-data-mechanisms"><i class="fa fa-check"></i><b>3.4.2</b> Diagnosing Missing Data Mechanisms</a></li>
<li class="chapter" data-level="3.4.3" data-path="score.html"><a href="score.html#managing-missing-data"><i class="fa fa-check"></i><b>3.4.3</b> Managing Missing Data</a></li>
<li class="chapter" data-level="3.4.4" data-path="score.html"><a href="score.html#available-information-analysis-aia"><i class="fa fa-check"></i><b>3.4.4</b> Available Information Analysis (AIA)</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="score.html"><a href="score.html#working-the-problem-1"><i class="fa fa-check"></i><b>3.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="score.html"><a href="score.html#missing-data-analysis-whole-df-and-item-level"><i class="fa fa-check"></i><b>3.5.1</b> Missing Data Analysis: Whole df and Item level</a></li>
<li class="chapter" data-level="3.5.2" data-path="score.html"><a href="score.html#analyzing-missing-data-patterns"><i class="fa fa-check"></i><b>3.5.2</b> Analyzing Missing Data Patterns</a></li>
<li class="chapter" data-level="3.5.3" data-path="score.html"><a href="score.html#missing-mechanisms"><i class="fa fa-check"></i><b>3.5.3</b> Missing Mechanisms</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="score.html"><a href="score.html#scoring"><i class="fa fa-check"></i><b>3.6</b> Scoring</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="score.html"><a href="score.html#reverse-scoring"><i class="fa fa-check"></i><b>3.6.1</b> Reverse scoring</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="score.html"><a href="score.html#missing-analysis-scale-level"><i class="fa fa-check"></i><b>3.7</b> Missing Analysis: Scale level</a></li>
<li class="chapter" data-level="3.8" data-path="score.html"><a href="score.html#revisiting-missing-analysis-at-the-scale-level"><i class="fa fa-check"></i><b>3.8</b> Revisiting Missing Analysis at the Scale Level</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="score.html"><a href="score.html#scale-level-patterns-of-missing-data"><i class="fa fa-check"></i><b>3.8.1</b> Scale Level: Patterns of Missing Data</a></li>
<li class="chapter" data-level="3.8.2" data-path="score.html"><a href="score.html#is-it-mcar"><i class="fa fa-check"></i><b>3.8.2</b> Is it MCAR?</a></li>
<li class="chapter" data-level="3.8.3" data-path="score.html"><a href="score.html#r-eady-for-analysis"><i class="fa fa-check"></i><b>3.8.3</b> R-eady for Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="score.html"><a href="score.html#the-apa-style-write-up"><i class="fa fa-check"></i><b>3.9</b> The APA Style Write-Up</a></li>
<li class="chapter" data-level="3.10" data-path="score.html"><a href="score.html#results"><i class="fa fa-check"></i><b>3.10</b> Results</a></li>
<li class="chapter" data-level="3.11" data-path="score.html"><a href="score.html#practice-problems-1"><i class="fa fa-check"></i><b>3.11</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="score.html"><a href="score.html#problem-1-reworking-the-chapter-problem"><i class="fa fa-check"></i><b>3.11.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="3.11.2" data-path="score.html"><a href="score.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1"><i class="fa fa-check"></i><b>3.11.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="3.11.3" data-path="score.html"><a href="score.html#problem-3-other-data-1"><i class="fa fa-check"></i><b>3.11.3</b> Problem #3: Other data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="DataDx.html"><a href="DataDx.html"><i class="fa fa-check"></i><b>4</b> Data Dx</a>
<ul>
<li class="chapter" data-level="4.1" data-path="DataDx.html"><a href="DataDx.html#navigating-this-lesson-2"><i class="fa fa-check"></i><b>4.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="DataDx.html"><a href="DataDx.html#learning-objectives-2"><i class="fa fa-check"></i><b>4.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.1.2" data-path="DataDx.html"><a href="DataDx.html#planning-for-practice-2"><i class="fa fa-check"></i><b>4.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="4.1.3" data-path="DataDx.html"><a href="DataDx.html#readings-resources-2"><i class="fa fa-check"></i><b>4.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="4.1.4" data-path="DataDx.html"><a href="DataDx.html#packages-3"><i class="fa fa-check"></i><b>4.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="DataDx.html"><a href="DataDx.html#workflow-for-scrubbing-and-scoring-2"><i class="fa fa-check"></i><b>4.2</b> Workflow for Scrubbing and Scoring</a></li>
<li class="chapter" data-level="4.3" data-path="DataDx.html"><a href="DataDx.html#research-vignette-2"><i class="fa fa-check"></i><b>4.3</b> Research Vignette</a></li>
<li class="chapter" data-level="4.4" data-path="DataDx.html"><a href="DataDx.html#internal-consistency-of-scalessubscales"><i class="fa fa-check"></i><b>4.4</b> Internal Consistency of Scales/Subscales</a></li>
<li class="chapter" data-level="4.5" data-path="DataDx.html"><a href="DataDx.html#distributional-characteristics-of-the-variables"><i class="fa fa-check"></i><b>4.5</b> Distributional Characteristics of the Variables</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="DataDx.html"><a href="DataDx.html#evaluating-univariate-normality"><i class="fa fa-check"></i><b>4.5.1</b> Evaluating Univariate Normality</a></li>
<li class="chapter" data-level="4.5.2" data-path="DataDx.html"><a href="DataDx.html#pairs-panels"><i class="fa fa-check"></i><b>4.5.2</b> Pairs Panels</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="DataDx.html"><a href="DataDx.html#evaluating-multivariate-normality"><i class="fa fa-check"></i><b>4.6</b> Evaluating Multivariate Normality</a></li>
<li class="chapter" data-level="4.7" data-path="DataDx.html"><a href="DataDx.html#a-few-words-on-transformations"><i class="fa fa-check"></i><b>4.7</b> A Few Words on Transformations</a></li>
<li class="chapter" data-level="4.8" data-path="DataDx.html"><a href="DataDx.html#the-apa-style-write-up-1"><i class="fa fa-check"></i><b>4.8</b> The APA Style Write-Up</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="DataDx.html"><a href="DataDx.html#data-diagnostics"><i class="fa fa-check"></i><b>4.8.1</b> Data Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="DataDx.html"><a href="DataDx.html#a-quick-regression-of-our-research-vignette"><i class="fa fa-check"></i><b>4.9</b> A Quick Regression of our Research Vignette</a></li>
<li class="chapter" data-level="4.10" data-path="DataDx.html"><a href="DataDx.html#practice-problems-2"><i class="fa fa-check"></i><b>4.10</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="DataDx.html"><a href="DataDx.html#problem-1-reworking-the-chapter-problem-1"><i class="fa fa-check"></i><b>4.10.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="4.10.2" data-path="DataDx.html"><a href="DataDx.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-2"><i class="fa fa-check"></i><b>4.10.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="4.10.3" data-path="DataDx.html"><a href="DataDx.html#problem-3-other-data-2"><i class="fa fa-check"></i><b>4.10.3</b> Problem #3: Other data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multimp.html"><a href="multimp.html"><i class="fa fa-check"></i><b>5</b> Multiple Imputation (A Brief Demo)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multimp.html"><a href="multimp.html#navigating-this-lesson-3"><i class="fa fa-check"></i><b>5.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="multimp.html"><a href="multimp.html#learning-objectives-3"><i class="fa fa-check"></i><b>5.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="multimp.html"><a href="multimp.html#planning-for-practice-3"><i class="fa fa-check"></i><b>5.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="5.1.3" data-path="multimp.html"><a href="multimp.html#readings-resources-3"><i class="fa fa-check"></i><b>5.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="5.1.4" data-path="multimp.html"><a href="multimp.html#packages-4"><i class="fa fa-check"></i><b>5.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="multimp.html"><a href="multimp.html#workflow-for-multiple-imputation"><i class="fa fa-check"></i><b>5.2</b> Workflow for Multiple Imputation</a></li>
<li class="chapter" data-level="5.3" data-path="multimp.html"><a href="multimp.html#research-vignette-3"><i class="fa fa-check"></i><b>5.3</b> Research Vignette</a></li>
<li class="chapter" data-level="5.4" data-path="multimp.html"><a href="multimp.html#multiple-imputation-a-super-brief-review"><i class="fa fa-check"></i><b>5.4</b> Multiple Imputation – a Super Brief Review</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="multimp.html"><a href="multimp.html#steps-in-multiple-imputation"><i class="fa fa-check"></i><b>5.4.1</b> Steps in Multiple Imputation</a></li>
<li class="chapter" data-level="5.4.2" data-path="multimp.html"><a href="multimp.html#statistical-approaches-to-multiple-imputation"><i class="fa fa-check"></i><b>5.4.2</b> Statistical Approaches to Multiple Imputation</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="multimp.html"><a href="multimp.html#working-the-problem-2"><i class="fa fa-check"></i><b>5.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="multimp.html"><a href="multimp.html#selecting-and-formatting-variables"><i class="fa fa-check"></i><b>5.5.1</b> Selecting and Formatting Variables</a></li>
<li class="chapter" data-level="5.5.2" data-path="multimp.html"><a href="multimp.html#creating-composite-variables"><i class="fa fa-check"></i><b>5.5.2</b> Creating Composite Variables</a></li>
<li class="chapter" data-level="5.5.3" data-path="multimp.html"><a href="multimp.html#the-multiple-imputation"><i class="fa fa-check"></i><b>5.5.3</b> The Multiple Imputation</a></li>
<li class="chapter" data-level="5.5.4" data-path="multimp.html"><a href="multimp.html#creating-scale-scores"><i class="fa fa-check"></i><b>5.5.4</b> Creating Scale Scores</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="multimp.html"><a href="multimp.html#multiple-regression-with-multiply-imputed-data"><i class="fa fa-check"></i><b>5.6</b> Multiple Regression with Multiply Imputed Data</a></li>
<li class="chapter" data-level="5.7" data-path="multimp.html"><a href="multimp.html#toward-the-apa-style-write-up-1"><i class="fa fa-check"></i><b>5.7</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="multimp.html"><a href="multimp.html#methoddata-diagnostics"><i class="fa fa-check"></i><b>5.7.1</b> Method/Data Diagnostics</a></li>
<li class="chapter" data-level="5.7.2" data-path="multimp.html"><a href="multimp.html#results-1"><i class="fa fa-check"></i><b>5.7.2</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="multimp.html"><a href="multimp.html#multiple-imputation-considerations"><i class="fa fa-check"></i><b>5.8</b> Multiple imputation considerations</a></li>
<li class="chapter" data-level="5.9" data-path="multimp.html"><a href="multimp.html#practice-problems-3"><i class="fa fa-check"></i><b>5.9</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="multimp.html"><a href="multimp.html#problem-1-reworking-the-chapter-problem-2"><i class="fa fa-check"></i><b>5.9.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="5.9.2" data-path="multimp.html"><a href="multimp.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-3"><i class="fa fa-check"></i><b>5.9.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="5.9.3" data-path="multimp.html"><a href="multimp.html#problem-3-other-data-3"><i class="fa fa-check"></i><b>5.9.3</b> Problem #3: Other data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MED.html"><a href="MED.html"><i class="fa fa-check"></i>MEDIATION</a></li>
<li class="chapter" data-level="6" data-path="SimpleMed.html"><a href="SimpleMed.html"><i class="fa fa-check"></i><b>6</b> Simple Mediation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="SimpleMed.html"><a href="SimpleMed.html#navigating-this-lesson-4"><i class="fa fa-check"></i><b>6.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="SimpleMed.html"><a href="SimpleMed.html#learning-objectives-4"><i class="fa fa-check"></i><b>6.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.1.2" data-path="SimpleMed.html"><a href="SimpleMed.html#planning-for-practice-4"><i class="fa fa-check"></i><b>6.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="6.1.3" data-path="SimpleMed.html"><a href="SimpleMed.html#readings-resources-4"><i class="fa fa-check"></i><b>6.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="6.1.4" data-path="SimpleMed.html"><a href="SimpleMed.html#packages-5"><i class="fa fa-check"></i><b>6.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="SimpleMed.html"><a href="SimpleMed.html#estimating-indirect-effects-the-analytic-approach-often-termed-mediation"><i class="fa fa-check"></i><b>6.2</b> Estimating Indirect Effects (the analytic approach often termed <em>mediation</em>)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="SimpleMed.html"><a href="SimpleMed.html#the-definitional-and-conceptual"><i class="fa fa-check"></i><b>6.2.1</b> The definitional and conceptual</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="SimpleMed.html"><a href="SimpleMed.html#workflow-for-simple-mediation"><i class="fa fa-check"></i><b>6.3</b> Workflow for Simple Mediation</a></li>
<li class="chapter" data-level="6.4" data-path="SimpleMed.html"><a href="SimpleMed.html#simple-mediation-in-lavaan-a-focus-on-the-mechanics"><i class="fa fa-check"></i><b>6.4</b> Simple Mediation in <em>lavaan</em>: A focus on the mechanics</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="SimpleMed.html"><a href="SimpleMed.html#simulate-fake-data"><i class="fa fa-check"></i><b>6.4.1</b> Simulate Fake Data</a></li>
<li class="chapter" data-level="6.4.2" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-mediation-model"><i class="fa fa-check"></i><b>6.4.2</b> Specify Mediation Model</a></li>
<li class="chapter" data-level="6.4.3" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output"><i class="fa fa-check"></i><b>6.4.3</b> Interpret the Output</a></li>
<li class="chapter" data-level="6.4.4" data-path="SimpleMed.html"><a href="SimpleMed.html#a-table-and-a-figure"><i class="fa fa-check"></i><b>6.4.4</b> A Table and a Figure</a></li>
<li class="chapter" data-level="6.4.5" data-path="SimpleMed.html"><a href="SimpleMed.html#results-2"><i class="fa fa-check"></i><b>6.4.5</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="SimpleMed.html"><a href="SimpleMed.html#research-vignette-4"><i class="fa fa-check"></i><b>6.5</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="SimpleMed.html"><a href="SimpleMed.html#simulate-data-from-the-journal-article"><i class="fa fa-check"></i><b>6.5.1</b> Simulate Data from the Journal Article</a></li>
<li class="chapter" data-level="6.5.2" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-the-model-in-lavaan"><i class="fa fa-check"></i><b>6.5.2</b> Specify the Model in <em>lavaan</em></a></li>
<li class="chapter" data-level="6.5.3" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output-1"><i class="fa fa-check"></i><b>6.5.3</b> Interpret the Output</a></li>
<li class="chapter" data-level="6.5.4" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table"><i class="fa fa-check"></i><b>6.5.4</b> A Figure and a Table</a></li>
<li class="chapter" data-level="6.5.5" data-path="SimpleMed.html"><a href="SimpleMed.html#results-3"><i class="fa fa-check"></i><b>6.5.5</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="SimpleMed.html"><a href="SimpleMed.html#considering-covariates"><i class="fa fa-check"></i><b>6.6</b> Considering Covariates</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table-1"><i class="fa fa-check"></i><b>6.6.1</b> A Figure and a Table</a></li>
<li class="chapter" data-level="6.6.2" data-path="SimpleMed.html"><a href="SimpleMed.html#apa-style-write-up"><i class="fa fa-check"></i><b>6.6.2</b> APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="SimpleMed.html"><a href="SimpleMed.html#residual-and-related-questions"><i class="fa fa-check"></i><b>6.7</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="6.8" data-path="SimpleMed.html"><a href="SimpleMed.html#practice-problems-4"><i class="fa fa-check"></i><b>6.8</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed"><i class="fa fa-check"></i><b>6.8.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="6.8.2" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables"><i class="fa fa-check"></i><b>6.8.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="6.8.3" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-3-use-other-data-that-is-available-to-you"><i class="fa fa-check"></i><b>6.8.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="CompMed.html"><a href="CompMed.html"><i class="fa fa-check"></i><b>7</b> Complex Mediation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="CompMed.html"><a href="CompMed.html#navigating-this-lesson-5"><i class="fa fa-check"></i><b>7.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="CompMed.html"><a href="CompMed.html#learning-objectives-5"><i class="fa fa-check"></i><b>7.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="7.1.2" data-path="CompMed.html"><a href="CompMed.html#planning-for-practice-5"><i class="fa fa-check"></i><b>7.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="7.1.3" data-path="CompMed.html"><a href="CompMed.html#readings-resources-5"><i class="fa fa-check"></i><b>7.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="7.1.4" data-path="CompMed.html"><a href="CompMed.html#packages-6"><i class="fa fa-check"></i><b>7.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="CompMed.html"><a href="CompMed.html#complex-mediation"><i class="fa fa-check"></i><b>7.2</b> Complex Mediation</a></li>
<li class="chapter" data-level="7.3" data-path="CompMed.html"><a href="CompMed.html#parallel-mediation"><i class="fa fa-check"></i><b>7.3</b> Parallel Mediation</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="CompMed.html"><a href="CompMed.html#a-mechanical-example"><i class="fa fa-check"></i><b>7.3.1</b> A Mechanical Example</a>
<ul>
<li class="chapter" data-level="7.3.1.1" data-path="CompMed.html"><a href="CompMed.html#data-simulation"><i class="fa fa-check"></i><b>7.3.1.1</b> Data Simulation</a></li>
<li class="chapter" data-level="7.3.1.2" data-path="CompMed.html"><a href="CompMed.html#specifying-lavaan-code"><i class="fa fa-check"></i><b>7.3.1.2</b> Specifying <em>lavaan</em> code</a></li>
<li class="chapter" data-level="7.3.1.3" data-path="CompMed.html"><a href="CompMed.html#a-note-on-indirect-effects-and-confidence-intervals"><i class="fa fa-check"></i><b>7.3.1.3</b> A note on indirect effects and confidence intervals</a></li>
<li class="chapter" data-level="7.3.1.4" data-path="CompMed.html"><a href="CompMed.html#figures-and-tables"><i class="fa fa-check"></i><b>7.3.1.4</b> Figures and Tables</a></li>
<li class="chapter" data-level="7.3.1.5" data-path="CompMed.html"><a href="CompMed.html#apa-style-writeup"><i class="fa fa-check"></i><b>7.3.1.5</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="7.3.2" data-path="CompMed.html"><a href="CompMed.html#research-vignette-5"><i class="fa fa-check"></i><b>7.3.2</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="7.3.2.1" data-path="CompMed.html"><a href="CompMed.html#data-simulation-1"><i class="fa fa-check"></i><b>7.3.2.1</b> Data Simulation</a></li>
<li class="chapter" data-level="7.3.2.2" data-path="CompMed.html"><a href="CompMed.html#quick-descriptives"><i class="fa fa-check"></i><b>7.3.2.2</b> Quick Descriptives</a></li>
<li class="chapter" data-level="7.3.2.3" data-path="CompMed.html"><a href="CompMed.html#specifying-the-lavaan-model"><i class="fa fa-check"></i><b>7.3.2.3</b> Specifying the <em>lavaan</em> model</a></li>
<li class="chapter" data-level="7.3.2.4" data-path="CompMed.html"><a href="CompMed.html#figures-and-tables-1"><i class="fa fa-check"></i><b>7.3.2.4</b> Figures and Tables</a></li>
<li class="chapter" data-level="7.3.2.5" data-path="CompMed.html"><a href="CompMed.html#apa-style-writeup-1"><i class="fa fa-check"></i><b>7.3.2.5</b> APA Style Writeup</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="CompMed.html"><a href="CompMed.html#serial-multiple-mediator-model"><i class="fa fa-check"></i><b>7.4</b> Serial Multiple Mediator Model</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="CompMed.html"><a href="CompMed.html#we-stick-with-the-lewis-et-al.--lewis_applying_2017-example-but-modify-it."><i class="fa fa-check"></i><b>7.4.1</b> We stick with the Lewis et al. <span class="citation">(<span>2017</span>)</span> example, but modify it.</a></li>
<li class="chapter" data-level="7.4.2" data-path="CompMed.html"><a href="CompMed.html#specify-the-lavaan-model"><i class="fa fa-check"></i><b>7.4.2</b> Specify the <em>lavaan</em> model</a></li>
<li class="chapter" data-level="7.4.3" data-path="CompMed.html"><a href="CompMed.html#figures-and-tables-2"><i class="fa fa-check"></i><b>7.4.3</b> Figures and Tables</a></li>
<li class="chapter" data-level="7.4.4" data-path="CompMed.html"><a href="CompMed.html#apa-style-writeup-2"><i class="fa fa-check"></i><b>7.4.4</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="CompMed.html"><a href="CompMed.html#troubleshooting-and-faqs"><i class="fa fa-check"></i><b>7.5</b> Troubleshooting and FAQs</a></li>
<li class="chapter" data-level="7.6" data-path="CompMed.html"><a href="CompMed.html#practice-problems-5"><i class="fa fa-check"></i><b>7.6</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="CompMed.html"><a href="CompMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-1"><i class="fa fa-check"></i><b>7.6.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="7.6.2" data-path="CompMed.html"><a href="CompMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-1"><i class="fa fa-check"></i><b>7.6.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="7.6.3" data-path="CompMed.html"><a href="CompMed.html#problem-3-use-other-data-that-is-available-to-you-1"><i class="fa fa-check"></i><b>7.6.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MOD.html"><a href="MOD.html"><i class="fa fa-check"></i>MODERATION</a></li>
<li class="chapter" data-level="8" data-path="SimpMod.html"><a href="SimpMod.html"><i class="fa fa-check"></i><b>8</b> Simple Moderation in OLS and MLE</a>
<ul>
<li class="chapter" data-level="8.1" data-path="SimpMod.html"><a href="SimpMod.html#navigating-this-lesson-6"><i class="fa fa-check"></i><b>8.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="SimpMod.html"><a href="SimpMod.html#learning-objectives-6"><i class="fa fa-check"></i><b>8.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="8.1.2" data-path="SimpMod.html"><a href="SimpMod.html#planning-for-practice-6"><i class="fa fa-check"></i><b>8.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="8.1.3" data-path="SimpMod.html"><a href="SimpMod.html#readings-resources-6"><i class="fa fa-check"></i><b>8.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="8.1.4" data-path="SimpMod.html"><a href="SimpMod.html#packages-7"><i class="fa fa-check"></i><b>8.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="SimpMod.html"><a href="SimpMod.html#on-modeling-introductory-comments-on-the-simultaneously-invisible-and-paradigm-shifting-transition-we-are-making"><i class="fa fa-check"></i><b>8.2</b> On <em>Modeling</em>: Introductory Comments on the simultaneously invisible and paradigm-shifting transition we are making</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="SimpMod.html"><a href="SimpMod.html#nhst-versus-modeling"><i class="fa fa-check"></i><b>8.2.1</b> NHST versus modeling</a></li>
<li class="chapter" data-level="8.2.2" data-path="SimpMod.html"><a href="SimpMod.html#introducing-the-model"><i class="fa fa-check"></i><b>8.2.2</b> Introducing: <em>The Model</em></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="SimpMod.html"><a href="SimpMod.html#ols-to-ml-for-estimation"><i class="fa fa-check"></i><b>8.3</b> OLS to ML for Estimation</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="SimpMod.html"><a href="SimpMod.html#ordinary-least-squares-ols"><i class="fa fa-check"></i><b>8.3.1</b> Ordinary least squares (OLS)</a></li>
<li class="chapter" data-level="8.3.2" data-path="SimpMod.html"><a href="SimpMod.html#maximum-likelihood-estimation-mle-a-brief-orientation"><i class="fa fa-check"></i><b>8.3.2</b> Maximum likelihood estimation (MLE): A brief orientation</a></li>
<li class="chapter" data-level="8.3.3" data-path="SimpMod.html"><a href="SimpMod.html#ols-and-mle-comparison"><i class="fa fa-check"></i><b>8.3.3</b> OLS and MLE Comparison</a></li>
<li class="chapter" data-level="8.3.4" data-path="SimpMod.html"><a href="SimpMod.html#hayes-and-process-aka-conditional-process-analysis"><i class="fa fa-check"></i><b>8.3.4</b> Hayes and PROCESS (aka conditional process analysis)</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="SimpMod.html"><a href="SimpMod.html#introducing-the-lavaan-package"><i class="fa fa-check"></i><b>8.4</b> Introducing the <em>lavaan</em> package</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="SimpMod.html"><a href="SimpMod.html#the-fiml-magic-for-which-we-have-been-waiting"><i class="fa fa-check"></i><b>8.4.1</b> The FIML magic for which we have been waiting</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="SimpMod.html"><a href="SimpMod.html#picking-up-with-moderation"><i class="fa fa-check"></i><b>8.5</b> Picking up with Moderation</a></li>
<li class="chapter" data-level="8.6" data-path="SimpMod.html"><a href="SimpMod.html#workflow-for-a-simple-moderation"><i class="fa fa-check"></i><b>8.6</b> Workflow for a Simple Moderation</a></li>
<li class="chapter" data-level="8.7" data-path="SimpMod.html"><a href="SimpMod.html#research-vignette-6"><i class="fa fa-check"></i><b>8.7</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="SimpMod.html"><a href="SimpMod.html#simulate-data-from-the-journal-article-1"><i class="fa fa-check"></i><b>8.7.1</b> Simulate Data from the Journal Article</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="SimpMod.html"><a href="SimpMod.html#working-the-simple-moderation-with-ols-and-mle"><i class="fa fa-check"></i><b>8.8</b> Working the Simple Moderation with OLS and MLE</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="SimpMod.html"><a href="SimpMod.html#ols-with-lm"><i class="fa fa-check"></i><b>8.8.1</b> OLS with <em>lm()</em></a>
<ul>
<li class="chapter" data-level="8.8.1.1" data-path="SimpMod.html"><a href="SimpMod.html#an-apa-style-write-up-of-ols-results"><i class="fa fa-check"></i><b>8.8.1.1</b> An APA Style Write-up of OLS results</a></li>
</ul></li>
<li class="chapter" data-level="8.8.2" data-path="SimpMod.html"><a href="SimpMod.html#mle-with-lavaansem"><i class="fa fa-check"></i><b>8.8.2</b> MLE with <em>lavaan::sem()</em></a></li>
<li class="chapter" data-level="8.8.3" data-path="SimpMod.html"><a href="SimpMod.html#tabling-the-data"><i class="fa fa-check"></i><b>8.8.3</b> Tabling the data</a></li>
<li class="chapter" data-level="8.8.4" data-path="SimpMod.html"><a href="SimpMod.html#apa-style-writeup-3"><i class="fa fa-check"></i><b>8.8.4</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="SimpMod.html"><a href="SimpMod.html#residual-and-related-questions-1"><i class="fa fa-check"></i><b>8.9</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="8.10" data-path="SimpMod.html"><a href="SimpMod.html#practice-problems-6"><i class="fa fa-check"></i><b>8.10</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="SimpMod.html"><a href="SimpMod.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-2"><i class="fa fa-check"></i><b>8.10.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="8.10.2" data-path="SimpMod.html"><a href="SimpMod.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-2"><i class="fa fa-check"></i><b>8.10.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="8.10.3" data-path="SimpMod.html"><a href="SimpMod.html#problem-3-use-other-data-that-is-available-to-you-2"><i class="fa fa-check"></i><b>8.10.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="SimpMod.html"><a href="SimpMod.html#bonus-track-1"><i class="fa fa-check"></i><b>8.11</b> Bonus Track:</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="refs.html"><a href="refs.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="CPAnal.html"><a href="CPAnal.html"><i class="fa fa-check"></i>CONDITIONAL PROCESS ANALYSIS</a></li>
<li class="chapter" data-level="9" data-path="ModMed.html"><a href="ModMed.html"><i class="fa fa-check"></i><b>9</b> Moderated Mediation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ModMed.html"><a href="ModMed.html#navigating-this-lesson-7"><i class="fa fa-check"></i><b>9.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="ModMed.html"><a href="ModMed.html#learning-objectives-7"><i class="fa fa-check"></i><b>9.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="9.1.2" data-path="ModMed.html"><a href="ModMed.html#planning-for-practice-7"><i class="fa fa-check"></i><b>9.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="9.1.3" data-path="ModMed.html"><a href="ModMed.html#readings-resources-7"><i class="fa fa-check"></i><b>9.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="9.1.4" data-path="ModMed.html"><a href="ModMed.html#packages-8"><i class="fa fa-check"></i><b>9.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="ModMed.html"><a href="ModMed.html#conditional-process-analysis"><i class="fa fa-check"></i><b>9.2</b> Conditional Process Analysis</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ModMed.html"><a href="ModMed.html#the-definitional-and-conceptual-1"><i class="fa fa-check"></i><b>9.2.1</b> The definitional and conceptual</a></li>
<li class="chapter" data-level="9.2.2" data-path="ModMed.html"><a href="ModMed.html#hayes--hayes_introduction_2018-piecewise-approach-to-building-models"><i class="fa fa-check"></i><b>9.2.2</b> Hayes’ <span class="citation">(<span>2018</span>)</span> Piecewise Approach to Building Models</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ModMed.html"><a href="ModMed.html#workflow-for-moderated-mediation"><i class="fa fa-check"></i><b>9.3</b> Workflow for Moderated Mediation</a></li>
<li class="chapter" data-level="9.4" data-path="ModMed.html"><a href="ModMed.html#research-vignette-7"><i class="fa fa-check"></i><b>9.4</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ModMed.html"><a href="ModMed.html#simulating-the-data-from-the-journal-article"><i class="fa fa-check"></i><b>9.4.1</b> Simulating the data from the journal article</a></li>
<li class="chapter" data-level="9.4.2" data-path="ModMed.html"><a href="ModMed.html#quick-peek-at-the-data"><i class="fa fa-check"></i><b>9.4.2</b> Quick peek at the data</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ModMed.html"><a href="ModMed.html#working-the-moderated-mediation"><i class="fa fa-check"></i><b>9.5</b> Working the Moderated Mediation</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="ModMed.html"><a href="ModMed.html#piecewise-assembly-of-the-moderated-mediation"><i class="fa fa-check"></i><b>9.5.1</b> Piecewise Assembly of the Moderated Mediation</a>
<ul>
<li class="chapter" data-level="9.5.1.1" data-path="ModMed.html"><a href="ModMed.html#analysis-1-a-simple-moderation"><i class="fa fa-check"></i><b>9.5.1.1</b> Analysis #1: A simple moderation</a></li>
<li class="chapter" data-level="9.5.1.2" data-path="ModMed.html"><a href="ModMed.html#analysis-2-another-simple-moderation"><i class="fa fa-check"></i><b>9.5.1.2</b> Analysis #2: Another simple moderation</a></li>
<li class="chapter" data-level="9.5.1.3" data-path="ModMed.html"><a href="ModMed.html#analysis-3-a-simple-mediation"><i class="fa fa-check"></i><b>9.5.1.3</b> Analysis #3: A simple mediation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ModMed.html"><a href="ModMed.html#the-moderated-mediation-a-combined-analysis"><i class="fa fa-check"></i><b>9.6</b> The Moderated Mediation: A Combined analysis</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="ModMed.html"><a href="ModMed.html#specification-in-lavaan"><i class="fa fa-check"></i><b>9.6.1</b> Specification in <em>lavaan</em></a></li>
<li class="chapter" data-level="9.6.2" data-path="ModMed.html"><a href="ModMed.html#a-quick-plot"><i class="fa fa-check"></i><b>9.6.2</b> A quick plot</a></li>
<li class="chapter" data-level="9.6.3" data-path="ModMed.html"><a href="ModMed.html#beginning-the-interpretation"><i class="fa fa-check"></i><b>9.6.3</b> Beginning the interpretation</a></li>
<li class="chapter" data-level="9.6.4" data-path="ModMed.html"><a href="ModMed.html#tabling-the-data-1"><i class="fa fa-check"></i><b>9.6.4</b> Tabling the data</a>
<ul>
<li class="chapter" data-level="9.6.4.1" data-path="ModMed.html"><a href="ModMed.html#conditional-indirect-effects"><i class="fa fa-check"></i><b>9.6.4.1</b> Conditional Indirect effects</a></li>
<li class="chapter" data-level="9.6.4.2" data-path="ModMed.html"><a href="ModMed.html#conditional-direct-effect"><i class="fa fa-check"></i><b>9.6.4.2</b> Conditional Direct effect</a></li>
</ul></li>
<li class="chapter" data-level="9.6.5" data-path="ModMed.html"><a href="ModMed.html#model-trimming"><i class="fa fa-check"></i><b>9.6.5</b> Model trimming</a></li>
<li class="chapter" data-level="9.6.6" data-path="ModMed.html"><a href="ModMed.html#apa-style-write-up-1"><i class="fa fa-check"></i><b>9.6.6</b> APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ModMed.html"><a href="ModMed.html#residual-and-related-questions-2"><i class="fa fa-check"></i><b>9.7</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="9.8" data-path="ModMed.html"><a href="ModMed.html#practice-problems-7"><i class="fa fa-check"></i><b>9.8</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="ModMed.html"><a href="ModMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-3"><i class="fa fa-check"></i><b>9.8.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="9.8.2" data-path="ModMed.html"><a href="ModMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-3"><i class="fa fa-check"></i><b>9.8.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="9.8.3" data-path="ModMed.html"><a href="ModMed.html#problem-3-use-other-data-that-is-available-to-you-3"><i class="fa fa-check"></i><b>9.8.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="ModMed.html"><a href="ModMed.html#bonus-track-2"><i class="fa fa-check"></i><b>9.9</b> Bonus Track:</a></li>
</ul></li>
<li class="divider"></li>
#<li><a href="https:link" target="_blank">Open access book-in-progress</br>
<li><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a></li>
  <li><a href="https://bookdown.org" target="_blank">Built with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ReCentering Psych Stats: Multivariate Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="DataDx" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Data Dx</h1>
<p><a href="https://spu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?pid=43dbe818-8186-498d-8e84-acf7000acb5b">Screencasted Lecture Link</a></p>
<p>The focus of this chapter engage in <em>data diagnostics</em>, that is, to evaluate the appropriateness of the data for the <em>specific research model we are going to evaluate</em>. We are asking the question, “Does the data have the appropriate characteristics for the analysis we want to perform?” Some statistics are more robust than others to violations of the assumptions about the characteristics of the data. None-the-less, we must report these characteristics when we disseminate the results.</p>
<div id="navigating-this-lesson-2" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Navigating this Lesson</h2>
<p>There is about 45 minutes of lecture. If you work through the materials with me it would be plan for an additional hour.</p>
<p>While the majority of R objects and data you will need are created within the R script that sources the chapter, there are a few that cannot be created from within the R framework. Additionally, sometimes links fail. All original materials are provided at the <a href="https://github.com/lhbikos/ReC_MultivModel">Github site</a> that hosts the book. More detailed guidelines for ways to access all these materials are provided in the OER’s <a href="ReCintro.html#ReCintro">introduction</a></p>
<div id="learning-objectives-2" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Learning Objectives</h3>
<p>Learning objectives from this lecture include the following:</p>
<ul>
<li>Conduct and interpret critical data diagnostics, including
<ul>
<li>alpha coefficients</li>
<li>skew</li>
<li>kurtosis</li>
</ul></li>
<li>Assess univariate and multivariate normality</li>
<li>Identify options for managing outliers and skewed data</li>
<li>Articulate a workflow for data preparation, including scrubbing, scoring, and data diagnostics</li>
</ul>
</div>
<div id="planning-for-practice-2" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Planning for Practice</h3>
<p>The suggestions from practice are a continuation from the two prior chapters. If you have completed one or more of those assignments, you should have started with a raw dataset and then scrubbed and scored it. This chapter will involve running basic data diagnostics. Options of graded complexity could incude:</p>
<ul>
<li>Repeating the steps in the chapter with the most recent data from the Rate-A-Recent-Course survey; differences will be in the number of people who have completed the survey since the chapter was written.</li>
<li>Use the dataset that is the source of the chapter, but score a different set of items that you choose.</li>
<li>Begin with raw data to which you have access.</li>
</ul>
</div>
<div id="readings-resources-2" class="section level3" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Readings &amp; Resources</h3>
<p>In preparing this chapter, I drew heavily from the following resource(s). Other resources are cited (when possible, linked) in the text with complete citations in the reference list.</p>
<ul>
<li><p>Parent, M. C. (2013). Handling item-level missing data: Simpler is just as good. The Counseling Psychologist, 41(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176" class="uri">https://doi.org/10.1177/0011000012445176</a></p></li>
<li><p>Kline, R. B. (2015). Data preparation and psychometrics review. In Principles and Practice of Structural Equation Modeling, Fourth Edition. Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663" class="uri">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a></p></li>
</ul>
</div>
<div id="packages-3" class="section level3" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Packages</h3>
<p>The script below will (a) check to see if the following packages are installed on your computer and, if not (b) install them.</p>
<!-- TODO: Build out this section. -->
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="DataDx.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tidyverse)){<span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)} <span class="co">#this includes dplyr</span></span>
<span id="cb75-2"><a href="DataDx.html#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(psych)){<span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)}</span>
<span id="cb75-3"><a href="DataDx.html#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(apaTables)){<span class="fu">install.packages</span>(<span class="st">&quot;apaTables&quot;</span>)}</span>
<span id="cb75-4"><a href="DataDx.html#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(formattable)){<span class="fu">install.packages</span>(<span class="st">&quot;formattable&quot;</span>)}</span></code></pre></div>
</div>
</div>
<div id="workflow-for-scrubbing-and-scoring-2" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Workflow for Scrubbing and Scoring</h2>
<!-- TODO: When finalized, save as PDF so it can open in its own window) -->
<p>The same workflow guides us through the Scrubbing, Scoring, and Data Dx chapters. At this stage we have</p>
<ul>
<li>imported our raw data from Qualtrics,</li>
<li>scrubbed the data by applying our inclusion and exclusion criteria, and</li>
<li>used Parent’s available information approach [AIA; -<span class="citation">Parent (<a href="#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span>] for determining the acceptable amount of missingness for each scale, and</li>
<li>prepared variables and scored them.</li>
</ul>
<p>We are now ready to engage in data diagnostics for the statistical model we will test.</p>
<div class="figure">
<img src="images/Ch04/wrkflow_dx.jpg" alt="" />
<p class="caption">An image of our stage in the workflow for scrubbing and scoring data.</p>
</div>
</div>
<div id="research-vignette-2" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Research Vignette</h2>
<p>The research vignette comes from the survey titled, <a href="https://spupsych.az1.qualtrics.com/jfe/form/SV_b2cClqAlLGQ6nLU">Rate-a-Recent-Course: A ReCentering Psych Stats Exercise</a> and is explained in the <a href="scrub.html#scrub">scrubbing chapter</a>. In the <a href="score.html#score">scoring chapter</a> we prepared four variables for analysis. Details for these are in our <a href="./Rate-a-Course_Codebook.pdf">codebook</a>.</p>
<p>Variable recap:</p>
<ul>
<li>Perceived Campus Climate for Black Students includes 6 items, one of which was reverse scored. This scale was adapted from Szymanski et al.’s <span class="citation">(<a href="#ref-szymanski_perceptions_2020" role="doc-biblioref">2020</a>)</span> Campus Climate for LGBTQ students. It has not been evaluated for use with other groups. The Szymanski et al. analysis suggested that it could be used as a total scale score, or divided into three items each that assess
<ul>
<li>College response to LGBTQ students (items 6, 4, 1)</li>
<li>LGBTQ stigma (items 3, 2, 5)</li>
</ul></li>
<li>Sense of Belonging includes 3 items. This is a subscale from Bollen and Hoyle’s <span class="citation">(<a href="#ref-bollen_perceived_1990" role="doc-biblioref">1990</a>)</span> Perceived Cohesion Scale. There are no items on this scale that require reversing.</li>
<li>Percent of Black classmates is a single item that asked respondents to estimate the proportion of students in various racial categories</li>
<li>Percent of BIPOC instructional staff, similarly, asked respondents to identify the racial category of each member of their instructional staff</li>
</ul>
<p>As we noted in the <a href="scrub.html#scrub">scrubbing chapter</a>, our design has notable limitations. Briefly, (a) owing to the open source aspect of the data we do not ask about the demographic characteristics of the respondent; (b) the items that ask respondents to <em>guess</em> the identities of the instructional staff and to place them in broad categories, (c) we do not provide a “write-in” a response. We made these decisions after extensive conversation with stakeholders. The primary reason for these decisions was to prevent potential harm (a) to respondents who could be identified if/when the revealed private information in this open-source survey, and (b) trolls who would write inappropriate or harmful comments.</p>
<p>As I think about “how these variables go together” (which is often where I start in planning a study), imagine a parallel mediation. That is the perception of campus climate for Black students would be predicted by the respondent’s sense of belonging, mediated in separate paths through the proportion of classmates who are Black and the proportion of BIPOC instructional staff.</p>
<p><em>I would like to assess the model by having the instructional staff variable to be the %Black instructional staff. At the time that this lecture is being prepared, there is not sufficient Black representation in the staff to model this.</em></p>
<div class="figure">
<img src="images/Ch04/BlStuMed.jpg" alt="" />
<p class="caption">An image of the statistical model for which we are preparing data.</p>
</div>
<p>I will finish up this chapter by conducting a regression. Because parallel mediation can be complicated (I teach it in a later chapter), I will demonstrate use of our prepared variables with a simple multiple regression.</p>
<div class="figure">
<img src="images/Ch04/BlStuRegression.jpg" alt="" />
<p class="caption">An image of the statistical model for which we are preparing data.</p>
</div>
<p>First, though, let’s take a more conceptual look at issues regarding missing data. We’ll come back to details of the survey as we work with it.</p>
</div>
<div id="internal-consistency-of-scalessubscales" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Internal Consistency of Scales/Subscales</h2>
<p>Alpha coefficients are <em>reliability coefficients</em> that assess the <em>internal consistency</em> of an instrument. It asks, “For each person, are responses <em>consistently</em> high, or medium, or low?” To the degree that they are (meaning there are high inter-item correlations), the internal consistency coefficient will be high. We want values &gt;.80. There are numerous problems with alpha coefficients. The biggest one is that they are influenced by sample size – longer scales have higher alpha coefficients <span class="citation">(<a href="#ref-cortina_what_1993" role="doc-biblioref">Cortina, 1993</a>)</span>. Fourteen seems to be a magic number where we begin to not trust the high alpha coefficient. I address this more thoroughly – offering an alternative – in psychometrics. While there is much criticism about the usefulness of the alpha coefficient <span class="citation">(<a href="#ref-sijtsma_use_2009" role="doc-biblioref">Sijtsma, 2009</a>)</span>, researchers continue to use the alpha coefficient as an indicator of the internal consistency of scales that consist of multiple items and contain several variables.</p>
<p>We need item level data to compute an alpha coefficient. The easiest way to get an alpha coefficient is to feed the <em>alpha()</em> function (<em>psych</em> package) a contatonated list of items (with any items already reverse-scored). There should be no extra items. In the <a href="score.html#score">scoring chapter</a> we already reverse-coded the single item in the campus climate scale, so we are ready to calculate alphas.</p>
<p>The df from which I am pulling data was created and written as an outfile in the <a href="score.html#score">scoring chapter</a>. This particular df has item-level data.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="DataDx.html#cb76-1" aria-hidden="true" tabindex="-1"></a>item_scores_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span> (<span class="st">&quot;BlStItmsScrs210320.csv&quot;</span>, <span class="at">head =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>)</span></code></pre></div>
<p>From this, we create tiny dfs, one for each of the alpha coefficients we need to create. A priori, we are planning to use all six items of the campus climate scale. We’ll go ahead and also calculate the subscales because (a) it’s good practice and (b) if the alpha is low, a <em>reason</em> might show up in one of the subscales.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="DataDx.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb77-2"><a href="DataDx.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb77-3"><a href="DataDx.html#cb77-3" aria-hidden="true" tabindex="-1"></a>Bel_alpha <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;Belong_1&quot;</span>, <span class="st">&quot;Belong_2&quot;</span>, <span class="st">&quot;Belong_3&quot;</span>)])</span>
<span id="cb77-4"><a href="DataDx.html#cb77-4" aria-hidden="true" tabindex="-1"></a>Bel_alpha</span></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = item_scores_df[c(&quot;Belong_1&quot;, &quot;Belong_2&quot;, &quot;Belong_3&quot;)])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
##       0.96      0.96    0.94      0.88  22 0.011  4.2 1.5     0.89
## 
##  lower alpha upper     95% confidence boundaries
## 0.94 0.96 0.98 
## 
##  Reliability if an item is dropped:
##          raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## Belong_1      0.94      0.94    0.89      0.89  16    0.017    NA  0.89
## Belong_2      0.92      0.92    0.85      0.85  12    0.023    NA  0.85
## Belong_3      0.95      0.95    0.90      0.90  18    0.015    NA  0.90
## 
##  Item statistics 
##           n raw.r std.r r.cor r.drop mean  sd
## Belong_1 48  0.96  0.96  0.93   0.90  4.2 1.5
## Belong_2 49  0.97  0.97  0.95   0.93  4.3 1.5
## Belong_3 48  0.95  0.95  0.91   0.89  4.0 1.6
## 
## Non missing response frequency for each item
##             1    2    3    4    5    6    7 miss
## Belong_1 0.02 0.10 0.23 0.19 0.23 0.17 0.06 0.04
## Belong_2 0.02 0.10 0.22 0.22 0.16 0.20 0.06 0.02
## Belong_3 0.04 0.17 0.17 0.23 0.23 0.10 0.06 0.04</code></pre>
<p>CAPTURE FOR THE APA STYLE WRITE-UP(since these are generally placed in the description of each measure in the Method section, I am not doing a cumulative capture): Cronbach’s alpha for the belonging scale was 0.957.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="DataDx.html#cb79-1" aria-hidden="true" tabindex="-1"></a>CClim_alpha <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;rBlst_1&quot;</span>, <span class="st">&quot;Blst_2&quot;</span>, <span class="st">&quot;Blst_3&quot;</span>, <span class="st">&quot;Blst_4&quot;</span>, <span class="st">&quot;Blst_5&quot;</span>, <span class="st">&quot;Blst_6&quot;</span>)])</span>
<span id="cb79-2"><a href="DataDx.html#cb79-2" aria-hidden="true" tabindex="-1"></a>CClim_alpha</span></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = item_scores_df[c(&quot;rBlst_1&quot;, &quot;Blst_2&quot;, &quot;Blst_3&quot;, 
##     &quot;Blst_4&quot;, &quot;Blst_5&quot;, &quot;Blst_6&quot;)])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
##       0.87      0.88    0.88      0.55 7.2 0.029  2.5 1.1     0.52
## 
##  lower alpha upper     95% confidence boundaries
## 0.81 0.87 0.93 
## 
##  Reliability if an item is dropped:
##         raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## rBlst_1      0.88      0.89    0.88      0.61 7.8    0.027 0.017  0.59
## Blst_2       0.86      0.86    0.86      0.56 6.4    0.033 0.025  0.52
## Blst_3       0.86      0.88    0.87      0.59 7.1    0.031 0.021  0.55
## Blst_4       0.83      0.84    0.83      0.51 5.3    0.038 0.019  0.49
## Blst_5       0.82      0.83    0.82      0.50 5.0    0.040 0.018  0.48
## Blst_6       0.83      0.84    0.82      0.51 5.2    0.039 0.018  0.48
## 
##  Item statistics 
##          n raw.r std.r r.cor r.drop mean  sd
## rBlst_1 45  0.68  0.66  0.53   0.51  3.4 1.6
## Blst_2  48  0.78  0.76  0.70   0.64  2.8 1.6
## Blst_3  48  0.69  0.70  0.61   0.56  2.1 1.3
## Blst_4  47  0.85  0.86  0.84   0.78  2.3 1.2
## Blst_5  48  0.89  0.89  0.88   0.82  2.1 1.3
## Blst_6  48  0.85  0.87  0.87   0.79  2.3 1.3
## 
## Non missing response frequency for each item
##            1    2    3    4    5    6    7 miss
## rBlst_1 0.09 0.24 0.22 0.22 0.09 0.09 0.04 0.10
## Blst_2  0.35 0.15 0.08 0.23 0.17 0.02 0.00 0.04
## Blst_3  0.42 0.31 0.08 0.15 0.02 0.02 0.00 0.04
## Blst_4  0.30 0.34 0.15 0.15 0.06 0.00 0.00 0.06
## Blst_5  0.46 0.27 0.06 0.17 0.04 0.00 0.00 0.04
## Blst_6  0.33 0.35 0.12 0.10 0.06 0.02 0.00 0.04</code></pre>
<p>CAPTURE FOR THE APA STYLE WRITE-UP (since these are generally placed in the description of each measure in the Method section, I am not doing a cumulative capture): Cronbach’s alpha for the campus climate scale was 0.869. Since this value is <span class="math inline">\(\geq\)</span> .80, it is within the realm of acceptability. Let’s go ahead, though, and look at its subscales.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="DataDx.html#cb81-1" aria-hidden="true" tabindex="-1"></a>Stigma_alpha <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;Blst_3&quot;</span>, <span class="st">&quot;Blst_2&quot;</span>, <span class="st">&quot;Blst_5&quot;</span>)])</span>
<span id="cb81-2"><a href="DataDx.html#cb81-2" aria-hidden="true" tabindex="-1"></a>Stigma_alpha</span></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = item_scores_df[c(&quot;Blst_3&quot;, &quot;Blst_2&quot;, &quot;Blst_5&quot;)])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
##       0.77      0.78    0.74      0.54 3.6 0.056  2.3 1.2     0.55
## 
##  lower alpha upper     95% confidence boundaries
## 0.66 0.77 0.88 
## 
##  Reliability if an item is dropped:
##        raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## Blst_3      0.80      0.81    0.69      0.69 4.4    0.054    NA  0.69
## Blst_2      0.71      0.71    0.55      0.55 2.5    0.081    NA  0.55
## Blst_5      0.55      0.56    0.39      0.39 1.3    0.123    NA  0.39
## 
##  Item statistics 
##         n raw.r std.r r.cor r.drop mean  sd
## Blst_3 48  0.76  0.78  0.58   0.50  2.1 1.3
## Blst_2 48  0.86  0.83  0.72   0.61  2.8 1.6
## Blst_5 48  0.90  0.90  0.84   0.75  2.1 1.3
## 
## Non missing response frequency for each item
##           1    2    3    4    5    6 miss
## Blst_3 0.42 0.31 0.08 0.15 0.02 0.02 0.04
## Blst_2 0.35 0.15 0.08 0.23 0.17 0.02 0.04
## Blst_5 0.46 0.27 0.06 0.17 0.04 0.00 0.04</code></pre>
<p>Cronbach’s alpha for the campus climate stigma subscale was 0.772.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="DataDx.html#cb83-1" aria-hidden="true" tabindex="-1"></a>Resp_alpha <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;rBlst_1&quot;</span>, <span class="st">&quot;Blst_4&quot;</span>, <span class="st">&quot;Blst_6&quot;</span>)])</span>
<span id="cb83-2"><a href="DataDx.html#cb83-2" aria-hidden="true" tabindex="-1"></a>Resp_alpha</span></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = item_scores_df[c(&quot;rBlst_1&quot;, &quot;Blst_4&quot;, &quot;Blst_6&quot;)])
## 
##   raw_alpha std.alpha G6(smc) average_r S/N   ase mean  sd median_r
##       0.78       0.8    0.77      0.57   4 0.055  2.7 1.2     0.47
## 
##  lower alpha upper     95% confidence boundaries
## 0.68 0.78 0.89 
## 
##  Reliability if an item is dropped:
##         raw_alpha std.alpha G6(smc) average_r S/N alpha se var.r med.r
## rBlst_1      0.88      0.88    0.79      0.79 7.3    0.034    NA  0.79
## Blst_4       0.63      0.64    0.47      0.47 1.8    0.102    NA  0.47
## Blst_6       0.62      0.64    0.47      0.47 1.8    0.102    NA  0.47
## 
##  Item statistics 
##          n raw.r std.r r.cor r.drop mean  sd
## rBlst_1 45  0.80  0.76  0.53   0.50  3.4 1.6
## Blst_4  47  0.87  0.89  0.85   0.71  2.3 1.2
## Blst_6  48  0.87  0.89  0.85   0.71  2.3 1.3
## 
## Non missing response frequency for each item
##            1    2    3    4    5    6    7 miss
## rBlst_1 0.09 0.24 0.22 0.22 0.09 0.09 0.04 0.10
## Blst_4  0.30 0.34 0.15 0.15 0.06 0.00 0.00 0.06
## Blst_6  0.33 0.35 0.12 0.10 0.06 0.02 0.00 0.04</code></pre>
<p>Cronbach’s alpha for the campus climate responsiveness subscale was 0.784. Between the two subscales, it looks as if the responsivenes subscale is more internally consistent.</p>
</div>
<div id="distributional-characteristics-of-the-variables" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Distributional Characteristics of the Variables</h2>
<div id="evaluating-univariate-normality" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Evaluating Univariate Normality</h3>
<p>Statistics like ANOVA and regression each have a set of assumptions about the distributional characteristics of the data. In most of the chapters in this OER we review those assumptions and how to evaluate them. Common across many statistics is the requirement of univariate and multivariate normality. Let’s take a look at the variables we will use in our analysis and assess those.</p>
<p>We can continue to work from the df we uploaded at the beginning of the chapter to do this work. Let’s take a quick peek. This df has the item-level data (we used it for the alpha coefficients); the scale and subscale scores; and the two items that assess proportion of instructional staff that are BIPOC and proportion of classmates that are BIPOC.</p>
<p>The <em>str()</em> function let’s us look at the variable format/measurement level of each variable.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="DataDx.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(item_scores_df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  17 variables:
##  $ ID        : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ iBIPOC_pr : num  0.333 0 0.5 0.333 1 ...
##  $ cmBlack   : int  0 5 10 6 5 20 0 0 0 4 ...
##  $ Belong_1  : int  6 4 NA 5 4 5 6 7 6 3 ...
##  $ Belong_2  : int  6 4 3 3 4 6 6 7 6 3 ...
##  $ Belong_3  : int  7 6 NA 2 4 5 5 7 6 3 ...
##  $ Blst_1    : int  5 6 NA 2 6 5 5 5 5 3 ...
##  $ Blst_2    : int  3 6 5 2 1 1 4 4 3 5 ...
##  $ Blst_3    : int  5 2 2 2 1 1 4 3 1 2 ...
##  $ Blst_4    : int  2 2 2 2 1 2 4 3 2 3 ...
##  $ Blst_5    : int  2 4 NA 2 1 1 4 4 1 3 ...
##  $ Blst_6    : int  2 1 2 2 1 2 4 3 2 3 ...
##  $ rBlst_1   : int  3 2 NA 6 2 3 3 3 3 5 ...
##  $ Belonging : num  6.33 4.67 NA 3.33 4 5.33 5.67 7 6 3 ...
##  $ ResponseBL: num  2.33 1.67 2 3.33 1.33 2.33 3.67 3 2.33 3.67 ...
##  $ StigmaBL  : num  3.33 4 3.5 2 1 1 4 3.67 1.67 3.33 ...
##  $ ClimateBL : num  2.83 2.83 NA 2.67 1.17 1.67 3.83 3.33 2 3.5 ...</code></pre>
<p>The difference between “int” (integer) and “num” (numerical) is that integers are limited to whole numbers. In the functions used in this chapter, both are acceptable formats for the variables.</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="DataDx.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the script may look a little complicated; I could have simply written</span></span>
<span id="cb87-2"><a href="DataDx.html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co"># describe(item_scores_df) #it would have given me descriptives for all the items in the df</span></span>
<span id="cb87-3"><a href="DataDx.html#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="co"># because I only wanted a few variables, I provided them in a concatenated: list [c(&quot;iBIPOC_pr&quot;, &quot;cmBlack&quot;, &quot;Belonging&quot;, &quot;ClimateBL&quot;)]</span></span>
<span id="cb87-4"><a href="DataDx.html#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co"># I also added &quot;psych::&quot; in front of the command to make sure that R is using the describe function from the psych package</span></span>
<span id="cb87-5"><a href="DataDx.html#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="co"># I popped the output into an object; objects are not required, but can be helpful to write as outfiles, to pipe elements of inline text, and to use with packages like apaTables</span></span>
<span id="cb87-6"><a href="DataDx.html#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="co"># When we use an object, we need to write it below so the results will display</span></span>
<span id="cb87-7"><a href="DataDx.html#cb87-7" aria-hidden="true" tabindex="-1"></a>descriptives <span class="ot">&lt;-</span> (psych<span class="sc">::</span><span class="fu">describe</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;iBIPOC_pr&quot;</span>, <span class="st">&quot;cmBlack&quot;</span>, <span class="st">&quot;Belonging&quot;</span>, <span class="st">&quot;ClimateBL&quot;</span>)]))</span>
<span id="cb87-8"><a href="DataDx.html#cb87-8" aria-hidden="true" tabindex="-1"></a>descriptives</span></code></pre></div>
<pre><code>##           vars  n mean   sd median trimmed  mad min  max range  skew kurtosis
## iBIPOC_pr    1 48 0.33 0.39   0.25    0.29 0.37   0  1.0   1.0  0.78    -0.96
## cmBlack      2 50 6.56 7.48   5.00    5.20 7.41   0 29.0  29.0  1.31     1.02
## Belonging    3 48 4.18 1.47   4.00    4.18 1.48   1  7.0   6.0 -0.02    -0.84
## ClimateBL    4 46 2.46 1.09   2.33    2.42 1.48   1  4.5   3.5  0.29    -1.15
##             se
## iBIPOC_pr 0.06
## cmBlack   1.06
## Belonging 0.21
## ClimateBL 0.16</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="DataDx.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span> (descriptives, <span class="at">file=</span><span class="st">&quot;DataDx_descripts.csv&quot;</span>) <span class="co">#this can be useful if you wish to manually format the data for an APA style table</span></span></code></pre></div>
<p>To understand whether our data are normally distributed, we can look at skew and kurtosis. The skew and kurtosis indices in the psych package are reported as <em>z</em> scores. Regarding skew, values &gt; 3.0 are generally considered “severely skewed.” Regarding kurtosis, “severely kurtotic” is argued anywhere &gt; 8 to 20 <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">Kline, 2016</a>)</span>. At the time I am writing this chapter, our skew and kurtosis values fall below the thresholds that Kline identified as concerning.</p>
<p>We can also apply the Shapiro-Wilk test of normality to each of our variables. When the <span class="math inline">\(p\)</span> value is &lt; .05, the variable’s distribution is deviates from a normal distribution to a degree that is statistically significant. Below, the plotting of the histogram with a normal curve superimposed shows how the distribution approximates one that is normal.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="DataDx.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The shapiro-test is in base R; it&#39;s specification is simple:  shapiro.test(df$variable)</span></span>
<span id="cb90-2"><a href="DataDx.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="co">#I added the object (and had to list it below) so I can use the inline text function</span></span>
<span id="cb90-3"><a href="DataDx.html#cb90-3" aria-hidden="true" tabindex="-1"></a>SWt_i <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(item_scores_df<span class="sc">$</span>iBIPOC_pr)</span>
<span id="cb90-4"><a href="DataDx.html#cb90-4" aria-hidden="true" tabindex="-1"></a>SWt_cm <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(item_scores_df<span class="sc">$</span>cmBlack)</span>
<span id="cb90-5"><a href="DataDx.html#cb90-5" aria-hidden="true" tabindex="-1"></a>SWt_Bel <span class="ot">&lt;-</span><span class="fu">shapiro.test</span>(item_scores_df<span class="sc">$</span>Belonging)</span>
<span id="cb90-6"><a href="DataDx.html#cb90-6" aria-hidden="true" tabindex="-1"></a>SWt_Cl <span class="ot">&lt;-</span><span class="fu">shapiro.test</span>(item_scores_df<span class="sc">$</span>ClimateBL)</span>
<span id="cb90-7"><a href="DataDx.html#cb90-7" aria-hidden="true" tabindex="-1"></a>SWt_i</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  item_scores_df$iBIPOC_pr
## W = 0.75717, p-value = 1.585e-07</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="DataDx.html#cb92-1" aria-hidden="true" tabindex="-1"></a>SWt_cm</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  item_scores_df$cmBlack
## W = 0.81606, p-value = 2.098e-06</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="DataDx.html#cb94-1" aria-hidden="true" tabindex="-1"></a>SWt_Bel</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  item_scores_df$Belonging
## W = 0.97779, p-value = 0.4901</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="DataDx.html#cb96-1" aria-hidden="true" tabindex="-1"></a>SWt_Cl</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  item_scores_df$ClimateBL
## W = 0.93256, p-value = 0.01043</code></pre>
<p>CUMULATIVE CAPTURE FOR THE APA STYLE WRITE-UP: Regarding the distributional characteristics of the data, skew and kurtosis values of the variables fell below the values of 3 (skew) and 8 to 20 (kurtosis) that Kline suggests are concerning <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span>. Results of the Shapiro-Wilk test of normality indicate that our variables assessing the proportion of classmates who are Black (<span class="math inline">\(W\)</span> = 0.816, <span class="math inline">\(p\)</span> = 0.0000) and the proportion of BIPOC instructional staff(<span class="math inline">\(W\)</span> = 0.757, <span class="math inline">\(p\)</span> = 0.0000) are statistically significantly different than a normal distribution. The scales assessing the respondent’s belonging (<span class="math inline">\(W\)</span> = 0.978, <span class="math inline">\(p\)</span> = 0.4901) and the respondent’s perception of campus climate for Black students (<span class="math inline">\(W\)</span> = 0.933, <span class="math inline">\(p\)</span> = 0.0104) did not differ differently from a normal distribution.</p>
<p><em>Note. Owing to the open nature of the dataset, these values will change. While I have used inline text to update the values of the Shapiro Wilks’ and associated significance test, the text narration is not automatically updated and may be inconsistent with the results.</em></p>
<p>What would we do in the case of a univariate outlier? I find Kline’s <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span> chapter on data preparation and management to be extremely useful. He provides ideas for more complex analysis of both univariate and multivariate normality and provides suggestions that range from recoding an extreme value to the next most extreme that is within three standard deviations of the mean to more complicated transformations. First, though we need to further examine the relationships between variables. We do that, next.</p>
</div>
<div id="pairs-panels" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Pairs Panels</h3>
<p>As we work our way from univariate to multivariate inspection of our data, let’s take a look at the bivariate relations.</p>
<p>The <em>pairs.panels()</em> function from the <em>psych</em> package is useful for showing the relationship between variables (probably no more than 10) in a model.</p>
<ul>
<li>The lower half is a scatterplot between the two variables with a regression line (red) and mean (dot).<br />
</li>
<li>The diagonal is a histogram of each variable.<br />
</li>
<li>The upper half of is the correlation coefficient between the two variables.</li>
</ul>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="DataDx.html#cb98-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">pairs.panels</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;iBIPOC_pr&quot;</span>, <span class="st">&quot;cmBlack&quot;</span>, <span class="st">&quot;Belonging&quot;</span>, <span class="st">&quot;ClimateBL&quot;</span>)], <span class="at">stars =</span> <span class="cn">TRUE</span>, <span class="at">lm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="ReC_MultMod_files/figure-html/pairs%20panels-1.svg" width="672" /></p>
<p>The histograms displayed in the diagonal graph for us what we learned from the Shapiro Wilk’s test of normality. We can clearly see the non-normal distribution in the iBIPOC_pr and cmBlack variables.</p>
</div>
</div>
<div id="evaluating-multivariate-normality" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Evaluating Multivariate Normality</h2>
<p><strong>Multivariate outliers</strong> have extreme scores on two or more variables, or a pattern of scores that is atypical. For example, a case may have scores between two and three standard deviations above the mean on all variables, even though no case would be extreme. A common method of multivariate outlier detection is the <strong>Mahalanobis distance</strong> (<span class="math inline">\(D_{M}^{2}\)</span>). This indicates the distance in variance units between the profile of scores for that case and the vector of sample means, or <strong>centroid</strong>, correcting for intercorrelations.</p>
<p>The <em>outlier()</em> function from the <em>psych</em> package tells us how far each datapoint is from the multivariate centroid of the data. That is, find the squared Mahalanobis distance for each data point and compare it to the expected values of <span class="math inline">\(\chi^2\)</span>. The <em>outlier()</em> protocol also produces a Q-Q (quantile-quantile) plot with the <em>n</em> most extreme data points labeled.</p>
<p>The code below appends the Mahalanobis values to the dataframe. It is easy, then, to identify, sort, and examine the most extreme values (relative to the rest of the data in their case/row) to make decisions about their retention or adjustment.</p>
<p>Numeric variables are required in the for the calculation of the Mahalanobis.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="DataDx.html#cb99-1" aria-hidden="true" tabindex="-1"></a>item_scores_df<span class="sc">$</span>Mahal <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">outlier</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;iBIPOC_pr&quot;</span>, <span class="st">&quot;cmBlack&quot;</span>, <span class="st">&quot;Belonging&quot;</span>, <span class="st">&quot;ClimateBL&quot;</span>)]) </span></code></pre></div>
<p><img src="ReC_MultMod_files/figure-html/Detect%20multivariate%20outliers-1.svg" width="672" /></p>
<p>Q-Q plots take your sample data, sort it in ascending order, and then plot them versus quantiles (the number varies; you can see it on the X axis) calculated from a theoretical distribution. The number of quantiles is selected to match the size of your sample data. While Normal Q-Q Plots are the ones most often used in practice due to so many statistical methods assuming normality, Q-Q Plots can actually be created for any distribution. To the degree that the plotted line stays on the straight line (representing the theoretical normal distribution), the data is multivariate normally distributed.</p>
<p>It is possible, then to analyze the Mahalanobis distance values.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="DataDx.html#cb100-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(item_scores_df<span class="sc">$</span>Mahal)</span></code></pre></div>
<pre><code>##    vars  n mean  sd median trimmed  mad  min   max range skew kurtosis   se
## X1    1 50 3.78 2.3   3.65    3.56 2.34 0.38 11.33 10.95 0.99     1.13 0.32</code></pre>
<p>Using this information we can determine cases that have a Mahalanobis distance values that exceeds three standard deviations around the median. In fact, we can have these noted in a column in the dataframe.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="DataDx.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb102-2"><a href="DataDx.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="co">#str(item_scores_df$Mahal)</span></span>
<span id="cb102-3"><a href="DataDx.html#cb102-3" aria-hidden="true" tabindex="-1"></a>item_scores_df<span class="sc">$</span>MOutlier <span class="ot">&lt;-</span> <span class="fu">if_else</span>(item_scores_df<span class="sc">$</span>Mahal <span class="sc">&gt;</span> (<span class="fu">median</span>(item_scores_df<span class="sc">$</span>Mahal) <span class="sc">+</span> (<span class="dv">3</span><span class="sc">*</span><span class="fu">sd</span>(item_scores_df<span class="sc">$</span>Mahal))), <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb102-4"><a href="DataDx.html#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="DataDx.html#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb102-6"><a href="DataDx.html#cb102-6" aria-hidden="true" tabindex="-1"></a>OutlierCount <span class="ot">&lt;-</span> item_scores_df<span class="sc">%&gt;%</span></span>
<span id="cb102-7"><a href="DataDx.html#cb102-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOutlier)</span>
<span id="cb102-8"><a href="DataDx.html#cb102-8" aria-hidden="true" tabindex="-1"></a>OutlierCount</span></code></pre></div>
<pre><code>##   MOutlier  n
## 1    FALSE 49
## 2     TRUE  1</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="DataDx.html#cb104-1" aria-hidden="true" tabindex="-1"></a>NumOutliers <span class="ot">&lt;-</span> <span class="fu">nrow</span>(item_scores_df) <span class="sc">-</span> OutlierCount <span class="co">#calculating how many outliers</span></span>
<span id="cb104-2"><a href="DataDx.html#cb104-2" aria-hidden="true" tabindex="-1"></a>NumOutliers <span class="co">#this object is used for the inline text for the reesults</span></span></code></pre></div>
<pre><code>##   MOutlier  n
## 1       50  1
## 2       49 49</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="DataDx.html#cb106-1" aria-hidden="true" tabindex="-1"></a>NumOutliers</span></code></pre></div>
<pre><code>##   MOutlier  n
## 1       50  1
## 2       49 49</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="DataDx.html#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(item_scores_df) <span class="co">#shows us the first 6 rows of the data so we can see the new variables (Mahal, MOutlier)</span></span></code></pre></div>
<pre><code>##   ID iBIPOC_pr cmBlack Belong_1 Belong_2 Belong_3 Blst_1 Blst_2 Blst_3 Blst_4
## 1  1 0.3333333       0        6        6        7      5      3      5      2
## 2  2 0.0000000       5        4        4        6      6      6      2      2
## 3  3 0.5000000      10       NA        3       NA     NA      5      2      2
## 4  4 0.3333333       6        5        3        2      2      2      2      2
## 5  5 1.0000000       5        4        4        4      6      1      1      1
## 6  6 0.0000000      20        5        6        5      5      1      1      2
##   Blst_5 Blst_6 rBlst_1 Belonging ResponseBL StigmaBL ClimateBL     Mahal
## 1      2      2       3      6.33       2.33     3.33      2.83 2.9474599
## 2      4      1       2      4.67       1.67     4.00      2.83 1.0363038
## 3     NA      2      NA        NA       2.00     3.50        NA 0.4759603
## 4      2      2       6      3.33       3.33     2.00      2.67 0.3795770
## 5      1      1       2      4.00       1.33     1.00      1.17 3.9774323
## 6      1      2       3      5.33       2.33     1.00      1.67 5.2238187
##   MOutlier
## 1    FALSE
## 2    FALSE
## 3    FALSE
## 4    FALSE
## 5    FALSE
## 6    FALSE</code></pre>
<p>CUMULATIVE CAPTURE FOR THE APA STYLE WRITE-UP: We evaluated multivariate normality with the Mahalanobis distance test. Specifically, we used the <em>outlier()</em> function in the <em>psych</em> package and included all continuous variables in the calculation. Our visual inspection of the Q-Q plot suggested that the plotted line strayed from the straight line as the quantiles increased. Additionally, we appended the Mahalanobis distance scores as a variable to the data. Analyzing this variable, we found that 1, 49 exceed three standard deviations beyond the median. <em>Thus, with no outliers, we assumed multivariate normality and proceeded with the data analysis</em> AS DATA IS ADDED THIS NUMBER OF OUTLIERS COULD UPDATE FROM ZERO AND THIS TEXT COULD CHANGE.</p>
</div>
<div id="a-few-words-on-transformations" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> A Few Words on Transformations</h2>
<p>To quote from Kline <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span>, “Before applying a normalizing transformation, you should think about the variables of interest and whether the expectation of normality is reasonable.” (p. 77)</p>
<p>At this point in history, the non-normal distribution of the proportions of classmates who are Black and instructional staff who are BIPOC are accurate representations in higher education. Kline <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span> has noted that transforming an inherently non-normal variable to force a normal distribution may fundamentally alter it such that the variable of interest is not actually studied. Kline’s chapter reviews some options for applying corrections to outliers. Additionally, the chapter describes a variety of normalizing transformations.</p>
<p>On a personal note, while I will use stadardized scores (a linear transformation) if it improves interpretation and center variables around a meaningful intercept, I tend to resist the transformation of data without a really compelling reason. Why? It’s complicated and can make interpretation difficult.</p>
</div>
<div id="the-apa-style-write-up-1" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> The APA Style Write-Up</h2>
<p>Since the focus of this chapter was on data diagnostics, the APA style writeup will focus on on this element of the Method section:</p>
<div id="data-diagnostics" class="section level3" number="4.8.1">
<h3><span class="header-section-number">4.8.1</span> Data Diagnostics</h3>
<p>Data screening suggested that 75 individuals opened the survey link. Of those, 60 granted consent and proceeded to the survey items. A further inclusion criteria was that the course was taught in the U.S; 52 met this criteria.</p>
<p>Available item analysis (AIA; <span class="citation">(<a href="#ref-parent_handling_2013" role="doc-biblioref">Parent, 2013</a>)</span>) is a strategy for managing missing data that uses available data for analysis and excludes cases with missing data points only for analyses in which the data points would be directly involved. Parent (2013) suggested that AIA is equivalent to more complex methods (e.g., multiple imputation) across a number of variations of sample size, magnitude of associations among items, and degree of missingness. Thus, we utilized Parent’s recommendations to guide our approach to managing missing data. Missing data analyses were conducted with tools in base R as well as the R packages, <em>psych</em> (v. 1.0.12) and <em>mice</em> (v. 3.13.0).</p>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0% to 91%. Across the dataset, 4.18% of cells had missing data and 86.00% of cases had nonmissing data. At this stage in the analysis, we allowed all cases with less than 90% missing to continue to the scoring stage. Guided by Parent’s <span class="citation">(<a href="#ref-parent_handling_2013" role="doc-biblioref">2013</a>)</span> AIA approach, scales with three items were scored if at least two items were non-missing; the scale with four items was scored if it at least three non-missing items; and the scale with six items was scored if it had at least five non-missing items.</p>
<p>Across the 50 cases for which the scoring protocol was applied, missingness ranged from 0% to 67%. After eliminating cases with greater than 20% missing, the dataset analyzed included 46 cases. In this dataset we had 0.72% missing across the df; 95.65% of the rows had nonmissing data.</p>
<p>Regarding the distributional characteristics of the data, skew and kurtosis values of the variables fell below the values of 3 (skew) and 8 to 20 (kurtosis) that Kline suggests are concerning <span class="citation">(<a href="#ref-kline_principles_2016" role="doc-biblioref">2016</a>)</span>. Results of the Shapiro-Wilk test of normality indicate that our variables assessing the proportion of classmates who are Black (<span class="math inline">\(W\)</span> = 0.816, <span class="math inline">\(p\)</span> = 0.0000) and the proportion of BIPOC instructional staff(<span class="math inline">\(W\)</span> = 0.757, <span class="math inline">\(p\)</span> = 0.0000) are statistically significantly different than a normal distribution. The scales assessing the respondent’s belonging (<span class="math inline">\(W\)</span> = 0.978, <span class="math inline">\(p\)</span> = 0.4901) and the respondent’s perception of campus climate for Black students (<span class="math inline">\(W\)</span> = 0.933, <span class="math inline">\(p\)</span> = 0.0104) did not differ differently from a normal distribution.</p>
<p>We evaluated multivariate normality with the Mahalanobis distance test. Specifically, we used the <em>outlier()</em> function in the <em>psych</em> package and included all continuous variables in the calculation. Our visual inspection of the Q-Q plot suggested that the plotted line strayed from the straight line as the quantiles increased. Additionally, we appended the Mahalanobis distance scores as a variable to the data. Analyzing this variable, we found that 1, 49 exceed three standard deviations beyond the median. <em>Thus, with no outliers, we assumed multivariate normality and proceeded with the data analysis</em> AS DATA IS ADDED THIS NUMBER OF OUTLIERS COULD UPDATE FROM ZERO AND THIS TEXT COULD CHANGE.</p>
<p>Given that our sample sizes were reasonable for the planned analyses and the degree of missingness was low, we used pairwise deletion in our multiple regression analysis.</p>
</div>
</div>
<div id="a-quick-regression-of-our-research-vignette" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> A Quick Regression of our Research Vignette</h2>
<p>With some confidence that our scrubbed-and-scored variables are appropriate for analysis, let me conduct the super quick regression that is our research vignette.</p>
<div class="figure">
<img src="images/Ch04/BlStuRegression.jpg" alt="" />
<p class="caption">An image of the statistical model for which we are preparing data.</p>
</div>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="DataDx.html#cb110-1" aria-hidden="true" tabindex="-1"></a>Climate_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(ClimateBL <span class="sc">~</span> Belonging <span class="sc">+</span> cmBlack <span class="sc">+</span> iBIPOC_pr, <span class="at">data =</span> item_scores_df)</span>
<span id="cb110-2"><a href="DataDx.html#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Climate_fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ClimateBL ~ Belonging + cmBlack + iBIPOC_pr, data = item_scores_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.93429 -0.81101 -0.06069  0.72280  1.94092 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.06548    0.52308   5.860 7.43e-07 ***
## Belonging   -0.05630    0.11372  -0.495    0.623    
## cmBlack     -0.02758    0.02093  -1.318    0.195    
## iBIPOC_pr   -0.69730    0.41999  -1.660    0.105    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.063 on 40 degrees of freedom
##   (6 observations deleted due to missingness)
## Multiple R-squared:  0.1097, Adjusted R-squared:  0.04289 
## F-statistic: 1.642 on 3 and 40 DF,  p-value: 0.1949</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="DataDx.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Climate_fit)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;na.action&quot;     &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;        
## [13] &quot;model&quot;</code></pre>
<p>Results of a multiple regression predicting the respondents’ perceptions of campus climate for Black students indicated that neither contributions of the respondents’ personal belonging (<span class="math inline">\(B\)</span> = -0.056, <span class="math inline">\(p\)</span> = 0.623) nor the proportion of BIPOC instructional staff (<span class="math inline">\(B\)</span> = -0.697, <span class="math inline">\(p\)</span> = 0.105), nor the proportion of Black classmates (<span class="math inline">\(B\)</span> = -0.028, <span class="math inline">\(p\)</span> = 0.195) led to statistically significant changes in perceptions of campus climate for Black students. Although it accounted for 10.97% of the variance, the overall model was not statistically significant. Results are presented in Table 2.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="DataDx.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb114-2"><a href="DataDx.html#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apa.cor.table</span>(item_scores_df[<span class="fu">c</span>(<span class="st">&quot;iBIPOC_pr&quot;</span>, <span class="st">&quot;cmBlack&quot;</span>, <span class="st">&quot;Belonging&quot;</span>, <span class="st">&quot;ClimateBL&quot;</span>)], <span class="at">table.number =</span> <span class="dv">1</span>, <span class="at">show.sig.stars =</span> <span class="cn">TRUE</span>, <span class="at">filename =</span> <span class="st">&quot;Table1_M_SDs_r_DataDx.doc&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 
## Table 1 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable     M    SD   1           2           3          
##   1. iBIPOC_pr 0.33 0.39                                    
##                                                             
##   2. cmBlack   6.56 7.48 -.05                               
##                          [-.33, .24]                        
##                                                             
##   3. Belonging 4.18 1.47 .21         -.08                   
##                          [-.08, .47] [-.35, .21]            
##                                                             
##   4. ClimateBL 2.46 1.09 -.26        -.19        -.16       
##                          [-.52, .04] [-.45, .11] [-.43, .14]
##                                                             
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
##  * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="DataDx.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb116-2"><a href="DataDx.html#cb116-2" aria-hidden="true" tabindex="-1"></a>apaTables<span class="sc">::</span><span class="fu">apa.reg.table</span>(Climate_fit, <span class="at">table.number =</span> <span class="dv">2</span>, <span class="at">filename =</span> <span class="st">&quot;Climate_table.doc&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 
## Table 2 
## 
## Regression results using ClimateBL as the criterion
##  
## 
##    Predictor      b      b_95%_CI  beta   beta_95%_CI sr2  sr2_95%_CI    r
##  (Intercept) 3.07**  [2.01, 4.12]                                         
##    Belonging  -0.06 [-0.29, 0.17] -0.08 [-0.38, 0.23] .01 [-.04, .05] -.11
##      cmBlack  -0.03 [-0.07, 0.01] -0.20 [-0.50, 0.11] .04 [-.07, .15] -.18
##    iBIPOC_pr  -0.70 [-1.55, 0.15] -0.25 [-0.56, 0.05] .06 [-.07, .20] -.26
##                                                                           
##                                                                           
##                                                                           
##              Fit
##                 
##                 
##                 
##                 
##        R2 = .110
##  95% CI[.00,.26]
##                 
## 
## Note. A significant b-weight indicates the beta-weight and semi-partial correlation are also significant.
## b represents unstandardized regression weights. beta indicates the standardized regression weights. 
## sr2 represents the semi-partial correlation squared. r represents the zero-order correlation.
## Square brackets are used to enclose the lower and upper limits of a confidence interval.
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
</div>
<div id="practice-problems-2" class="section level2" number="4.10">
<h2><span class="header-section-number">4.10</span> Practice Problems</h2>
<p>The three problems described below are designed to be continuations from the previous chapter (Scrubbing). You will likely encounter challenges that were not covered in this chapter. Search for and try out solutions, knowing that there are multiple paths through the analysis.</p>
<div id="problem-1-reworking-the-chapter-problem-1" class="section level3" number="4.10.1">
<h3><span class="header-section-number">4.10.1</span> Problem #1: Reworking the Chapter Problem</h3>
<p>If you chose this option in the prior chapters, you imported the data from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, properly formatted the variables, interpreted item-level missingness, scored the scales/subscales, interpreted scale-level missingness, and wrote up the results.</p>
<p>If you continue with this option, please continue working with the data to:</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Calculate alpha coefficients for scales/subscales.</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Evaluate univariate normality (skew, kurtosis, Shapiro-Wilks).</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Evaluate multivarite normality (Mahalanobis test)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. For fun, run a quick analysis (e.g., regression, ANOVA) including at least three variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">30</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-2" class="section level3" number="4.10.2">
<h3><span class="header-section-number">4.10.2</span> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</h3>
<p>If you chose this option in the prior chapter, you chose a minimum of three variables from the <em>Rate-a-Recent-Course</em> survey to include in a simple statistical model. You imported the data from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, properly formatted the variables, interpreted item-level missingness, scored the scales/subscales, interpreted scale-level missingness, and wrote up the results.</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Calculate alpha coefficients for scales/subscales.</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Evaluate univariate normality (skew, kurtosis, Shapiro-Wilks).</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Evaluate multivarite normality (Mahalanobis test)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. For fun, run a quick analysis (e.g., regression, ANOVA) including at least three variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">30</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-3-other-data-2" class="section level3" number="4.10.3">
<h3><span class="header-section-number">4.10.3</span> Problem #3: Other data</h3>
<p>If you chose this option in the prior chapter, you used raw data that was available to you. You imported it into R, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, properly formatted the variables, interpreted item-level missingness, scored the scales/subscales, interpreted scale-level missingness, and wrote up the results.</p>
<p>Continue working with this data to:</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Calculate alpha coefficients for scales/subscales.</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Evaluate univariate normality (skew, kurtosis, Shapiro-Wilks).</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Evaluate multivarite normality (Mahalanobis test)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. For fun, run a quick analysis (e.g., regression, ANOVA) including at least three variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">30</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="DataDx.html#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>## R version 4.1.3 (2022-03-10)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 18363)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] apaTables_2.0.8   mice_3.13.0       sjstats_0.18.1    formattable_0.2.1
##  [5] qualtRics_3.1.4   forcats_0.5.1     stringr_1.4.0     dplyr_1.0.7      
##  [9] purrr_0.3.4       readr_2.0.1       tidyr_1.1.3       tibble_3.1.4     
## [13] ggplot2_3.3.5     tidyverse_1.3.1   psych_2.1.6      
## 
## loaded via a namespace (and not attached):
##  [1] nlme_3.1-155       fs_1.5.0           lubridate_1.7.10   bit64_4.0.5       
##  [5] MBESS_4.8.0        insight_0.14.4     httr_1.4.2         tools_4.1.3       
##  [9] backports_1.2.1    bslib_0.3.0        utf8_1.2.2         R6_2.5.1          
## [13] sjlabelled_1.1.8   DBI_1.1.1          colorspace_2.0-2   withr_2.4.2       
## [17] tidyselect_1.1.1   mnormt_2.0.2       emmeans_1.6.3      bit_4.0.4         
## [21] curl_4.3.2         compiler_4.1.3     performance_0.7.3  cli_3.0.1         
## [25] rvest_1.0.1        xml2_1.3.2         sandwich_3.0-1     bookdown_0.24     
## [29] bayestestR_0.11.0  sass_0.4.0         scales_1.1.1       mvtnorm_1.1-2     
## [33] systemfonts_1.0.2  digest_0.6.27      minqa_1.2.4        svglite_2.0.0     
## [37] rmarkdown_2.10     pkgconfig_2.0.3    htmltools_0.5.2    lme4_1.1-27.1     
## [41] highr_0.9          dbplyr_2.1.1       fastmap_1.1.0      htmlwidgets_1.5.4 
## [45] rlang_0.4.11       readxl_1.3.1       rstudioapi_0.13    jquerylib_0.1.4   
## [49] generics_0.1.0     zoo_1.8-9          jsonlite_1.7.2     vroom_1.5.4       
## [53] magrittr_2.0.1     Matrix_1.4-0       parameters_0.14.0  Rcpp_1.0.7        
## [57] munsell_0.5.0      fansi_0.5.0        lifecycle_1.0.0    stringi_1.7.4     
## [61] multcomp_1.4-17    yaml_2.2.1         MASS_7.3-55        grid_4.1.3        
## [65] parallel_4.1.3     sjmisc_2.8.7       crayon_1.4.1       lattice_0.20-45   
## [69] splines_4.1.3      haven_2.4.3        hms_1.1.0          tmvnsim_1.0-2     
## [73] knitr_1.34         pillar_1.6.2       boot_1.3-28        estimability_1.3  
## [77] effectsize_0.4.5   codetools_0.2-18   reprex_2.0.1       glue_1.4.2        
## [81] evaluate_0.14      modelr_0.1.8       nloptr_1.2.2.2     vctrs_0.3.8       
## [85] tzdb_0.1.2         cellranger_1.1.0   gtable_0.3.0       assertthat_0.2.1  
## [89] datawizard_0.2.0.1 xfun_0.25          xtable_1.8-4       broom_0.7.9       
## [93] coda_0.19-4        survival_3.2-13    TH.data_1.1-0      ellipsis_0.3.2</code></pre>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bollen_perceived_1990" class="csl-entry">
Bollen, K. A., &amp; Hoyle, R. H. (1990). Perceived cohesion: <span>A</span> conceptual and empirical examination. <em>Social Forces</em>, <em>69</em>(2), 479–504. <a href="https://doi.org/10.2307/2579670">https://doi.org/10.2307/2579670</a>
</div>
<div id="ref-cortina_what_1993" class="csl-entry">
Cortina, J. M. (1993). What is coefficient alpha? <span>An</span> examination of theory and applications. <em>Journal of Applied Psychology</em>, <em>78</em>(1), 98–104. <a href="https://doi.org/10.1037/0021-9010.78.1.98">https://doi.org/10.1037/0021-9010.78.1.98</a>
</div>
<div id="ref-kline_principles_2016" class="csl-entry">
Kline, R. B. (2016). <em>Principles and practice of structural equation modeling</em> (4th ed.). Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a>
</div>
<div id="ref-parent_handling_2013" class="csl-entry">
Parent, M. C. (2013). Handling item-level missing data: <span>Simpler</span> is just as good. <em>The Counseling Psychologist</em>, <em>41</em>(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176">https://doi.org/10.1177/0011000012445176</a>
</div>
<div id="ref-sijtsma_use_2009" class="csl-entry">
Sijtsma, K. (2009). On the <span>Use</span>, the <span>Misuse</span>, and the <span>Very</span> <span>Limited</span> <span>Usefulness</span> of <span>Cronbach</span>’s <span>Alpha</span>. <em>Psychometrika</em>, <em>74</em>(1), 107–120. <a href="https://doi.org/10.1007/s11336-008-9101-0">https://doi.org/10.1007/s11336-008-9101-0</a>
</div>
<div id="ref-szymanski_perceptions_2020" class="csl-entry">
Szymanski, D. M., &amp; Bissonette, D. (2020). Perceptions of the <span>LGBTQ</span> <span>College</span> <span>Campus</span> <span>Climate</span> <span>Scale</span>: <span>Development</span> and <span>Psychometric</span> <span>Evaluation</span>. <em>Journal of Homosexuality</em>, <em>67</em>(10), 1412–1428. <a href="https://doi.org/10.1080/00918369.2019.1591788">https://doi.org/10.1080/00918369.2019.1591788</a>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="score.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multimp.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/ontheline/otl-bookdown/blob/master/04-DataDx.Rmd",
"text": null
},
"download": ["ReC_MultMod.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
