<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Scoring | ReCentering Psych Stats: Multivariate Modeling</title>
  <meta name="description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Scoring | ReCentering Psych Stats: Multivariate Modeling" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://lhbikos.github.io/ReC_MultivModel/images/ReC_multivariate_bkcvr.png" />
  <meta property="og:description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="github-repo" content="lhbikos/extRas" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Scoring | ReCentering Psych Stats: Multivariate Modeling" />
  
  <meta name="twitter:description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="twitter:image" content="https://lhbikos.github.io/ReC_MultivModel/images/ReC_multivariate_bkcvr.png" />

<meta name="author" content="Lynette H. Bikos, PhD, ABPP" />


<meta name="date" content="2023-10-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scrub.html"/>
<link rel="next" href="DataDx.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ReCentering Psych Stats</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>BOOK COVER</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>PREFACE</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>ACKNOWLEDGEMENTS</a></li>
<li class="chapter" data-level="" data-path="dataprep.html"><a href="dataprep.html"><i class="fa fa-check"></i>DATA PREP</a></li>
<li class="chapter" data-level="1" data-path="scrub.html"><a href="scrub.html"><i class="fa fa-check"></i><b>1</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="1.1" data-path="scrub.html"><a href="scrub.html#navigating-this-lesson"><i class="fa fa-check"></i><b>1.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="scrub.html"><a href="scrub.html#learning-objectives"><i class="fa fa-check"></i><b>1.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="scrub.html"><a href="scrub.html#planning-for-practice"><i class="fa fa-check"></i><b>1.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="1.1.3" data-path="scrub.html"><a href="scrub.html#readings-resources"><i class="fa fa-check"></i><b>1.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="1.1.4" data-path="scrub.html"><a href="scrub.html#packages"><i class="fa fa-check"></i><b>1.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="scrub.html"><a href="scrub.html#workflow-for-scrubbing"><i class="fa fa-check"></i><b>1.2</b> Workflow for Scrubbing</a></li>
<li class="chapter" data-level="1.3" data-path="scrub.html"><a href="scrub.html#research-vignette"><i class="fa fa-check"></i><b>1.3</b> Research Vignette</a></li>
<li class="chapter" data-level="1.4" data-path="scrub.html"><a href="scrub.html#working-the-problem"><i class="fa fa-check"></i><b>1.4</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="scrub.html"><a href="scrub.html#intravenous-qualtrics"><i class="fa fa-check"></i><b>1.4.1</b> intRavenous Qualtrics</a></li>
<li class="chapter" data-level="1.4.2" data-path="scrub.html"><a href="scrub.html#about-the-rate-a-recent-course-survey"><i class="fa fa-check"></i><b>1.4.2</b> About the <em>Rate-a-Recent-Course</em> Survey</a></li>
<li class="chapter" data-level="1.4.3" data-path="scrub.html"><a href="scrub.html#the-codebook"><i class="fa fa-check"></i><b>1.4.3</b> The Codebook</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="scrub.html"><a href="scrub.html#scrubbing"><i class="fa fa-check"></i><b>1.5</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="scrub.html"><a href="scrub.html#tools-for-data-manipulation"><i class="fa fa-check"></i><b>1.5.1</b> Tools for Data Manipulation</a></li>
<li class="chapter" data-level="1.5.2" data-path="scrub.html"><a href="scrub.html#inclusion-and-exclusion-criteria"><i class="fa fa-check"></i><b>1.5.2</b> Inclusion and Exclusion Criteria</a></li>
<li class="chapter" data-level="1.5.3" data-path="scrub.html"><a href="scrub.html#renaming-variables"><i class="fa fa-check"></i><b>1.5.3</b> Renaming Variables</a></li>
<li class="chapter" data-level="1.5.4" data-path="scrub.html"><a href="scrub.html#downsizing-the-dataframe"><i class="fa fa-check"></i><b>1.5.4</b> Downsizing the Dataframe</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="scrub.html"><a href="scrub.html#toward-the-apa-style-write-up"><i class="fa fa-check"></i><b>1.6</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="scrub.html"><a href="scrub.html#methodprocedure"><i class="fa fa-check"></i><b>1.6.1</b> Method/Procedure</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scrub.html"><a href="scrub.html#practice-problems"><i class="fa fa-check"></i><b>1.7</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="scrub.html"><a href="scrub.html#problem-1-rework-the-chapter-problem"><i class="fa fa-check"></i><b>1.7.1</b> Problem #1: Rework the Chapter Problem</a></li>
<li class="chapter" data-level="1.7.2" data-path="scrub.html"><a href="scrub.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables"><i class="fa fa-check"></i><b>1.7.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="1.7.3" data-path="scrub.html"><a href="scrub.html#problem-3-other-data"><i class="fa fa-check"></i><b>1.7.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="1.7.4" data-path="scrub.html"><a href="scrub.html#grading-rubric"><i class="fa fa-check"></i><b>1.7.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="scrub.html"><a href="scrub.html#bonus-track"><i class="fa fa-check"></i><b>1.8</b> Bonus Track:</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="scrub.html"><a href="scrub.html#importing-data-from-an-exported-qualtrics-.csv-file"><i class="fa fa-check"></i><b>1.8.1</b> Importing data from an exported Qualtrics .csv file</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="score.html"><a href="score.html"><i class="fa fa-check"></i><b>2</b> Scoring</a>
<ul>
<li class="chapter" data-level="2.1" data-path="score.html"><a href="score.html#navigating-this-lesson-1"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="score.html"><a href="score.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="score.html"><a href="score.html#planning-for-practice-1"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="score.html"><a href="score.html#readings-resources-1"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="2.1.4" data-path="score.html"><a href="score.html#packages-1"><i class="fa fa-check"></i><b>2.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="score.html"><a href="score.html#workflow-for-scoring"><i class="fa fa-check"></i><b>2.2</b> Workflow for Scoring</a></li>
<li class="chapter" data-level="2.3" data-path="score.html"><a href="score.html#research-vignette-1"><i class="fa fa-check"></i><b>2.3</b> Research Vignette</a></li>
<li class="chapter" data-level="2.4" data-path="score.html"><a href="score.html#on-missing-data"><i class="fa fa-check"></i><b>2.4</b> On Missing Data</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="score.html"><a href="score.html#data-loss-mechanisms"><i class="fa fa-check"></i><b>2.4.1</b> Data Loss Mechanisms</a></li>
<li class="chapter" data-level="2.4.2" data-path="score.html"><a href="score.html#diagnosing-missing-data-mechanisms"><i class="fa fa-check"></i><b>2.4.2</b> Diagnosing Missing Data Mechanisms</a></li>
<li class="chapter" data-level="2.4.3" data-path="score.html"><a href="score.html#managing-missing-data"><i class="fa fa-check"></i><b>2.4.3</b> Managing Missing Data</a></li>
<li class="chapter" data-level="2.4.4" data-path="score.html"><a href="score.html#available-information-analysis-aia"><i class="fa fa-check"></i><b>2.4.4</b> Available Information Analysis (AIA)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="score.html"><a href="score.html#working-the-problem-1"><i class="fa fa-check"></i><b>2.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="score.html"><a href="score.html#variable-planning-and-preparation"><i class="fa fa-check"></i><b>2.5.1</b> Variable Planning and Preparation</a></li>
<li class="chapter" data-level="2.5.2" data-path="score.html"><a href="score.html#missing-data-analysis-whole-df-and-item-level"><i class="fa fa-check"></i><b>2.5.2</b> Missing Data Analysis: Whole df and Item level</a></li>
<li class="chapter" data-level="2.5.3" data-path="score.html"><a href="score.html#analyzing-missing-data-patterns"><i class="fa fa-check"></i><b>2.5.3</b> Analyzing Missing Data Patterns</a></li>
<li class="chapter" data-level="2.5.4" data-path="score.html"><a href="score.html#can-we-identify-the-missing-mechanisms"><i class="fa fa-check"></i><b>2.5.4</b> Can we identify the missing mechanisms?</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="score.html"><a href="score.html#scoring"><i class="fa fa-check"></i><b>2.6</b> Scoring</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="score.html"><a href="score.html#reverse-scoring"><i class="fa fa-check"></i><b>2.6.1</b> Reverse scoring</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="score.html"><a href="score.html#missing-analysis-scale-level"><i class="fa fa-check"></i><b>2.7</b> Missing Analysis: Scale level</a></li>
<li class="chapter" data-level="2.8" data-path="score.html"><a href="score.html#revisiting-missing-analysis-at-the-scale-level"><i class="fa fa-check"></i><b>2.8</b> Revisiting Missing Analysis at the Scale Level</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="score.html"><a href="score.html#scale-level-patterns-of-missing-data"><i class="fa fa-check"></i><b>2.8.1</b> Scale Level: Patterns of Missing Data</a></li>
<li class="chapter" data-level="2.8.2" data-path="score.html"><a href="score.html#r-eady-for-analysis"><i class="fa fa-check"></i><b>2.8.2</b> R-eady for Analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="score.html"><a href="score.html#the-apa-style-write-up"><i class="fa fa-check"></i><b>2.9</b> The APA Style Write-Up</a></li>
<li class="chapter" data-level="2.10" data-path="score.html"><a href="score.html#results"><i class="fa fa-check"></i><b>2.10</b> Results</a></li>
<li class="chapter" data-level="2.11" data-path="score.html"><a href="score.html#practice-problems-1"><i class="fa fa-check"></i><b>2.11</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="score.html"><a href="score.html#problem-1-reworking-the-chapter-problem"><i class="fa fa-check"></i><b>2.11.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="2.11.2" data-path="score.html"><a href="score.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1"><i class="fa fa-check"></i><b>2.11.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="2.11.3" data-path="score.html"><a href="score.html#problem-3-other-data-1"><i class="fa fa-check"></i><b>2.11.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="2.11.4" data-path="score.html"><a href="score.html#grading-rubric-1"><i class="fa fa-check"></i><b>2.11.4</b> Grading Rubric</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="DataDx.html"><a href="DataDx.html"><i class="fa fa-check"></i><b>3</b> Data Dx</a>
<ul>
<li class="chapter" data-level="3.1" data-path="DataDx.html"><a href="DataDx.html#navigating-this-lesson-2"><i class="fa fa-check"></i><b>3.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="DataDx.html"><a href="DataDx.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="DataDx.html"><a href="DataDx.html#planning-for-practice-2"><i class="fa fa-check"></i><b>3.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="3.1.3" data-path="DataDx.html"><a href="DataDx.html#readings-resources-2"><i class="fa fa-check"></i><b>3.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="3.1.4" data-path="DataDx.html"><a href="DataDx.html#packages-2"><i class="fa fa-check"></i><b>3.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="DataDx.html"><a href="DataDx.html#workflow-for-preliminary-data-diagnostics"><i class="fa fa-check"></i><b>3.2</b> Workflow for Preliminary Data Diagnostics</a></li>
<li class="chapter" data-level="3.3" data-path="DataDx.html"><a href="DataDx.html#research-vignette-2"><i class="fa fa-check"></i><b>3.3</b> Research Vignette</a></li>
<li class="chapter" data-level="3.4" data-path="DataDx.html"><a href="DataDx.html#internal-consistency-of-scalessubscales"><i class="fa fa-check"></i><b>3.4</b> Internal Consistency of Scales/Subscales</a></li>
<li class="chapter" data-level="3.5" data-path="DataDx.html"><a href="DataDx.html#distributional-characteristics-of-the-variables"><i class="fa fa-check"></i><b>3.5</b> Distributional Characteristics of the Variables</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="DataDx.html"><a href="DataDx.html#evaluating-univariate-normality"><i class="fa fa-check"></i><b>3.5.1</b> Evaluating Univariate Normality</a></li>
<li class="chapter" data-level="3.5.2" data-path="DataDx.html"><a href="DataDx.html#pairs-panels"><i class="fa fa-check"></i><b>3.5.2</b> Pairs Panels</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="DataDx.html"><a href="DataDx.html#evaluating-multivariate-normality"><i class="fa fa-check"></i><b>3.6</b> Evaluating Multivariate Normality</a></li>
<li class="chapter" data-level="3.7" data-path="DataDx.html"><a href="DataDx.html#a-few-words-on-transformations"><i class="fa fa-check"></i><b>3.7</b> A Few Words on Transformations</a></li>
<li class="chapter" data-level="3.8" data-path="DataDx.html"><a href="DataDx.html#the-apa-style-write-up-1"><i class="fa fa-check"></i><b>3.8</b> The APA Style Write-Up</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="DataDx.html"><a href="DataDx.html#data-diagnostics"><i class="fa fa-check"></i><b>3.8.1</b> Data Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="DataDx.html"><a href="DataDx.html#a-quick-regression-of-our-research-vignette"><i class="fa fa-check"></i><b>3.9</b> A Quick Regression of our Research Vignette</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="DataDx.html"><a href="DataDx.html#results-1"><i class="fa fa-check"></i><b>3.9.1</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="DataDx.html"><a href="DataDx.html#practice-problems-2"><i class="fa fa-check"></i><b>3.10</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="DataDx.html"><a href="DataDx.html#problem-1-reworking-the-chapter-problem-1"><i class="fa fa-check"></i><b>3.10.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="3.10.2" data-path="DataDx.html"><a href="DataDx.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-2"><i class="fa fa-check"></i><b>3.10.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="3.10.3" data-path="DataDx.html"><a href="DataDx.html#problem-3-other-data-2"><i class="fa fa-check"></i><b>3.10.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="3.10.4" data-path="DataDx.html"><a href="DataDx.html#grading-rubric-2"><i class="fa fa-check"></i><b>3.10.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="DataDx.html"><a href="DataDx.html#homeworked-example"><i class="fa fa-check"></i><b>3.11</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="DataDx.html"><a href="DataDx.html#scrubbing-1"><i class="fa fa-check"></i><b>3.11.1</b> Scrubbing</a></li>
<li class="chapter" data-level="3.11.2" data-path="DataDx.html"><a href="DataDx.html#scoring-1"><i class="fa fa-check"></i><b>3.11.2</b> Scoring</a></li>
<li class="chapter" data-level="3.11.3" data-path="DataDx.html"><a href="DataDx.html#data-dx"><i class="fa fa-check"></i><b>3.11.3</b> Data Dx</a></li>
<li class="chapter" data-level="3.11.4" data-path="DataDx.html"><a href="DataDx.html#results-2"><i class="fa fa-check"></i><b>3.11.4</b> Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multimp.html"><a href="multimp.html"><i class="fa fa-check"></i><b>4</b> Multiple Imputation (A Brief Demo)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multimp.html"><a href="multimp.html#navigating-this-lesson-3"><i class="fa fa-check"></i><b>4.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="multimp.html"><a href="multimp.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.1.2" data-path="multimp.html"><a href="multimp.html#planning-for-practice-3"><i class="fa fa-check"></i><b>4.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="4.1.3" data-path="multimp.html"><a href="multimp.html#readings-resources-3"><i class="fa fa-check"></i><b>4.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="4.1.4" data-path="multimp.html"><a href="multimp.html#packages-3"><i class="fa fa-check"></i><b>4.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="multimp.html"><a href="multimp.html#workflow-for-multiple-imputation"><i class="fa fa-check"></i><b>4.2</b> Workflow for Multiple Imputation</a></li>
<li class="chapter" data-level="4.3" data-path="multimp.html"><a href="multimp.html#research-vignette-3"><i class="fa fa-check"></i><b>4.3</b> Research Vignette</a></li>
<li class="chapter" data-level="4.4" data-path="multimp.html"><a href="multimp.html#multiple-imputation-a-super-brief-review"><i class="fa fa-check"></i><b>4.4</b> Multiple Imputation – a Super Brief Review</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="multimp.html"><a href="multimp.html#steps-in-multiple-imputation"><i class="fa fa-check"></i><b>4.4.1</b> Steps in Multiple Imputation</a></li>
<li class="chapter" data-level="4.4.2" data-path="multimp.html"><a href="multimp.html#statistical-approaches-to-multiple-imputation"><i class="fa fa-check"></i><b>4.4.2</b> Statistical Approaches to Multiple Imputation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="multimp.html"><a href="multimp.html#working-the-problem-2"><i class="fa fa-check"></i><b>4.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="multimp.html"><a href="multimp.html#selecting-and-formatting-variables"><i class="fa fa-check"></i><b>4.5.1</b> Selecting and Formatting Variables</a></li>
<li class="chapter" data-level="4.5.2" data-path="multimp.html"><a href="multimp.html#creating-composite-variables"><i class="fa fa-check"></i><b>4.5.2</b> Creating Composite Variables</a></li>
<li class="chapter" data-level="4.5.3" data-path="multimp.html"><a href="multimp.html#the-multiple-imputation"><i class="fa fa-check"></i><b>4.5.3</b> The Multiple Imputation</a></li>
<li class="chapter" data-level="4.5.4" data-path="multimp.html"><a href="multimp.html#creating-scale-scores"><i class="fa fa-check"></i><b>4.5.4</b> Creating Scale Scores</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="multimp.html"><a href="multimp.html#multiple-regression-with-multiply-imputed-data"><i class="fa fa-check"></i><b>4.6</b> Multiple Regression with Multiply Imputed Data</a></li>
<li class="chapter" data-level="4.7" data-path="multimp.html"><a href="multimp.html#toward-the-apa-style-write-up-1"><i class="fa fa-check"></i><b>4.7</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="multimp.html"><a href="multimp.html#methoddata-diagnostics"><i class="fa fa-check"></i><b>4.7.1</b> Method/Data Diagnostics</a></li>
<li class="chapter" data-level="4.7.2" data-path="multimp.html"><a href="multimp.html#results-3"><i class="fa fa-check"></i><b>4.7.2</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="multimp.html"><a href="multimp.html#multiple-imputation-considerations"><i class="fa fa-check"></i><b>4.8</b> Multiple imputation considerations</a></li>
<li class="chapter" data-level="4.9" data-path="multimp.html"><a href="multimp.html#practice-problems-3"><i class="fa fa-check"></i><b>4.9</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="multimp.html"><a href="multimp.html#problem-1-reworking-the-chapter-problem-2"><i class="fa fa-check"></i><b>4.9.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="4.9.2" data-path="multimp.html"><a href="multimp.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-3"><i class="fa fa-check"></i><b>4.9.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="4.9.3" data-path="multimp.html"><a href="multimp.html#problem-3-other-data-3"><i class="fa fa-check"></i><b>4.9.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="4.9.4" data-path="multimp.html"><a href="multimp.html#grading-rubric-3"><i class="fa fa-check"></i><b>4.9.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="multimp.html"><a href="multimp.html#homeworked-example-1"><i class="fa fa-check"></i><b>4.10</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="multimp.html"><a href="multimp.html#scrubbing-2"><i class="fa fa-check"></i><b>4.10.1</b> Scrubbing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MED.html"><a href="MED.html"><i class="fa fa-check"></i>MEDIATION</a></li>
<li class="chapter" data-level="5" data-path="SimpleMed.html"><a href="SimpleMed.html"><i class="fa fa-check"></i><b>5</b> Simple Mediation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="SimpleMed.html"><a href="SimpleMed.html#navigating-this-lesson-4"><i class="fa fa-check"></i><b>5.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="SimpleMed.html"><a href="SimpleMed.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="SimpleMed.html"><a href="SimpleMed.html#planning-for-practice-4"><i class="fa fa-check"></i><b>5.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="5.1.3" data-path="SimpleMed.html"><a href="SimpleMed.html#readings-resources-4"><i class="fa fa-check"></i><b>5.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="5.1.4" data-path="SimpleMed.html"><a href="SimpleMed.html#packages-4"><i class="fa fa-check"></i><b>5.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="SimpleMed.html"><a href="SimpleMed.html#estimating-indirect-effects-the-analytic-approach-often-termed-mediation"><i class="fa fa-check"></i><b>5.2</b> Estimating Indirect Effects (the analytic approach often termed <em>mediation</em>)</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="SimpleMed.html"><a href="SimpleMed.html#the-definitional-and-conceptual"><i class="fa fa-check"></i><b>5.2.1</b> The definitional and conceptual</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="SimpleMed.html"><a href="SimpleMed.html#workflow-for-simple-mediation"><i class="fa fa-check"></i><b>5.3</b> Workflow for Simple Mediation</a></li>
<li class="chapter" data-level="5.4" data-path="SimpleMed.html"><a href="SimpleMed.html#super-simple-mediation-in-lavaan-a-focus-on-the-mechanics"><i class="fa fa-check"></i><b>5.4</b> Super Simple Mediation in <em>lavaan</em>: A focus on the mechanics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="SimpleMed.html"><a href="SimpleMed.html#simulate-fake-data"><i class="fa fa-check"></i><b>5.4.1</b> Simulate Fake Data</a></li>
<li class="chapter" data-level="5.4.2" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-mediation-model"><i class="fa fa-check"></i><b>5.4.2</b> Specify Mediation Model</a></li>
<li class="chapter" data-level="5.4.3" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output"><i class="fa fa-check"></i><b>5.4.3</b> Interpret the Output</a></li>
<li class="chapter" data-level="5.4.4" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-table"><i class="fa fa-check"></i><b>5.4.4</b> A Figure and Table</a></li>
<li class="chapter" data-level="5.4.5" data-path="SimpleMed.html"><a href="SimpleMed.html#results-4"><i class="fa fa-check"></i><b>5.4.5</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="SimpleMed.html"><a href="SimpleMed.html#research-vignette-4"><i class="fa fa-check"></i><b>5.5</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="SimpleMed.html"><a href="SimpleMed.html#data-simulation"><i class="fa fa-check"></i><b>5.5.1</b> Data Simulation</a></li>
<li class="chapter" data-level="5.5.2" data-path="SimpleMed.html"><a href="SimpleMed.html#scrubbing-scoring-and-data-diagnostics"><i class="fa fa-check"></i><b>5.5.2</b> Scrubbing, Scoring, and Data Diagnostics</a></li>
<li class="chapter" data-level="5.5.3" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-the-model-in-lavaan"><i class="fa fa-check"></i><b>5.5.3</b> Specify the Model in <em>lavaan</em></a></li>
<li class="chapter" data-level="5.5.4" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output-1"><i class="fa fa-check"></i><b>5.5.4</b> Interpret the Output</a></li>
<li class="chapter" data-level="5.5.5" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table"><i class="fa fa-check"></i><b>5.5.5</b> A Figure and a Table</a></li>
<li class="chapter" data-level="5.5.6" data-path="SimpleMed.html"><a href="SimpleMed.html#results-5"><i class="fa fa-check"></i><b>5.5.6</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="SimpleMed.html"><a href="SimpleMed.html#considering-covariates"><i class="fa fa-check"></i><b>5.6</b> Considering Covariates</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table-1"><i class="fa fa-check"></i><b>5.6.1</b> A Figure and a Table</a></li>
<li class="chapter" data-level="5.6.2" data-path="SimpleMed.html"><a href="SimpleMed.html#apa-style-write-up"><i class="fa fa-check"></i><b>5.6.2</b> APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="SimpleMed.html"><a href="SimpleMed.html#stay-tuned"><i class="fa fa-check"></i><b>5.7</b> STAY TUNED</a></li>
<li class="chapter" data-level="5.8" data-path="SimpleMed.html"><a href="SimpleMed.html#residual-and-related-questions"><i class="fa fa-check"></i><b>5.8</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="5.9" data-path="SimpleMed.html"><a href="SimpleMed.html#practice-problems-4"><i class="fa fa-check"></i><b>5.9</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed"><i class="fa fa-check"></i><b>5.9.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="5.9.2" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables"><i class="fa fa-check"></i><b>5.9.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="5.9.3" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-3-use-other-data-that-is-available-to-you"><i class="fa fa-check"></i><b>5.9.3</b> Problem #3: Use other data that is available to you</a></li>
<li class="chapter" data-level="5.9.4" data-path="SimpleMed.html"><a href="SimpleMed.html#grading-rubric-4"><i class="fa fa-check"></i><b>5.9.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="SimpleMed.html"><a href="SimpleMed.html#homeworked-example-2"><i class="fa fa-check"></i><b>5.10</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="SimpleMed.html"><a href="SimpleMed.html#assign-each-variable-to-the-x-y-or-m-roles-ok-but-not-required-to-include-a-covariate"><i class="fa fa-check"></i><b>5.10.1</b> Assign each variable to the X, Y, or M roles (ok but not required to include a covariate)</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-a-research-model-2"><i class="fa fa-check"></i>Specify a research model</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#import-the-data-and-format-the-variables-in-the-model"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-and-run-the-lavaan-model"><i class="fa fa-check"></i>Specify and run the lavaan model</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#use-tidysem-to-create-a-figure-that-represents-your-results"><i class="fa fa-check"></i>Use tidySEM to create a figure that represents your results</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#create-a-table-that-includes-regression-output-for-the-m-and-y-variables"><i class="fa fa-check"></i>Create a table that includes regression output for the M and Y variables</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#represent-your-work-in-an-apa-style-write-up"><i class="fa fa-check"></i>Represent your work in an APA-style write-up</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#explanation-to-grader"><i class="fa fa-check"></i>Explanation to grader</a></li>
<li class="chapter" data-level="" data-path="SimpleMed.html"><a href="SimpleMed.html#be-able-to-hand-calculate-the-indirect-direct-and-total-effects-from-the-a-b-c-paths"><i class="fa fa-check"></i>Be able to hand-calculate the indirect, direct, and total effects from the a, b, &amp; c’ paths</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="CompMed.html"><a href="CompMed.html"><i class="fa fa-check"></i><b>6</b> Complex Mediation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="CompMed.html"><a href="CompMed.html#navigating-this-lesson-5"><i class="fa fa-check"></i><b>6.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="CompMed.html"><a href="CompMed.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.1.2" data-path="CompMed.html"><a href="CompMed.html#planning-for-practice-5"><i class="fa fa-check"></i><b>6.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="6.1.3" data-path="CompMed.html"><a href="CompMed.html#readings-resources-5"><i class="fa fa-check"></i><b>6.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="6.1.4" data-path="CompMed.html"><a href="CompMed.html#packages-5"><i class="fa fa-check"></i><b>6.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="CompMed.html"><a href="CompMed.html#complex-mediation"><i class="fa fa-check"></i><b>6.2</b> Complex Mediation</a></li>
<li class="chapter" data-level="6.3" data-path="CompMed.html"><a href="CompMed.html#workflow-for-complex-mediation"><i class="fa fa-check"></i><b>6.3</b> Workflow for Complex Mediation</a></li>
<li class="chapter" data-level="6.4" data-path="CompMed.html"><a href="CompMed.html#parallel-mediation"><i class="fa fa-check"></i><b>6.4</b> Parallel Mediation</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="CompMed.html"><a href="CompMed.html#a-mechanical-example"><i class="fa fa-check"></i><b>6.4.1</b> A Mechanical Example</a></li>
<li class="chapter" data-level="6.4.2" data-path="CompMed.html"><a href="CompMed.html#research-vignette-5"><i class="fa fa-check"></i><b>6.4.2</b> Research Vignette</a></li>
<li class="chapter" data-level="6.4.3" data-path="CompMed.html"><a href="CompMed.html#scrubbing-scoring-and-data-diagnostics-1"><i class="fa fa-check"></i><b>6.4.3</b> Scrubbing, Scoring, and Data Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="CompMed.html"><a href="CompMed.html#serial-multiple-mediator-model"><i class="fa fa-check"></i><b>6.5</b> Serial Multiple Mediator Model</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="CompMed.html"><a href="CompMed.html#we-stick-with-the-lewis-et-al.--lewis_applying_2017-example-but-modify-it."><i class="fa fa-check"></i><b>6.5.1</b> We stick with the Lewis et al. <span class="citation">(2017)</span> example, but modify it.</a></li>
<li class="chapter" data-level="6.5.2" data-path="CompMed.html"><a href="CompMed.html#specify-the-lavaan-model"><i class="fa fa-check"></i><b>6.5.2</b> Specify the <em>lavaan</em> model</a></li>
<li class="chapter" data-level="6.5.3" data-path="CompMed.html"><a href="CompMed.html#apa-style-writeup-2"><i class="fa fa-check"></i><b>6.5.3</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="CompMed.html"><a href="CompMed.html#stay-tuned-1"><i class="fa fa-check"></i><b>6.6</b> STAY TUNED</a></li>
<li class="chapter" data-level="6.7" data-path="CompMed.html"><a href="CompMed.html#troubleshooting-and-faqs"><i class="fa fa-check"></i><b>6.7</b> Troubleshooting and FAQs</a></li>
<li class="chapter" data-level="6.8" data-path="CompMed.html"><a href="CompMed.html#practice-problems-5"><i class="fa fa-check"></i><b>6.8</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="CompMed.html"><a href="CompMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-1"><i class="fa fa-check"></i><b>6.8.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="6.8.2" data-path="CompMed.html"><a href="CompMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-1"><i class="fa fa-check"></i><b>6.8.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="6.8.3" data-path="CompMed.html"><a href="CompMed.html#problem-3-use-other-data-that-is-available-to-you-1"><i class="fa fa-check"></i><b>6.8.3</b> Problem #3: Use other data that is available to you</a></li>
<li class="chapter" data-level="6.8.4" data-path="CompMed.html"><a href="CompMed.html#grading-rubric-5"><i class="fa fa-check"></i><b>6.8.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="CompMed.html"><a href="CompMed.html#homeworked-example-3"><i class="fa fa-check"></i><b>6.9</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#assign-each-variable-to-the-x-y-m1-and-m2-roles"><i class="fa fa-check"></i>Assign each variable to the X, Y, M1, and M2 roles</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#import-the-data-and-format-the-variables-in-the-model-1"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#specify-and-run-the-lavaan-model-1"><i class="fa fa-check"></i>Specify and run the lavaan model</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#use-tidysem-to-create-a-figure-that-represents-your-results-1"><i class="fa fa-check"></i>Use tidySEM to create a figure that represents your results</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#create-a-table-that-includes-a-summary-of-the-effects-indirect-direct-total-total-indirect-as-well-as-contrasts"><i class="fa fa-check"></i>Create a table that includes a summary of the effects (indirect, direct, total, total indirect) as well as contrasts</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#represent-your-work-in-an-apa-style-write-up-1"><i class="fa fa-check"></i>Represent your work in an APA-style write-up</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#explanation-to-grader-1"><i class="fa fa-check"></i>Explanation to grader</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#be-able-to-hand-calculate-the-indirect-direct-and-total-effects-from-the-a-b-c-paths-1"><i class="fa fa-check"></i>Be able to hand-calculate the indirect, direct, and total effects from the a, b, &amp; c’ paths</a></li>
<li class="chapter" data-level="" data-path="CompMed.html"><a href="CompMed.html#a-homework-idea"><i class="fa fa-check"></i>A homework idea</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MOD.html"><a href="MOD.html"><i class="fa fa-check"></i>MODERATION</a></li>
<li class="chapter" data-level="7" data-path="SimpMod.html"><a href="SimpMod.html"><i class="fa fa-check"></i><b>7</b> Simple Moderation in OLS and MLE</a>
<ul>
<li class="chapter" data-level="7.1" data-path="SimpMod.html"><a href="SimpMod.html#navigating-this-lesson-6"><i class="fa fa-check"></i><b>7.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="SimpMod.html"><a href="SimpMod.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="7.1.2" data-path="SimpMod.html"><a href="SimpMod.html#planning-for-practice-6"><i class="fa fa-check"></i><b>7.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="7.1.3" data-path="SimpMod.html"><a href="SimpMod.html#readings-resources-6"><i class="fa fa-check"></i><b>7.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="7.1.4" data-path="SimpMod.html"><a href="SimpMod.html#packages-6"><i class="fa fa-check"></i><b>7.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="SimpMod.html"><a href="SimpMod.html#on-modeling-introductory-comments-on-the-simultaneously-invisible-and-paradigm-shifting-transition-we-are-making"><i class="fa fa-check"></i><b>7.2</b> On <em>Modeling</em>: Introductory Comments on the simultaneously invisible and paradigm-shifting transition we are making</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="SimpMod.html"><a href="SimpMod.html#nhst-versus-modeling"><i class="fa fa-check"></i><b>7.2.1</b> NHST versus modeling</a></li>
<li class="chapter" data-level="7.2.2" data-path="SimpMod.html"><a href="SimpMod.html#introducing-the-model"><i class="fa fa-check"></i><b>7.2.2</b> Introducing: <em>The Model</em></a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="SimpMod.html"><a href="SimpMod.html#ols-to-ml-for-estimation"><i class="fa fa-check"></i><b>7.3</b> OLS to ML for Estimation</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="SimpMod.html"><a href="SimpMod.html#ordinary-least-squares-ols"><i class="fa fa-check"></i><b>7.3.1</b> Ordinary least squares (OLS)</a></li>
<li class="chapter" data-level="7.3.2" data-path="SimpMod.html"><a href="SimpMod.html#maximum-likelihood-estimation-mle-a-brief-orientation"><i class="fa fa-check"></i><b>7.3.2</b> Maximum likelihood estimation (MLE): A brief orientation</a></li>
<li class="chapter" data-level="7.3.3" data-path="SimpMod.html"><a href="SimpMod.html#ols-and-mle-comparison"><i class="fa fa-check"></i><b>7.3.3</b> OLS and MLE Comparison</a></li>
<li class="chapter" data-level="7.3.4" data-path="SimpMod.html"><a href="SimpMod.html#hayes-and-process-aka-conditional-process-analysis"><i class="fa fa-check"></i><b>7.3.4</b> Hayes and PROCESS (aka conditional process analysis)</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="SimpMod.html"><a href="SimpMod.html#introducing-the-lavaan-package"><i class="fa fa-check"></i><b>7.4</b> Introducing the <em>lavaan</em> package</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="SimpMod.html"><a href="SimpMod.html#the-fiml-magic-for-which-we-have-been-waiting"><i class="fa fa-check"></i><b>7.4.1</b> The FIML magic for which we have been waiting</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="SimpMod.html"><a href="SimpMod.html#picking-up-with-moderation"><i class="fa fa-check"></i><b>7.5</b> Picking up with Moderation</a></li>
<li class="chapter" data-level="7.6" data-path="SimpMod.html"><a href="SimpMod.html#workflow-for-a-simple-moderation"><i class="fa fa-check"></i><b>7.6</b> Workflow for a Simple Moderation</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="SimpMod.html"><a href="SimpMod.html#research-vignette-6"><i class="fa fa-check"></i><b>7.6.1</b> Research Vignette</a></li>
<li class="chapter" data-level="7.6.2" data-path="SimpMod.html"><a href="SimpMod.html#scrubbing-scoring-and-data-diagnostics-2"><i class="fa fa-check"></i><b>7.6.2</b> Scrubbing, Scoring, and Data Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="SimpMod.html"><a href="SimpMod.html#working-the-simple-moderation-with-ols-and-mle"><i class="fa fa-check"></i><b>7.7</b> Working the Simple Moderation with OLS and MLE</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="SimpMod.html"><a href="SimpMod.html#ols-with-lm"><i class="fa fa-check"></i><b>7.7.1</b> OLS with <em>lm()</em></a></li>
<li class="chapter" data-level="7.7.2" data-path="SimpMod.html"><a href="SimpMod.html#mle-with-lavaansem"><i class="fa fa-check"></i><b>7.7.2</b> MLE with <em>lavaan::sem()</em></a></li>
<li class="chapter" data-level="7.7.3" data-path="SimpMod.html"><a href="SimpMod.html#tabling-the-data"><i class="fa fa-check"></i><b>7.7.3</b> Tabling the data</a></li>
<li class="chapter" data-level="7.7.4" data-path="SimpMod.html"><a href="SimpMod.html#apa-style-writeup-3"><i class="fa fa-check"></i><b>7.7.4</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="SimpMod.html"><a href="SimpMod.html#stay-tuned-2"><i class="fa fa-check"></i><b>7.8</b> STAY TUNED</a></li>
<li class="chapter" data-level="7.9" data-path="SimpMod.html"><a href="SimpMod.html#residual-and-related-questions-1"><i class="fa fa-check"></i><b>7.9</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="7.10" data-path="SimpMod.html"><a href="SimpMod.html#practice-problems-6"><i class="fa fa-check"></i><b>7.10</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="7.10.1" data-path="SimpMod.html"><a href="SimpMod.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-2"><i class="fa fa-check"></i><b>7.10.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="7.10.2" data-path="SimpMod.html"><a href="SimpMod.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-2"><i class="fa fa-check"></i><b>7.10.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="7.10.3" data-path="SimpMod.html"><a href="SimpMod.html#problem-3-use-other-data-that-is-available-to-you-2"><i class="fa fa-check"></i><b>7.10.3</b> Problem #3: Use other data that is available to you</a></li>
<li class="chapter" data-level="7.10.4" data-path="SimpMod.html"><a href="SimpMod.html#grading-rubric-6"><i class="fa fa-check"></i><b>7.10.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="SimpMod.html"><a href="SimpMod.html#bonus-track-1"><i class="fa fa-check"></i><b>7.11</b> Bonus Track:</a></li>
<li class="chapter" data-level="7.12" data-path="SimpMod.html"><a href="SimpMod.html#homeworked-example-4"><i class="fa fa-check"></i><b>7.12</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#assign-each-variable-to-the-x-y-and-w-roles"><i class="fa fa-check"></i>Assign each variable to the X, Y, and W roles</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#import-the-data-and-format-the-variables-in-the-model-2"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#specify-and-run-the-olslm-model"><i class="fa fa-check"></i>Specify and run the OLS/<em>lm()</em> model</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#probe-the-interaction-with-the-simple-slopes-and-johnson-neyman-approaches"><i class="fa fa-check"></i>Probe the interaction with the simple slopes and Johnson-Neyman approaches</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#create-an-interaction-figure"><i class="fa fa-check"></i>Create an interaction figure</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#create-a-table-a-package-produced-table-is-fine"><i class="fa fa-check"></i>Create a table (a package-produced table is fine)</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#create-an-apa-style-write-up-of-the-results"><i class="fa fa-check"></i>Create an APA style write-up of the results</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#repeat-the-analysis-in-lavaan-specify-the-model-to-include-probing-the-interaction"><i class="fa fa-check"></i>Repeat the analysis in <em>lavaan</em> (specify the model to include probing the interaction)</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#create-a-model-figure"><i class="fa fa-check"></i>Create a model figure</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#create-a-table"><i class="fa fa-check"></i>Create a table</a></li>
<li class="chapter" data-level="7.12.1" data-path="SimpMod.html"><a href="SimpMod.html#note-similarities-and-differences-in-the-ols-results"><i class="fa fa-check"></i><b>7.12.1</b> Note similarities and differences in the OLS results</a></li>
<li class="chapter" data-level="" data-path="SimpMod.html"><a href="SimpMod.html#represent-your-work-in-an-apa-style-write-up-2"><i class="fa fa-check"></i>Represent your work in an APA-style write-up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="CPAnal.html"><a href="CPAnal.html"><i class="fa fa-check"></i>CONDITIONAL PROCESS ANALYSIS</a></li>
<li class="chapter" data-level="8" data-path="ModMed.html"><a href="ModMed.html"><i class="fa fa-check"></i><b>8</b> Moderated Mediation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ModMed.html"><a href="ModMed.html#navigating-this-lesson-7"><i class="fa fa-check"></i><b>8.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ModMed.html"><a href="ModMed.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="8.1.2" data-path="ModMed.html"><a href="ModMed.html#planning-for-practice-7"><i class="fa fa-check"></i><b>8.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="8.1.3" data-path="ModMed.html"><a href="ModMed.html#readings-resources-7"><i class="fa fa-check"></i><b>8.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="8.1.4" data-path="ModMed.html"><a href="ModMed.html#packages-7"><i class="fa fa-check"></i><b>8.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="ModMed.html"><a href="ModMed.html#conditional-process-analysis"><i class="fa fa-check"></i><b>8.2</b> Conditional Process Analysis</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ModMed.html"><a href="ModMed.html#the-definitional-and-conceptual-1"><i class="fa fa-check"></i><b>8.2.1</b> The definitional and conceptual</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ModMed.html"><a href="ModMed.html#workflow-for-moderated-mediation"><i class="fa fa-check"></i><b>8.3</b> Workflow for Moderated Mediation</a></li>
<li class="chapter" data-level="8.4" data-path="ModMed.html"><a href="ModMed.html#research-vignette-7"><i class="fa fa-check"></i><b>8.4</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="ModMed.html"><a href="ModMed.html#simulating-the-data-from-the-journal-article"><i class="fa fa-check"></i><b>8.4.1</b> Simulating the data from the journal article</a></li>
<li class="chapter" data-level="8.4.2" data-path="ModMed.html"><a href="ModMed.html#scrubbing-scoring-and-data-diagnostics-3"><i class="fa fa-check"></i><b>8.4.2</b> Scrubbing, Scoring, and Data Diagnostics</a></li>
<li class="chapter" data-level="8.4.3" data-path="ModMed.html"><a href="ModMed.html#quick-peek-at-the-data"><i class="fa fa-check"></i><b>8.4.3</b> Quick peek at the data</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="ModMed.html"><a href="ModMed.html#working-the-moderated-mediation"><i class="fa fa-check"></i><b>8.5</b> Working the Moderated Mediation</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="ModMed.html"><a href="ModMed.html#piecewise-assembly-of-the-moderated-mediation"><i class="fa fa-check"></i><b>8.5.1</b> Piecewise Assembly of the Moderated Mediation</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="ModMed.html"><a href="ModMed.html#the-moderated-mediation-a-combined-analysis"><i class="fa fa-check"></i><b>8.6</b> The Moderated Mediation: A Combined analysis</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ModMed.html"><a href="ModMed.html#specification-in-lavaan"><i class="fa fa-check"></i><b>8.6.1</b> Specification in <em>lavaan</em></a></li>
<li class="chapter" data-level="8.6.2" data-path="ModMed.html"><a href="ModMed.html#beginning-the-interpretation"><i class="fa fa-check"></i><b>8.6.2</b> Beginning the interpretation</a></li>
<li class="chapter" data-level="8.6.3" data-path="ModMed.html"><a href="ModMed.html#tabling-the-data-1"><i class="fa fa-check"></i><b>8.6.3</b> Tabling the data</a></li>
<li class="chapter" data-level="8.6.4" data-path="ModMed.html"><a href="ModMed.html#model-trimming"><i class="fa fa-check"></i><b>8.6.4</b> Model trimming</a></li>
<li class="chapter" data-level="8.6.5" data-path="ModMed.html"><a href="ModMed.html#apa-style-write-up-1"><i class="fa fa-check"></i><b>8.6.5</b> APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="ModMed.html"><a href="ModMed.html#stay-tuned-3"><i class="fa fa-check"></i><b>8.7</b> STAY TUNED</a></li>
<li class="chapter" data-level="8.8" data-path="ModMed.html"><a href="ModMed.html#residual-and-related-questions-2"><i class="fa fa-check"></i><b>8.8</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="8.9" data-path="ModMed.html"><a href="ModMed.html#practice-problems-7"><i class="fa fa-check"></i><b>8.9</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="ModMed.html"><a href="ModMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-3"><i class="fa fa-check"></i><b>8.9.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="8.9.2" data-path="ModMed.html"><a href="ModMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-3"><i class="fa fa-check"></i><b>8.9.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="8.9.3" data-path="ModMed.html"><a href="ModMed.html#problem-3-use-other-data-that-is-available-to-you-3"><i class="fa fa-check"></i><b>8.9.3</b> Problem #3: Use other data that is available to you</a></li>
<li class="chapter" data-level="8.9.4" data-path="ModMed.html"><a href="ModMed.html#grading-rubric-7"><i class="fa fa-check"></i><b>8.9.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="ModMed.html"><a href="ModMed.html#homeworked-example-1-a-moderation-on-the-a-path"><i class="fa fa-check"></i><b>8.10</b> Homeworked Example 1: A moderation on the <em>a</em> path</a>
<ul>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#describing-thy-overall-model-hypothesis-assign-each-variable-to-the-x-y-m-and-w-roles"><i class="fa fa-check"></i>Describing thy overall model hypothesis, assign each variable to the X, Y, M, and W roles</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#import-the-data-and-format-the-variables-in-the-model-3"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#using-a-piecewise-approach-run-each-of-the-simple-models-in-the-grander-design"><i class="fa fa-check"></i>Using a piecewise approach, run each of the simple models in the grander design</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#use-tidysem-to-create-a-figure"><i class="fa fa-check"></i>Use tidySEM to create a figure</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#create-a-table-that-includes-regression-output-for-the-m-and-y-variables-and-the-moderated-effects"><i class="fa fa-check"></i>Create a table that includes regression output for the M and Y variables and the moderated effects</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#apa-style-write-up-2"><i class="fa fa-check"></i>APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="ModMed.html"><a href="ModMed.html#homeworked-example-2-a-moderation-on-the-b-path"><i class="fa fa-check"></i><b>8.11</b> Homeworked Example 2: A moderation on the <em>b</em> path</a>
<ul>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#describing-they-overall-model-hypothesis-assign-each-variable-to-the-x-y-m-and-w-roles"><i class="fa fa-check"></i>Describing they overall model hypothesis, assign each variable to the X, Y, M, and W roles</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#import-the-data-and-format-the-variables-in-the-model-4"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#using-a-piecewise-approach-run-each-of-the-simple-models-in-the-grander-design-1"><i class="fa fa-check"></i>Using a piecewise approach, run each of the simple models in the grander design</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#use-tidysem-to-create-a-figure-1"><i class="fa fa-check"></i>Use tidySEM to create a figure</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#create-a-table-that-includes-regression-output-for-the-m-and-y-variables-and-the-moderated-effects-1"><i class="fa fa-check"></i>Create a table that includes regression output for the M and Y variables and the moderated effects</a></li>
<li class="chapter" data-level="" data-path="ModMed.html"><a href="ModMed.html#apa-style-write-up-3"><i class="fa fa-check"></i>APA Style Write-up</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="refs.html"><a href="refs.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="" data-path="SEM.html"><a href="SEM.html"><i class="fa fa-check"></i>STRUCTURAL EQUATION MODELING</a></li>
<li class="chapter" data-level="9" data-path="MeasMod.html"><a href="MeasMod.html"><i class="fa fa-check"></i><b>9</b> Establishing the Measurement Model</a>
<ul>
<li class="chapter" data-level="9.1" data-path="MeasMod.html"><a href="MeasMod.html#navigating-this-lesson-8"><i class="fa fa-check"></i><b>9.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="MeasMod.html"><a href="MeasMod.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="9.1.2" data-path="MeasMod.html"><a href="MeasMod.html#planning-for-practice-8"><i class="fa fa-check"></i><b>9.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="9.1.3" data-path="MeasMod.html"><a href="MeasMod.html#readings-resources-8"><i class="fa fa-check"></i><b>9.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="9.1.4" data-path="MeasMod.html"><a href="MeasMod.html#packages-8"><i class="fa fa-check"></i><b>9.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="MeasMod.html"><a href="MeasMod.html#introduction-to-structural-equation-modeling-sem"><i class="fa fa-check"></i><b>9.2</b> Introduction to Structural Equation Modeling (SEM)</a></li>
<li class="chapter" data-level="9.3" data-path="MeasMod.html"><a href="MeasMod.html#workflow-for-evaluating-a-structural-model"><i class="fa fa-check"></i><b>9.3</b> Workflow for Evaluating a Structural Model</a></li>
<li class="chapter" data-level="9.4" data-path="MeasMod.html"><a href="MeasMod.html#the-measurement-model-specification-and-evaluation"><i class="fa fa-check"></i><b>9.4</b> The Measurement Model: Specification and Evaluation</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="MeasMod.html"><a href="MeasMod.html#degrees-of-freedom-and-model-identification"><i class="fa fa-check"></i><b>9.4.1</b> Degrees of Freedom and Model Identification</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="MeasMod.html"><a href="MeasMod.html#research-vignette-8"><i class="fa fa-check"></i><b>9.5</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="MeasMod.html"><a href="MeasMod.html#simulating-the-data-from-the-journal-article-1"><i class="fa fa-check"></i><b>9.5.1</b> Simulating the data from the journal article</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="MeasMod.html"><a href="MeasMod.html#scrubbing-scoring-and-data-diagnostics-4"><i class="fa fa-check"></i><b>9.6</b> Scrubbing, Scoring, and Data Diagnostics</a></li>
<li class="chapter" data-level="9.7" data-path="MeasMod.html"><a href="MeasMod.html#specifying-the-measurement-model-in-lavaan"><i class="fa fa-check"></i><b>9.7</b> Specifying the Measurement Model in <em>lavaan</em></a></li>
<li class="chapter" data-level="9.8" data-path="MeasMod.html"><a href="MeasMod.html#interpreting-the-output"><i class="fa fa-check"></i><b>9.8</b> Interpreting the Output</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="MeasMod.html"><a href="MeasMod.html#global-fit-indices"><i class="fa fa-check"></i><b>9.8.1</b> Global Fit Indices</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="MeasMod.html"><a href="MeasMod.html#parceling"><i class="fa fa-check"></i><b>9.9</b> Parceling</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="MeasMod.html"><a href="MeasMod.html#the-pros-and-cons-of-parceling"><i class="fa fa-check"></i><b>9.9.1</b> The Pros and Cons of Parceling</a></li>
<li class="chapter" data-level="9.9.2" data-path="MeasMod.html"><a href="MeasMod.html#practical-procedures-for-parceling"><i class="fa fa-check"></i><b>9.9.2</b> Practical Procedures for Parceling</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="MeasMod.html"><a href="MeasMod.html#parceling-with-subscale-scores"><i class="fa fa-check"></i><b>9.10</b> Parceling with Subscale Scores</a>
<ul>
<li class="chapter" data-level="9.10.1" data-path="MeasMod.html"><a href="MeasMod.html#measurement-model-with-subscale-parcels"><i class="fa fa-check"></i><b>9.10.1</b> Measurement Model with Subscale Parcels</a></li>
<li class="chapter" data-level="9.10.2" data-path="MeasMod.html"><a href="MeasMod.html#measurement-model-with-just-identified-random-parcels"><i class="fa fa-check"></i><b>9.10.2</b> Measurement Model with Just-Identified Random Parcels</a></li>
<li class="chapter" data-level="9.10.3" data-path="MeasMod.html"><a href="MeasMod.html#apa-style-write-up-of-the-results"><i class="fa fa-check"></i><b>9.10.3</b> APA Style Write-up of the Results</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="MeasMod.html"><a href="MeasMod.html#residual-and-related-questions-3"><i class="fa fa-check"></i><b>9.11</b> Residual and Related Questions…</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="MeasMod.html"><a href="MeasMod.html#wait-why-did-we-do-this"><i class="fa fa-check"></i><b>9.11.1</b> Wait! Why did we do this?</a></li>
<li class="chapter" data-level="9.11.2" data-path="MeasMod.html"><a href="MeasMod.html#what-if-one-of-my-variables-only-has-one-or-two-indicators"><i class="fa fa-check"></i><b>9.11.2</b> What if one of my variables only has one or two indicators?</a></li>
<li class="chapter" data-level="9.11.3" data-path="MeasMod.html"><a href="MeasMod.html#what-if-i-have-missing-data"><i class="fa fa-check"></i><b>9.11.3</b> What if I have missing data?</a></li>
</ul></li>
<li class="chapter" data-level="9.12" data-path="MeasMod.html"><a href="MeasMod.html#practice-problems-8"><i class="fa fa-check"></i><b>9.12</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="9.12.1" data-path="MeasMod.html"><a href="MeasMod.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-4"><i class="fa fa-check"></i><b>9.12.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="9.12.2" data-path="MeasMod.html"><a href="MeasMod.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-4"><i class="fa fa-check"></i><b>9.12.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="9.12.3" data-path="MeasMod.html"><a href="MeasMod.html#problem-3-try-something-entirely-new."><i class="fa fa-check"></i><b>9.12.3</b> Problem #3: Try something entirely new.</a></li>
<li class="chapter" data-level="9.12.4" data-path="MeasMod.html"><a href="MeasMod.html#grading-rubric-8"><i class="fa fa-check"></i><b>9.12.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="MeasMod.html"><a href="MeasMod.html#homeworked-example-5"><i class="fa fa-check"></i><b>9.13</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#identify-the-structural-model-you-will-evaluate"><i class="fa fa-check"></i>Identify the structural model you will evaluate</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#specify-a-research-model-3"><i class="fa fa-check"></i>Specify a research model</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#import-the-data-and-format-the-variables-in-the-model-5"><i class="fa fa-check"></i>Import the data and format the variables in the model</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#specify-and-evaluate-a-measurement-model-with-all-items-as-indicators"><i class="fa fa-check"></i>Specify and evaluate a measurement model with all items as indicators</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#interpret-the-results"><i class="fa fa-check"></i>Interpret the results</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#specify-and-evaluate-a-measurement-model-with-either-the-subscale-or-randomly-assigned-to-3-parcels-approaches"><i class="fa fa-check"></i>Specify and evaluate a measurement model with either the subscale or randomly assigned to 3 parcels approaches</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#interpret-the-results-1"><i class="fa fa-check"></i>Interpret the results</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#make-notes-about-similarities-and-differences-in-the-all-items-and-parceled-approaches"><i class="fa fa-check"></i>Make notes about similarities and differences in the all-items and parceled approaches</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#apa-style-results-with-table-and-figure"><i class="fa fa-check"></i>APA style results with table and figure</a></li>
<li class="chapter" data-level="" data-path="MeasMod.html"><a href="MeasMod.html#explanation-to-grader-2"><i class="fa fa-check"></i>Explanation to grader</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ReCentering Psych Stats: Multivariate Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="score" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Scoring<a href="score.html#score" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><a href="https://youtube.com/playlist?list=PLtz5cFLQl4KNJXbHg2vDU-sbCH-QwXMlr&amp;si=7i1LFdRqxEJMLVZ6">Screencasted Lecture Link</a></p>
<p>The focus of this chapter is to continue the process of scrubbing-and-scoring. We continue with the raw data we downloaded and prepared in the prior chapter. In this chapter we analyze and manage missingness, score scales/subscales, and represent our work with an APA-style write-up. To that end, we will address the conceptual considerations and practical steps in this process.</p>
<div id="navigating-this-lesson-1" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Navigating this Lesson<a href="score.html#navigating-this-lesson-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There is about 1 hour and 20 minutes of lecture. If you work through the materials with me it would be good to add another hour.</p>
<p>While the majority of R objects and data you will need are created within the R script that sources the chapter, there are a few that cannot be created from within the R framework. Additionally, sometimes links fail. All original materials are provided at the <a href="https://github.com/lhbikos/ReC_MultivModel">Github site</a> that hosts the book. More detailed guidelines for ways to access all these materials are provided in the OER’s <a href="#ReCintro">introduction</a></p>
<div id="learning-objectives-1" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Learning Objectives<a href="score.html#learning-objectives-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Learning objectives from this lecture include the following:</p>
<ul>
<li>Recognize the key components of data loss mechanisms (MCAR, MAR, MNAR), including how to diagnose MCAR.</li>
<li>Interpret missingness figures produced by packages such as <em>mice</em>.</li>
<li>Articulate a workflow for scrubbing and scoring data.</li>
<li>Use critical data manipulation functions from <em>dplyr</em> including <em>filter()</em>, <em>select()</em>, and <em>mutate()</em> to prepare variables.</li>
<li>Interpret code related to missingness (i.e., “is.na”, “!is.na”) and the pipe (%&gt;%)</li>
</ul>
</div>
<div id="planning-for-practice-1" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Planning for Practice<a href="score.html#planning-for-practice-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The suggestions for practice continue from the prior chapter. The assignment in the prior chapter involved downloading a dataset from Qualtrics and the “scrubbing” it on the basis of inclusion and exclusion criteria. Using that same data, the practice suggestions in this chapter will continue to use Parent’s <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> AIA approach to managing missing data, to score the variables of interest. Options of graded complexity could incude:</p>
<ul>
<li>Repeating the steps in the chapter with the most recent data from the Rate-A-Recent-Course survey; differences will be in the number of people who have completed the survey since the chapter was written.</li>
<li>Use the dataset that is the source of the chapter, but score a different set of items that you choose.</li>
<li>Begin with raw data to which you have access.</li>
</ul>
</div>
<div id="readings-resources-1" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Readings &amp; Resources<a href="score.html#readings-resources-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In preparing this chapter, I drew heavily from the following resource(s). Other resources are cited (when possible, linked) in the text with complete citations in the reference list.</p>
<ul>
<li>Enders, C. K. (2010). Applied missing data analysis (2010-13190-000). Guilford Press.
<ul>
<li>Enders’ text continues to be the comprehensive “go-to” source for examining and managing missing data.</li>
</ul></li>
<li>Kline, R. B. (2015). Data preparation and psychometrics review. In Principles and Practice of Structural Equation Modeling, Fourth Edition. Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663" class="uri">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a>
<ul>
<li>Kline’s chapter is my “go-to” for making decisions about preparing data for analysis.</li>
</ul></li>
<li>Parent, M. C. (2013). Handling item-level missing data: Simpler is just as good. The Counseling Psychologist, 41(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176" class="uri">https://doi.org/10.1177/0011000012445176</a>
<ul>
<li>The purpose of Parent’s article was to argue that complex and resource-intensive procedurs like multiple imputation are unnecessary. Following a simulation that supports his claims, Parent provides some guidelines to follow for the AIA approach.</li>
</ul></li>
</ul>
</div>
<div id="packages-1" class="section level3 hasAnchor" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Packages<a href="score.html#packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The packages used in this lesson are embedded in this code. When the hashtags are removed, the script below will (a) check to see if the following packages are installed on your computer and, if not (b) install them.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="score.html#cb26-1" tabindex="-1"></a><span class="co"># if(!require(tidyverse)){install.packages(&#39;tidyverse&#39;)}</span></span>
<span id="cb26-2"><a href="score.html#cb26-2" tabindex="-1"></a><span class="co"># if(!require(psych)){install.packages(&#39;psych&#39;)}</span></span>
<span id="cb26-3"><a href="score.html#cb26-3" tabindex="-1"></a><span class="co"># if(!require(mice)){install.packages(&#39;mice&#39;)}</span></span>
<span id="cb26-4"><a href="score.html#cb26-4" tabindex="-1"></a><span class="co"># if(!require(sjstats)){install.packages(&#39;sjstats&#39;)}</span></span>
<span id="cb26-5"><a href="score.html#cb26-5" tabindex="-1"></a><span class="co"># if(!require(formattable)){install.packages(&#39;formattable&#39;)}</span></span></code></pre></div>
</div>
</div>
<div id="workflow-for-scoring" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Workflow for Scoring<a href="score.html#workflow-for-scoring" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The following is a proposed workflow for preparing data for analysis.</p>
<p>The same workflow guides us through the Scrubbing, Scoring, and Data Dx chapters. At this stage in the chapter we are still scrubbing as we work through the item-level and whole-level portions of the AIA (left side) of the chart.</p>
<div class="float">
<img src="images/Ch02/wrkflow_prelim.jpg" alt="An image of our stage in the workflow for scrubbing and scoring data." />
<div class="figcaption">An image of our stage in the workflow for scrubbing and scoring data.</div>
</div>
</div>
<div id="research-vignette-1" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Research Vignette<a href="score.html#research-vignette-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The research vignette comes from the survey titled, <a href="https://spupsych.az1.qualtrics.com/jfe/form/SV_b2cClqAlLGQ6nLU">Rate-a-Recent-Course: A ReCentering Psych Stats Exercise</a> and is explained in the prior chapter. In the prior chapter we conducted super-preliminary scrubbing of variables that will allow us to examine the respondent’s perceived campus climate for students who are Black, predicted by the the respondent’s own campus belonging, and also the <em>structural diversity</em> proportions of Black students in the classroom and the BIPOC instructional staff. At present, I see this as a parallel mediation. That is, the perceived campus climate for Black students will be predicted by the respondent’s sense of belonging, through the proportion of Black classmates and BIPOC (Black, Indigenous, and people of color)instructional staff.</p>
<p><em>I would like to assess the model by having the instructional staff variable to be the percent of Black instructional staff. At the time that this lecture is being prepared, there is insufficient representation of Black faculty to model this.</em></p>
<div class="float">
<img src="images/Ch03/BlStuMed.jpg" alt="An image of the statistical model for which we are preparing data." />
<div class="figcaption">An image of the statistical model for which we are preparing data.</div>
</div>
<p>First, though, let’s take a more conceptual look at issues regarding missing data. We’ll come back to details of the survey as we work with it.</p>
</div>
<div id="on-missing-data" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> On Missing Data<a href="score.html#on-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>On the topic of missing data, we follow the traditions in most textbooks. We start by considering <em>data loss mechanisms</em> and options for <em>managing missingness.</em></p>
<p>Although the workflow I recommend is fairly straightforward, the topic is not. Quantitative psychologist have produced volumes of research that supports and refutes all of these issues in detail. An in-deth review of this is found in Enders’ <span class="citation">(<a href="#ref-enders_applied_2010">2010</a>)</span> text.</p>
<div id="data-loss-mechanisms" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Data Loss Mechanisms<a href="score.html#data-loss-mechanisms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We generally classify missingess in data in three different ways <span class="citation">(<a href="#ref-kline_principles_2016">Kline, 2016b</a>; <a href="#ref-parent_handling_2013">Parent, 2013</a>)</span>:</p>
<p><strong>Missing completely at random (MCAR)</strong> is the ideal case (and often unrealistic in actual data). For variable <em>Y</em> this mean that</p>
<ul>
<li>Missingness is due to a factor(s) completely unrelated to the missing data. Stated another way:
<ul>
<li>Missing observations differ from the observed scores only by chance; that is, whether scores on Y are missing or not missing is unrelated to <em>Y</em> itself</li>
</ul></li>
<li>The presence versus absence of data on <em>Y</em> is unrelated to all other variables in the dataset. That is, the nonmissing data are just a random sample of scores that the researcher would have analyzed had the data been complete. We might think of it as <em>haphazard</em> missing.
<ul>
<li>A respondent is interrupted, looks up, looks down, and skips an item.</li>
<li>A computer glitch causes spotty missingness – unrelated to any particular variable.</li>
</ul></li>
</ul>
<p>MCAR is the ideal state because results from it should not be biased as a function of the missingness.</p>
<p><strong>Missing at random (MAR)</strong> missing data arise from a process that is both measured and predictable in a particular sample. <em>Admittedly the use of “random” in this term is odd, because, by definition, the missingness is not random.</em></p>
<p>Restated:</p>
<ol style="list-style-type: decimal">
<li>Missingness on Y is unrelated to Y itself, but</li>
<li>Missingness is on Y is correlated with other variables in the data set.</li>
</ol>
<p>Example: Men are less likely to respond to questions about mental health than women, but among men, the probability of responding is unrelated to their true mental health status.</p>
<p>Kline <span class="citation">(<a href="#ref-kline_principles_2016">2016b</a>)</span> indicated that information loss due to MAR is potentially recoverable through imputation where missing scores are replaced by predicted scores. The predicted scores are generated from other variables in the data set that predict missingness on Y. If the strength of that prediction is reasonably strong, then results on Y after imputation may be relatively unbiased. In this sense, the MAR pattern is described as <em>ignorable</em> with regard to potential bias. Two types of variables can be used to predict the missing data</p>
<ol style="list-style-type: decimal">
<li>variables that are in the prediction equation, and</li>
<li><em>auxiliary</em> variables (i.e., variables in the dataset that are not in the prediction equation).</li>
</ol>
<p>Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> noted that multiple imputation and expectation maximization have frequently been used to manage missingness in MAR circumstances.</p>
<p><strong>Missing not at random (MNAR)</strong> is when the presence versus absence of scores on <em>Y</em> depend on <em>Y</em> itself. This is <em>non-ignorable</em>.</p>
<p>For example, if a patient drops out of a medical RCT because there are unpleasant side effects from the treatment, this discomfort is not measured, but the data is missing due to a process that is unknown in a particular data set. Results based on <em>complete cases only</em> can be severely biased when the data loss pattern is MNAR. That is, a treatment may look more beneficial than it really is if data from patients who were unable to tolerate the treatment are lost.</p>
<p>Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> described MNAR a little differently – but emphasized that the systematic missingness would be related to a variable outside the datset. Parent provided the example of items written in a manner that may be inappropriate for some participants (e.g., asking women about a relationship with their boyfriend/husband, when the woman might be in same gender relationship). If there were not demographic items that could identify the bias, this would be MNAR. Parent strongly advises researchers to carefully proofread and pilot surveys to avoid MNAR circumstances.</p>
<p>Kline <span class="citation">(<a href="#ref-kline_principles_2016">2016b</a>)</span> noted that the choice of the method to deal with the incomplete records can make a difference in the results, and should be made carefully.</p>
</div>
<div id="diagnosing-missing-data-mechanisms" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Diagnosing Missing Data Mechanisms<a href="score.html#diagnosing-missing-data-mechanisms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The bad news is that we never really know (with certainty) the type of missing data mechanism in our data. The following tools can help understand the mechanisms that contribute to missingness.</p>
<ul>
<li>Missing data analyses often includes correlations that could predict missingness.</li>
<li>Little and Rubin <span class="citation">(<a href="#ref-little_statistical_2002">2002</a>)</span> proposed a multivariate statistical test of the MCAR assumption that simultaneously compares complete versus incomplete cases on <em>Y</em> across all other variables. If this comparison is significant, then the MCAR hypothesis is rejected.
<ul>
<li>To restate: we want a non-significant result; and we use the sometimes-backwards-sounding NHST (null hypothesis significance testing) language, “MCAR cannot be rejected.”</li>
</ul></li>
<li>MCAR can also be examined through a series of <em>t</em> tests of the cases that have missing scores on Y with cases that have complete records on other variables. Unfortunately, sample sizes contribute to problems with interpretation. With low samples, they are underpowered; in large samples they can flag trivial differences.</li>
</ul>
<p>If MCAR is rejected, we are never sure whether the data loss mechanism is MAR or MNAR. There is no magical statistical “fix.” Kline <span class="citation">(<a href="#ref-kline_principles_2016">2016b</a>)</span> wrote, “About the best that can be done is to understand the nature of the underlying data loss pattern and accordingly modify your interpretation of the results” (p. 85).</p>
</div>
<div id="managing-missing-data" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Managing Missing Data<a href="score.html#managing-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are a number of approaches to managing missing data. Here is a summary of the ones most commonly used.</p>
<ul>
<li><p><strong>Listwise deletion</strong> (aka, Complete Case Analysis) If there is a missing score on any variable, that case is excluded from <strong>all</strong>
analyses.</p></li>
<li><p><strong>Pairwise deletion</strong> Cases are excluded only if they have missing data on variables involved in a particular analysis. AIA is a variant of pair-wise deletion, but it preserves as much data as possible with person-mean imputation at the scale level.</p></li>
<li><p><strong>Mean/median substitution</strong> Mean/median substitution replaces missing values with the mean/median of that particular variable. While this preserves the mean of the dataset, it can cause bias by decreasing variance. For example, if you have a column that has substantial of missingness and you replace each value with the same, fixed, mean, the variability of that variable has just been reduced. A variation on this is a <strong>group-mean substitution</strong> where the missing score in a particular group (e.g., women) is replaced by the group mean.</p></li>
<li><p><strong>Full information maximum likelihood (FIML)</strong> A <em>model-based method</em> that takes the researcher’s model as the starting point. The procedure partitions the cases in a raw data file into subsets, each with the same pattern of missing observations, including none (complete cases). Statistical information (e.g., means, variances) is extracted from each subset so all case are retained in the analysis. Parameters for the researcher’s model are estimated after combining all available information over the subsets of cases.</p></li>
<li><p><strong>Multiple imputation</strong> A <em>data based method</em> that works with the whole raw data file (not just with the observed variables that comprise the researcher’s model). Multiple imputation assumes that data are MAR (remember, MCAR is the more prestigious one). This means that researchers assume that missing values can be replaced by predictions derived from the observable portion fo the dataset.</p>
<ul>
<li>Multiple datasets (often 5 to 20) are created where missing values are replaced via a randomized process (so the same missing value [item 4 for person A] will likely have different values for each dataset).</li>
<li>The desired anlayis(es) is conducted simultaneously/separately for each of the imputed sets (so if you imputed 5 sets and wanted a linear regression, you get 5 linear regressions).</li>
<li>A <em>pooled analysis</em> uses the point estimates and the standard errors to provide a single result that represents the analysis.</li>
</ul></li>
</ul>
</div>
<div id="available-information-analysis-aia" class="section level3 hasAnchor" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Available Information Analysis (AIA)<a href="score.html#available-information-analysis-aia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> has created a set of recommendations that help us create a streamlined workflow for managing missing data. After evaluating three approaches to managing missingness (AIA, mean substitution, and multiple imputation) Parent concluded that in datasets with (a) low levels of missingness, (b) a reasonable sample size, and (c) adequate internal reliability of measures, these approaches had similar results.</p>
<p>Further, in simulation studies where there was (a) low sample size (<em>n</em> = 50), (b) weak associations among items, and (c) a small number of missing items, AIA was equivalent to multiple imputation. Even in cases where the data conditions were the “best” (i.e., <em>N</em> = 200, moderate correlations, at least 10 items), even 10% missingness (overall) did not produce notable difference among the methods. That is, means, standard errors, and alphas were similar across the methods (AIA, mean substitution, multiple imputation).</p>
<p>AIA is an older method of handling missing data that, as its name suggests, uses the <em>available data</em> for analysis and excludes missing data points only for analyses in which the missing data point would be directly involved. This means</p>
<ul>
<li>In the case of research that uses multiple item scales, and analysis takes place at the scale level
<ul>
<li>AIA is used to generate <strong>mean</strong> scores for the scale using the available data without substituting or imputing values;</li>
<li>This method generally produces a fairly complete set of scale-level data where
<ul>
<li>pairwise deletion (the whole row/case/person is skipped) can be used where there will be multiple analyses using statistics (e.g., correlations, t-tests, ANOVA) were missingness is not permitted</li>
<li>FIML can be specified in path analysis and CFA/SEM (where item-level data is required), and</li>
<li>some statistics, such as principal components analysis and principal axis factoring (item-level analyses) permit missing data,</li>
</ul></li>
<li>Of course, the researcher could still impute data, but why…</li>
</ul></li>
</ul>
<p>Parent’s <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> recommendations:</p>
<ul>
<li>Scale scores should be first calculated as a <em>mean</em> (average) not a sum. Why?
<ul>
<li>Calculating a “sum” from available data will result in automatically lower scores in cases where there is missingness.</li>
<li>If a sum is required (i.e., because you want to interpret some clinical level of something), calculate the mean first, do the analyses, then transform the results back into the whole-scale equivalent (multiply the mean by the number of items) for any interpretation.</li>
<li>For R script, do not write the script ([item1 + item2 + item3]/3) because this will return an empty entry for participants missing data (same problem as if you were to use sum). There are several functions for properly computing a mean; I will demo the <em>mean_n()</em> function from <em>sjstats</em> package because it allows us to simultaneously specify the tolerance level (next item).</li>
</ul></li>
<li>Determine your <em>tolerance</em> for missingness (20% seems to be common, although you could also look for guidance in the test manual/article). Then
<ul>
<li>Run a “percent missingness” check on the level of analysis (i.e., total score, scale, or subscale) you are using. If you are using a total scale score, then check to see what percent is missing across all the items in the whole scale. In contrast, if you are looking at subscales, run the percent missing at that level.</li>
<li>Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> advised that the tolerance levels should be made mindfully. A four-item scale with one item missing, won’t meet the 80% threshold, so it may make sense to set a 75% threshold for this scale.</li>
</ul></li>
<li>“Clearly and concisely detail the level of missingness” in papers <span class="citation">(<a href="#ref-parent_handling_2013">Parent, 2013, p. 595</a>)</span>. This includes
<ul>
<li>tolerance level for missing data by scale or subscale (e.g., 80% or 75%)</li>
<li>the number of missing values out of all data points on that scale for all participants and the maximum by participant (e.g., “For Scale X, a total of # missing data points out of ### were observed with no participant missing more than a single point.”)</li>
<li>verify a manual inspection of missing data for obvious patterns (e.g., abnormally high missing rates for only one or two items). This can be accomplished by requesting frequency output for the items and checking the nonmissing data points for each scale, ensuring there are no abnormal spikes in missingness (looking for MNAR).</li>
</ul></li>
<li>Curiously, Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> does not recommend that we run all the diagnostic tests. However, because recent reviewers have required them of me, I will demonstrate a series of them.</li>
<li>Reducing missingness starts at the survey design – make sure that all people can answer all items (i.e,. relationship-related items may contain heterosexist assumptions…which would result in an MNAR circumstance)</li>
</ul>
<p>Very practically speaking, Parent’s <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> recommendations follow us through the entire data analysis process.</p>
</div>
</div>
<div id="working-the-problem-1" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Working the Problem<a href="score.html#working-the-problem-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="variable-planning-and-preparation" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Variable Planning and Preparation<a href="score.html#variable-planning-and-preparation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the <a href="scrub.html#scrub">Scrubbing lesson</a> we imported the data from Qualtrics and applied the broadest levels of inclusion (e.g., the course rated was offered from an institution in the U.S., the respondent consented to participation) and exclusion (e.g., the survey was not a preview). We then downsized the survey to include the variables we will use in our statistical model. We then saved the data in .csv and .rds file.</p>
<p>Presuming that you are working along with me in an .rmd file and have placed that file in the same folder as this .rmd file, the following code should read the data into your environment.</p>
<p>I use <em>different</em> names for the object/df in my R environment than I use for the filename that holds the data on my computer. Why? I don’t want to accidentally overwrite this precious “source” of data.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="score.html#cb27-1" tabindex="-1"></a><span class="co"># scrub_df &lt;- read.csv (&#39;BlackStntsModel230902.csv&#39;, head = TRUE, sep</span></span>
<span id="cb27-2"><a href="score.html#cb27-2" tabindex="-1"></a><span class="co"># = &#39;,&#39;)</span></span>
<span id="cb27-3"><a href="score.html#cb27-3" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;BlackStntsModel230902.rds&quot;</span>)</span>
<span id="cb27-4"><a href="score.html#cb27-4" tabindex="-1"></a><span class="fu">str</span>(scrub_df)</span></code></pre></div>
<pre><code>## Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:    69 obs. of  25 variables:
##  $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ iRace1   : num  3 3 3 3 1 3 3 3 1 0 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;1 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;1_iRace&quot;
##  $ iRace2   : num  1 NA 1 1 NA NA 3 NA NA 0 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;2 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;2_iRace&quot;
##  $ iRace3   : num  3 NA NA 3 NA NA NA NA NA 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;3 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;3_iRace&quot;
##  $ iRace4   : num  NA NA NA NA NA NA NA NA NA 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;4 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;4_iRace&quot;
##  $ iRace5   : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;5 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;5_iRace&quot;
##  $ iRace6   : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;6 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;6_iRace&quot;
##  $ iRace7   : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;7 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;7_iRace&quot;
##  $ iRace8   : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;8 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;8_iRace&quot;
##  $ iRace9   : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;9 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;9_iRace&quot;
##  $ iRace10  : logi  NA NA NA NA NA NA ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;10 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;10_iRace&quot;
##  $ cmBiMulti: num  0 0 0 2 5 15 0 0 0 7 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Regarding race, what proportion of students were from each broad classification.  Your responses should add to &quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Race_10&quot;
##  $ cmBlack  : num  0 5 10 6 5 20 0 0 0 4 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Regarding race, what proportion of students were from each broad classification.  Your responses should add to 100%. - Black&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Race_1&quot;
##  $ cmNBPoC  : num  39 10 30 19 10 30 40 5 30 13 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Regarding race, what proportion of students were from each broad classification.  Your responses should add to &quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Race_7&quot;
##  $ cmWhite  : num  61 85 60 73 80 35 60 90 70 73 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Regarding race, what proportion of students were from each broad classification.  Your responses should add to 100%. - White&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Race_8&quot;
##  $ cmUnsure : num  0 0 0 0 0 0 0 5 0 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Regarding race, what proportion of students were from each broad classification.  Your responses should add to 100%. - Unsure&quot;
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Race_2&quot;
##  $ Belong_1 : num  6 4 NA 5 4 5 6 7 6 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Please indicate the degree to which you agree with the following questions about the course. Please skip the it&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Belong_1&quot;
##  $ Belong_2 : num  6 4 3 3 4 6 6 7 6 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Please indicate the degree to which you agree with the following questions about the course. Please skip the it&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Belong_2&quot;
##  $ Belong_3 : num  7 6 NA 2 4 5 5 7 6 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Please indicate the degree to which you agree with the following questions about the course. Please skip the it&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Belong_3&quot;
##  $ Blst_1   : num  5 6 NA 2 6 5 5 5 5 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_1&quot;
##  $ Blst_2   : num  3 6 5 2 1 1 4 4 3 5 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_2&quot;
##  $ Blst_3   : num  5 2 2 2 1 1 4 3 1 2 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_3&quot;
##  $ Blst_4   : num  2 2 2 2 1 2 4 3 2 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_4&quot;
##  $ Blst_5   : num  2 4 NA 2 1 1 4 4 1 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_5&quot;
##  $ Blst_6   : num  2 1 2 2 1 2 4 3 2 3 ...
##   ..- attr(*, &quot;label&quot;)= Named chr &quot;Each item below asks you to rate elements of campus climate for your \&quot;academic department/program.\&quot;  If you d&quot;| __truncated__
##   .. ..- attr(*, &quot;names&quot;)= chr &quot;Blst_6&quot;
##  - attr(*, &quot;column_map&quot;)=Classes &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;:   182 obs. of  7 variables:
##   ..$ qname      : chr [1:182] &quot;StartDate&quot; &quot;EndDate&quot; &quot;Status&quot; &quot;Progress&quot; ...
##   ..$ description: chr [1:182] &quot;Start Date&quot; &quot;End Date&quot; &quot;Response Type&quot; &quot;Progress&quot; ...
##   ..$ main       : chr [1:182] &quot;Start Date&quot; &quot;End Date&quot; &quot;Response Type&quot; &quot;Progress&quot; ...
##   ..$ sub        : chr [1:182] &quot;&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##   ..$ ImportId   : chr [1:182] &quot;startDate&quot; &quot;endDate&quot; &quot;status&quot; &quot;progress&quot; ...
##   ..$ timeZone   : chr [1:182] &quot;America/Los_Angeles&quot; &quot;America/Los_Angeles&quot; NA NA ...
##   ..$ choiceId   : chr [1:182] NA NA NA NA ...</code></pre>
<p>Let’s think about how the variables in our model should be measured:</p>
<ul>
<li>DV: Campus Climate for Black Students (as perceived by the respondent)
<ul>
<li>mean score of the 6 items on that scale (higher scores indicate a climate characterized by hostility, nonresponsiveness, and stigma)</li>
<li>1 item needs to be reverse-coded</li>
<li>this scale was adapted from the LGBT Campus Climate Scale <span class="citation">(<a href="#ref-szymanski_perceptions_2020">Szymanski &amp; Bissonette, 2020</a>)</span></li>
</ul></li>
<li>IV: Belonging
<ul>
<li>mean score for the 3 items on that scale (higher scores indicate a greater sense of belonging)</li>
<li>this scale is taken from the Sense of Belonging subscale from the Perceived Cohesion Scale <span class="citation">(<a href="#ref-bollen_perceived_1990">Bollen &amp; Hoyle, 1990</a>)</span></li>
</ul></li>
<li>Proportion of classmates who are Black
<ul>
<li>a single item</li>
</ul></li>
<li>Proportion of instructional staff who are BIPOC
<ul>
<li>must be calculated from each of the single items for each instructor</li>
</ul></li>
</ul>
<p>To summarize, the Campus Climate and Belonging scales are traditional in the sense that they have items that we sum. The variable representing proportion of classmates who are Black is a single item. The variable representing the proportion of instructional staff who are BIPOC must be calculated in a manner that takes into consideration the there may be multiple instructors. The survey allowed a respondent to name up to 10 instructors.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="score.html#cb29-1" tabindex="-1"></a><span class="fu">str</span>(scrub_df<span class="sc">$</span>iRace1)</span></code></pre></div>
<pre><code>##  num [1:69] 3 3 3 3 1 3 3 3 1 0 ...
##  - attr(*, &quot;label&quot;)= Named chr &quot;1 - From your perspective as a student, which of the following best describes the [Field-2] instructor.&quot;
##   ..- attr(*, &quot;names&quot;)= chr &quot;1_iRace&quot;</code></pre>
<p>Looking at the structure of our data, the iRace(1 thru 10) variables are in “int” or integer format. This means that they are represented as whole numbers. We need them to be represented as factors. R handles factors represented as words well. Therefore, let’s use our codebook to reformat this variable as a an ordered factor, with words instead of numbers.</p>
<p>Qualtrics imports many of the categorical variables as numbers. R often reads them numerically (integers or numbers). If they are directly converted to factors, R will sometimes collapse across missing numbers. In this example, if there is a race that is not represented (e.g., 2 for BiMulti), when the numbers are changed to factors, R will assume they are ordered and there is a consecutive series of numbers (0,1,2,3,4). If a number in the sequence is missing (0,1,3,4) and labels are applied, it will collapse across the numbers and the labels you think are attached to each number are not. Therefore, it is ESSENTIAL to check (again and again ad nauseum) to ensure that your variables are recoding in a manner you understand.</p>
<p>One way to avoid this is to use the code below to identify the levels and the labels. When they are in order, they align and don’t “skip” numbers. To quadruple check our work, we will recode into a new variable “tRace#” for “teacher” Race.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="score.html#cb31-1" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace1 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace1, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-2"><a href="score.html#cb31-2" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-3"><a href="score.html#cb31-3" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace2 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace2, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-4"><a href="score.html#cb31-4" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-5"><a href="score.html#cb31-5" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace3 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace3, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-6"><a href="score.html#cb31-6" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-7"><a href="score.html#cb31-7" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace4 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace4, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-8"><a href="score.html#cb31-8" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-9"><a href="score.html#cb31-9" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace5 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace5, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-10"><a href="score.html#cb31-10" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-11"><a href="score.html#cb31-11" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace6 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace6, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-12"><a href="score.html#cb31-12" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-13"><a href="score.html#cb31-13" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace7 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace7, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-14"><a href="score.html#cb31-14" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-15"><a href="score.html#cb31-15" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace8 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace8, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-16"><a href="score.html#cb31-16" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-17"><a href="score.html#cb31-17" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace9 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace9, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>,</span>
<span id="cb31-18"><a href="score.html#cb31-18" tabindex="-1"></a>    <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span>
<span id="cb31-19"><a href="score.html#cb31-19" tabindex="-1"></a>scrub_df<span class="sc">$</span>tRace10 <span class="ot">=</span> <span class="fu">factor</span>(scrub_df<span class="sc">$</span>iRace10, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>),</span>
<span id="cb31-20"><a href="score.html#cb31-20" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>, <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>, <span class="st">&quot;White&quot;</span>, <span class="st">&quot;NotNotice&quot;</span>))</span></code></pre></div>
<p>Let’s check the structure to see if they are factors.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="score.html#cb32-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.2     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="score.html#cb34-1" tabindex="-1"></a><span class="fu">glimpse</span>(scrub_df)</span></code></pre></div>
<pre><code>## Rows: 69
## Columns: 35
## $ ID        &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
## $ iRace1    &lt;dbl&gt; 3, 3, 3, 3, 1, 3, 3, 3, 1, 0, 2, 1, 1, 1, 3, 3, 3, 1, 3, 3, …
## $ iRace2    &lt;dbl&gt; 1, NA, 1, 1, NA, NA, 3, NA, NA, 0, NA, NA, 3, NA, 3, 3, NA, …
## $ iRace3    &lt;dbl&gt; 3, NA, NA, 3, NA, NA, NA, NA, NA, 3, NA, NA, NA, NA, 3, 1, N…
## $ iRace4    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, 3, NA, NA, NA, NA, NA, 3…
## $ iRace5    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ iRace6    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ iRace7    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ iRace8    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ iRace9    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ iRace10   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ cmBiMulti &lt;dbl&gt; 0, 0, 0, 2, 5, 15, 0, 0, 0, 7, 0, 0, 20, 0, 9, 12, 0, 6, 6, …
## $ cmBlack   &lt;dbl&gt; 0, 5, 10, 6, 5, 20, 0, 0, 0, 4, 0, 7, 0, 6, 9, 1, 21, 5, 6, …
## $ cmNBPoC   &lt;dbl&gt; 39, 10, 30, 19, 10, 30, 40, 5, 30, 13, 80, 19, 0, 19, 15, 22…
## $ cmWhite   &lt;dbl&gt; 61, 85, 60, 73, 80, 35, 60, 90, 70, 73, 10, 74, 80, 0, 67, 5…
## $ cmUnsure  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 5, 0, 3, 10, 0, 0, 75, 0, 14, 0, 5, 0, …
## $ Belong_1  &lt;dbl&gt; 6, 4, NA, 5, 4, 5, 6, 7, 6, 3, 6, 6, 3, 4, 3, 3, 4, 5, 1, 2,…
## $ Belong_2  &lt;dbl&gt; 6, 4, 3, 3, 4, 6, 6, 7, 6, 3, 6, 6, 5, 4, 3, 3, 4, 6, 1, 2, …
## $ Belong_3  &lt;dbl&gt; 7, 6, NA, 2, 4, 5, 5, 7, 6, 3, 5, 6, 4, 4, 3, 2, 4, 5, 1, 1,…
## $ Blst_1    &lt;dbl&gt; 5, 6, NA, 2, 6, 5, 5, 5, 5, 3, NA, 4, 5, 6, 3, 4, 6, 4, 4, 4…
## $ Blst_2    &lt;dbl&gt; 3, 6, 5, 2, 1, 1, 4, 4, 3, 5, NA, 5, 1, 1, 3, 2, 1, 2, 5, 3,…
## $ Blst_3    &lt;dbl&gt; 5, 2, 2, 2, 1, 1, 4, 3, 1, 2, 2, 1, 1, 1, 3, 2, 6, 2, 2, 2, …
## $ Blst_4    &lt;dbl&gt; 2, 2, 2, 2, 1, 2, 4, 3, 2, 3, NA, 4, 3, 1, 3, 2, 1, 3, 2, 1,…
## $ Blst_5    &lt;dbl&gt; 2, 4, NA, 2, 1, 1, 4, 4, 1, 3, 2, 2, 1, 1, 3, 2, 1, 2, 2, 1,…
## $ Blst_6    &lt;dbl&gt; 2, 1, 2, 2, 1, 2, 4, 3, 2, 3, NA, 2, 1, 1, 3, 2, 2, 3, 2, 1,…
## $ tRace1    &lt;fct&gt; White, White, White, White, nBpoc, White, White, White, nBpo…
## $ tRace2    &lt;fct&gt; nBpoc, NA, nBpoc, nBpoc, NA, NA, White, NA, NA, Black, NA, N…
## $ tRace3    &lt;fct&gt; White, NA, NA, White, NA, NA, NA, NA, NA, White, NA, NA, NA,…
## $ tRace4    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, White, NA, NA, NA, NA, N…
## $ tRace5    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ tRace6    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ tRace7    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ tRace8    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ tRace9    &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ tRace10   &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
<p>Calculating the proportion of the BIPOC instructional staff could likely be accomplished a number of ways. My searching for solutions resulted in this. Hopefully it’s a fair balance between intuitive and elegant coding. First, I created code that</p>
<ul>
<li>created a new variable (count.BIPOC) by
<ul>
<li>summing across the tRace1 through tRace10 variables,</li>
<li>assigning a count of “1” each time the factor value was Black, nBpoc, or BiMulti</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="score.html#cb36-1" tabindex="-1"></a>scrub_df<span class="sc">$</span>count.BIPOC <span class="ot">&lt;-</span> <span class="fu">apply</span>(scrub_df[<span class="fu">c</span>(<span class="st">&quot;tRace1&quot;</span>, <span class="st">&quot;tRace2&quot;</span>, <span class="st">&quot;tRace3&quot;</span>,</span>
<span id="cb36-2"><a href="score.html#cb36-2" tabindex="-1"></a>    <span class="st">&quot;tRace4&quot;</span>, <span class="st">&quot;tRace5&quot;</span>, <span class="st">&quot;tRace6&quot;</span>, <span class="st">&quot;tRace7&quot;</span>, <span class="st">&quot;tRace8&quot;</span>, <span class="st">&quot;tRace9&quot;</span>, <span class="st">&quot;tRace10&quot;</span>)],</span>
<span id="cb36-3"><a href="score.html#cb36-3" tabindex="-1"></a>    <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(x <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Black&quot;</span>, <span class="st">&quot;nBpoc&quot;</span>, <span class="st">&quot;BiMulti&quot;</span>)))</span></code></pre></div>
<p>Next, I created a variable that counted the number of non-missing values across the tRace1 through tRace10 variables.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="score.html#cb37-1" tabindex="-1"></a>scrub_df<span class="sc">$</span>count.nMiss <span class="ot">&lt;-</span> <span class="fu">apply</span>(scrub_df[<span class="fu">c</span>(<span class="st">&quot;tRace1&quot;</span>, <span class="st">&quot;tRace2&quot;</span>, <span class="st">&quot;tRace3&quot;</span>,</span>
<span id="cb37-2"><a href="score.html#cb37-2" tabindex="-1"></a>    <span class="st">&quot;tRace4&quot;</span>, <span class="st">&quot;tRace5&quot;</span>, <span class="st">&quot;tRace6&quot;</span>, <span class="st">&quot;tRace7&quot;</span>, <span class="st">&quot;tRace8&quot;</span>, <span class="st">&quot;tRace9&quot;</span>, <span class="st">&quot;tRace10&quot;</span>)],</span>
<span id="cb37-3"><a href="score.html#cb37-3" tabindex="-1"></a>    <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x)))</span></code></pre></div>
<p>Now to calculate the proportion of BIPOC instructional faculty for each case.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="score.html#cb38-1" tabindex="-1"></a>scrub_df<span class="sc">$</span>iBIPOC_pr <span class="ot">=</span> scrub_df<span class="sc">$</span>count.BIPOC<span class="sc">/</span>scrub_df<span class="sc">$</span>count.nMiss</span></code></pre></div>
</div>
<div id="missing-data-analysis-whole-df-and-item-level" class="section level3 hasAnchor" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Missing Data Analysis: Whole df and Item level<a href="score.html#missing-data-analysis-whole-df-and-item-level" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In understanding missingness across the dataset, I think it is important to analyze and manage it, iteratively. We will start with a view of the whole df-level missingness. Subsequently, and consistent with the available information analysis [AIA; <span class="citation">Parent (<a href="#ref-parent_handling_2013">2013</a>)</span>] approach, we will score the scales and then look again at missingness, using the new information to update our decisions about how to manage it.</p>
<div class="float">
<img src="images/Ch02/wrkflow_item_lvl.jpg" alt="An image of our stage in the workflow for scrubbing and scoring data." />
<div class="figcaption">An image of our stage in the workflow for scrubbing and scoring data.</div>
</div>
<p>Because we just created a host of new variables in creating the <em>prop_BIPOC</em> variable, let’s downsize the df so that the calculations are sensible.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="score.html#cb39-1" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> (<span class="fu">select</span>(scrub_df, ID, iBIPOC_pr, cmBlack, Belong_1<span class="sc">:</span>Belong_3,</span>
<span id="cb39-2"><a href="score.html#cb39-2" tabindex="-1"></a>    Blst_1<span class="sc">:</span>Blst_6))</span></code></pre></div>
<p>With a couple of calculations, we create a proportion of item-level missingness.</p>
<p>In this chunk I first calculate the number of missing (nmiss)</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="score.html#cb40-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb40-2"><a href="score.html#cb40-2" tabindex="-1"></a><span class="co">#Calculating number and proportion of item-level missingness</span></span>
<span id="cb40-3"><a href="score.html#cb40-3" tabindex="-1"></a>scrub_df<span class="sc">$</span>nmiss <span class="ot">&lt;-</span> scrub_df<span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="score.html#cb40-4" tabindex="-1"></a>    <span class="fu">select</span>(iBIPOC_pr<span class="sc">:</span>Blst_6) <span class="sc">%&gt;%</span> <span class="co">#the colon allows us to include all variables between the two listed (the variables need to be in order)</span></span>
<span id="cb40-5"><a href="score.html#cb40-5" tabindex="-1"></a>    is.na <span class="sc">%&gt;%</span> </span>
<span id="cb40-6"><a href="score.html#cb40-6" tabindex="-1"></a>    rowSums</span>
<span id="cb40-7"><a href="score.html#cb40-7" tabindex="-1"></a></span>
<span id="cb40-8"><a href="score.html#cb40-8" tabindex="-1"></a>scrub_df<span class="ot">&lt;-</span> scrub_df<span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="score.html#cb40-9" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">prop_miss =</span> (nmiss<span class="sc">/</span><span class="dv">11</span>)<span class="sc">*</span><span class="dv">100</span>) <span class="co">#11 is the number of variables included in calculating the proportion</span></span></code></pre></div>
<p>We can grab the descriptives for the <em>prop_miss</em> variable to begin to understand our data. I will create an object from it so I can use it with inline</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="score.html#cb41-1" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(scrub_df<span class="sc">$</span>prop_miss)</span></code></pre></div>
<pre><code>##    vars  n mean    sd median trimmed mad min max range skew kurtosis   se
## X1    1 69 7.77 22.61      0    1.59   0   0 100   100 3.04     8.19 2.72</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP:</p>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 100%.</p>
</blockquote>
</blockquote>
<p>At the time that I am lecturing this, we do have some rather egregious missingness. At this point I will write code to eliminate cases with <span class="math inline">\(\geq\)</span> 90%.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="score.html#cb43-1" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(scrub_df, prop_miss <span class="sc">&lt;=</span> <span class="dv">90</span>)  <span class="co">#update df to have only those with at least 90% of complete data</span></span></code></pre></div>
<p>To analyze missingness at this level, we need a df that has only the variables of interest. That is, variables like <em>ID</em> and the <em>prop_miss</em> and <em>nmiss</em> variables we created will interfere with an accurate assessment of missingness. I will update our df to eliminate these.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="score.html#cb44-1" tabindex="-1"></a><span class="co"># further update to exclude the n_miss and prop_miss variables</span></span>
<span id="cb44-2"><a href="score.html#cb44-2" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="score.html#cb44-3" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(ID, nmiss, prop_miss))</span></code></pre></div>
<p>Missing data analysis commonly looks at proportions by:</p>
<ul>
<li>the entire df</li>
<li>rows/cases/people</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="score.html#cb45-1" tabindex="-1"></a><span class="co"># what proportion of cells missing across entire dataset</span></span>
<span id="cb45-2"><a href="score.html#cb45-2" tabindex="-1"></a>formattable<span class="sc">::</span><span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">is.na</span>(scrub_df)))</span></code></pre></div>
<pre><code>## [1] 3.86%</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="score.html#cb47-1" tabindex="-1"></a><span class="co"># what proportion of cases (rows) are complete (nonmissing)</span></span>
<span id="cb47-2"><a href="score.html#cb47-2" tabindex="-1"></a>formattable<span class="sc">::</span><span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">complete.cases</span>(scrub_df)))</span></code></pre></div>
<pre><code>## [1] 87.88%</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP:</p>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 100%. Across the dataset, 3.86% of cells had missing data and 87.88% of cases had nonmissing data.</p>
</blockquote>
</blockquote>
</div>
<div id="analyzing-missing-data-patterns" class="section level3 hasAnchor" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Analyzing Missing Data Patterns<a href="score.html#analyzing-missing-data-patterns" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One approach to analyzing missing data is to assess patterns of missingness.</p>
<p>Several R packages are popularly used for conducting such analyses. In the <em>mice</em> package, <em>md.pattern()</em> function provides a matrix with the number of columns + 1, in which each row corresponds to a missing data pattern (1 = observed, 0 = missing).</p>
<p>Rows and columns are sorted in increasing amounts of missing information.</p>
<p>The last column and row contain row and column counts, respectively.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="score.html#cb49-1" tabindex="-1"></a>mice_out <span class="ot">&lt;-</span> mice<span class="sc">::</span><span class="fu">md.pattern</span>(scrub_df, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">rotate.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-2"><a href="score.html#cb49-2" tabindex="-1"></a>mice_out</span>
<span id="cb49-3"><a href="score.html#cb49-3" tabindex="-1"></a><span class="fu">write.csv</span>(mice_out, <span class="at">file =</span> <span class="st">&quot;mice_out.csv&quot;</span>)  <span class="co">#optional to write it to a .csv file</span></span></code></pre></div>
<p>The table lets us examine each missing pattern and see which variable(s) is/are missing. The output is in the form of a table that indicates the frequency of each pattern of missingness. Because I haven’t (yet) figured out how to pipe objects from this table into the chapter, this text may differ from the patterns in the current data frame.</p>
<p>Each row in the table represents a different pattern of missingness. At the time of writing, there are <em>8</em> patterns of missing data. The patterns are listed in descending order of the least amount of missingness. The most common pattern (<em>58</em> cases, top row) is one with no missing data. One case is missing one cell – one item assessing the campus climate for Black students, and so forth.</p>
</div>
<div id="can-we-identify-the-missing-mechanisms" class="section level3 hasAnchor" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Can we identify the missing mechanisms?<a href="score.html#can-we-identify-the-missing-mechanisms" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To date, we do not have statistical tools that can accurately diagnose our patterns of missingness. You may have heard that “Little’s MCAR” is a helpful tool. Unfortunately, as Enders <span class="citation">(<a href="#ref-enders_applied_2010">2010</a>)</span> has noted, the tool is problematic. Perhaps the most significant one is that under the null hypothesis, a statistically significant test indicates that the missing data are MAR (missing at random) or MNAR (missing not at random); a non-significant test indicates the data are MCAR (missing completely at random) or MNAR. Consequently, regardless of the result, an MNAR circumstance cannot be ruled out. Correspondingly, the Little’s MCAR test has disappeared from the more reliable R packages that assess missingness.</p>
<p>Enders <span class="citation">(<a href="#ref-enders_applied_2010">2010</a>)</span> <em>Applied Missing Data Analysis</em> text does provide a set of <a href="https://www.google.com/books/edition/Applied_Missing_Data_Analysis/uHt4EAAAQBAJ?hl=en&amp;gbpv=1&amp;dq=enders+missing+data&amp;pg=PP1&amp;printsec=frontcover">figures</a> (page 3) that illustrate common missing data patterns. Comparing these to the figure produced with <em>mice::mdpattern</em> our data looks somewhat monotonic – that is, as individuals completed the survey, they began to experience test fatigue and simply stopped responding. Diagnosisng monotonicity requires that the variables in the dataset must be in the order in which the students completed them. If the variables have been re-ordered or if the surveys were presented to students in a randomized order, then more data manipulation would be required before attributing missingness to test fatigue.</p>
<p>Survey programs like Qualtrics offer the randomization of items within blocks (or blocks themselves). This can help distribute missingness caused by test fatigue so that more cases can be retained.</p>
</div>
</div>
<div id="scoring" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Scoring<a href="score.html#scoring" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So let’s get to work to score up the measures for our analysis. Each step of this should involve careful cross-checking with the <a href="https://github.com/lhbikos/ReC_MultivModel/blob/main/Rate_a_Course_Codebook.pdf">codebook</a>.</p>
<div id="reverse-scoring" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Reverse scoring<a href="score.html#reverse-scoring" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As we discovered previously, in the scale that assesses campus climate (higher scores reflect a more negative climate) one of our items (Blst_1, “My <em>institution</em> provides a supportive environment for Black students.”) requires reverse-coding.</p>
<p>To rescore:</p>
<ul>
<li>Create a <em>new</em> variable (this is essential) that is designated as the reversed item. We might put a the letter “r” (for reverse scoring) at the beginning or end: rBlst_1 or Blst_1r. It does not matter; just be consistent.
<ul>
<li>We don’t reverse score into the same variable because when you rerun the script, it just re-reverses the reversed score…into infinity. It’s very easy to lose your place.</li>
</ul></li>
<li>The reversal is an <em>equation</em> where you subtract the value in the item from the range/scaling + 1. For the our three items we subtract each item’s value from 8.</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="score.html#cb50-1" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="score.html#cb50-2" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">rBlst_1 =</span> <span class="dv">8</span> <span class="sc">-</span> Blst_1)  <span class="co">#if you had multiple items, you could add a pipe (%&gt;%) at the end of the line and add more until the last one</span></span></code></pre></div>
<p>Per Parent <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> we will analyze missingness for each scale, separately.</p>
<ul>
<li>We will calculate scale scores on each scale separately when 80% (roughly) of the data is present.
<ul>
<li>this is somewhat arbitrary, on 4 item scales, I would choose 75% (to allow one to be missing)</li>
<li>on the 3 item scale, I will allow one item to be missing (65%)</li>
</ul></li>
<li>After calculating the scale scores, we will return to analyzing the missingness, looking at the whole df</li>
</ul>
<p>The <em>mean_n()</em> function of <em>sjstats</em> package has allows you to specify how many items (whole number) or what percentage of items should be present in order to get the mean. First, though, we should identify the variables (properly formatted, if rescoring was needed) that should be included in the calculation of each scale and subscale.</p>
<p>In our case, the scale assessing belonging <span class="citation">(<a href="#ref-bollen_perceived_1990">Bollen &amp; Hoyle, 1990</a>; <a href="#ref-hurtado_effects_1997">Hurtado &amp; Carter, 1997</a>)</span> involves three items with no reversals. Our campus climate scale was adapted from Szymanski et al.’s LGBTQ College Campus Climate Scale <span class="citation">(<a href="#ref-szymanski_perceptions_2020">Szymanski &amp; Bissonette, 2020</a>)</span>. While it has not been psychometrically evaluated for the purpose for which I am using it, I will follow the scoring structure in the journal article that introduces the measure. Specifically, the factor structure permits a total scale score and two subscales representing the college response and stigma.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="score.html#cb51-1" tabindex="-1"></a><span class="co"># Making the list of variables</span></span>
<span id="cb51-2"><a href="score.html#cb51-2" tabindex="-1"></a>Belonging_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Belong_1&quot;</span>, <span class="st">&quot;Belong_2&quot;</span>, <span class="st">&quot;Belong_3&quot;</span>)</span>
<span id="cb51-3"><a href="score.html#cb51-3" tabindex="-1"></a>ResponseBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;rBlst_1&quot;</span>, <span class="st">&quot;Blst_4&quot;</span>, <span class="st">&quot;Blst_6&quot;</span>)</span>
<span id="cb51-4"><a href="score.html#cb51-4" tabindex="-1"></a>StigmaBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Blst_2&quot;</span>, <span class="st">&quot;Blst_3&quot;</span>, <span class="st">&quot;Blst_5&quot;</span>)</span>
<span id="cb51-5"><a href="score.html#cb51-5" tabindex="-1"></a>ClimateBL_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;rBlst_1&quot;</span>, <span class="st">&quot;Blst_4&quot;</span>, <span class="st">&quot;Blst_6&quot;</span>, <span class="st">&quot;Blst_2&quot;</span>, <span class="st">&quot;Blst_3&quot;</span>,</span>
<span id="cb51-6"><a href="score.html#cb51-6" tabindex="-1"></a>    <span class="st">&quot;Blst_5&quot;</span>)</span>
<span id="cb51-7"><a href="score.html#cb51-7" tabindex="-1"></a></span>
<span id="cb51-8"><a href="score.html#cb51-8" tabindex="-1"></a><span class="co"># Creating the new variables</span></span>
<span id="cb51-9"><a href="score.html#cb51-9" tabindex="-1"></a>scrub_df<span class="sc">$</span>Belonging <span class="ot">&lt;-</span> sjstats<span class="sc">::</span><span class="fu">mean_n</span>(scrub_df[, Belonging_vars], <span class="fl">0.65</span>)</span>
<span id="cb51-10"><a href="score.html#cb51-10" tabindex="-1"></a>scrub_df<span class="sc">$</span>ResponseBL <span class="ot">&lt;-</span> sjstats<span class="sc">::</span><span class="fu">mean_n</span>(scrub_df[, ResponseBL_vars], <span class="fl">0.8</span>)</span>
<span id="cb51-11"><a href="score.html#cb51-11" tabindex="-1"></a>scrub_df<span class="sc">$</span>StigmaBL <span class="ot">&lt;-</span> sjstats<span class="sc">::</span><span class="fu">mean_n</span>(scrub_df[, StigmaBL_vars], <span class="fl">0.8</span>)</span>
<span id="cb51-12"><a href="score.html#cb51-12" tabindex="-1"></a>scrub_df<span class="sc">$</span>ClimateBL <span class="ot">&lt;-</span> sjstats<span class="sc">::</span><span class="fu">mean_n</span>(scrub_df[, ClimateBL_vars], <span class="fl">0.8</span>)</span>
<span id="cb51-13"><a href="score.html#cb51-13" tabindex="-1"></a></span>
<span id="cb51-14"><a href="score.html#cb51-14" tabindex="-1"></a><span class="co"># If the scoring code above does not work for you, try the format</span></span>
<span id="cb51-15"><a href="score.html#cb51-15" tabindex="-1"></a><span class="co"># below which involves inserting to periods in front of the variable</span></span>
<span id="cb51-16"><a href="score.html#cb51-16" tabindex="-1"></a><span class="co"># list. One example is provided. dfLewis$Belonging &lt;-</span></span>
<span id="cb51-17"><a href="score.html#cb51-17" tabindex="-1"></a><span class="co"># sjstats::mean_n(dfLewis[, ..Belonging_vars], 0.80)</span></span></code></pre></div>
<p>Later it will be helpful to have a df with the item and scale-level variables. It will also be helpful if there is an ID for each case.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="score.html#cb52-1" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="score.html#cb52-2" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">ID =</span> <span class="fu">row_number</span>())</span>
<span id="cb52-3"><a href="score.html#cb52-3" tabindex="-1"></a></span>
<span id="cb52-4"><a href="score.html#cb52-4" tabindex="-1"></a><span class="co"># moving the ID number to the first column; requires</span></span>
<span id="cb52-5"><a href="score.html#cb52-5" tabindex="-1"></a>scrub_df <span class="ot">&lt;-</span> scrub_df <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="score.html#cb52-6" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(ID, <span class="fu">everything</span>())</span></code></pre></div>
<p>Let’s save our <em>scrub_df</em> data for this and write it as an outfile. I will save it in both .rds and .csv formats so that you can use either one.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="score.html#cb53-1" tabindex="-1"></a><span class="fu">write.table</span>(scrub_df, <span class="at">file =</span> <span class="st">&quot;BlStItmsScrs230902.csv&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>, <span class="at">col.names =</span> <span class="cn">TRUE</span>,</span>
<span id="cb53-2"><a href="score.html#cb53-2" tabindex="-1"></a>    <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb53-3"><a href="score.html#cb53-3" tabindex="-1"></a><span class="fu">saveRDS</span>(scrub_df, <span class="st">&quot;BlStItmsScrs230902.rds&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="missing-analysis-scale-level" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Missing Analysis: Scale level<a href="score.html#missing-analysis-scale-level" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s return to analyzing the missingness, this time including the <em>scale level</em> variables (without the individual items) that will be in our statistical model(s).</p>
<div class="float">
<img src="images/Ch02/wrkflow_scale_lvl.jpg" alt="An image of our stage in the workflow for scrubbing and scoring data." />
<div class="figcaption">An image of our stage in the workflow for scrubbing and scoring data.</div>
</div>
<p>First let’s get the df down to the variables we want to retain:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="score.html#cb54-1" tabindex="-1"></a>scored <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(scrub_df, iBIPOC_pr, cmBlack, Belonging, ResponseBL,</span>
<span id="cb54-2"><a href="score.html#cb54-2" tabindex="-1"></a>    StigmaBL, ClimateBL)</span>
<span id="cb54-3"><a href="score.html#cb54-3" tabindex="-1"></a>ScoredCaseMiss <span class="ot">&lt;-</span> <span class="fu">nrow</span>(scored)  <span class="co">#I produced this object for the sole purpose of feeding the number of cases into the inline text, below</span></span>
<span id="cb54-4"><a href="score.html#cb54-4" tabindex="-1"></a>ScoredCaseMiss</span></code></pre></div>
<pre><code>## [1] 66</code></pre>
<p>Before we start our formal analysis of missingness at the scale level, let’s continue to scrub by eliminating cases that will have too much missingness. In the script below we create a variable that counts the number of missing variables and then creates a proportion by dividing it by the number of total variables.</p>
<p>Using the <em>describe()</em> function from the <em>psych</em> package, we can investigate this variable.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="score.html#cb56-1" tabindex="-1"></a><span class="co"># Create a variable (n_miss) that counts the number missing</span></span>
<span id="cb56-2"><a href="score.html#cb56-2" tabindex="-1"></a>scored<span class="sc">$</span>n_miss <span class="ot">&lt;-</span> scored <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="score.html#cb56-3" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(iBIPOC_pr<span class="sc">:</span>ClimateBL) <span class="sc">%&gt;%</span></span>
<span id="cb56-4"><a href="score.html#cb56-4" tabindex="-1"></a>    is.na <span class="sc">%&gt;%</span></span>
<span id="cb56-5"><a href="score.html#cb56-5" tabindex="-1"></a>    rowSums</span>
<span id="cb56-6"><a href="score.html#cb56-6" tabindex="-1"></a></span>
<span id="cb56-7"><a href="score.html#cb56-7" tabindex="-1"></a><span class="co"># Create a proportion missing by dividing n_miss by the total number</span></span>
<span id="cb56-8"><a href="score.html#cb56-8" tabindex="-1"></a><span class="co"># of variables (6) Pipe to sort in order of descending frequency to</span></span>
<span id="cb56-9"><a href="score.html#cb56-9" tabindex="-1"></a><span class="co"># get a sense of the missingness</span></span>
<span id="cb56-10"><a href="score.html#cb56-10" tabindex="-1"></a>scored <span class="ot">&lt;-</span> scored <span class="sc">%&gt;%</span></span>
<span id="cb56-11"><a href="score.html#cb56-11" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">prop_miss =</span> (n_miss<span class="sc">/</span><span class="dv">6</span>) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb56-12"><a href="score.html#cb56-12" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(n_miss))</span>
<span id="cb56-13"><a href="score.html#cb56-13" tabindex="-1"></a></span>
<span id="cb56-14"><a href="score.html#cb56-14" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(scored<span class="sc">$</span>prop_miss)</span></code></pre></div>
<pre><code>##    vars  n mean    sd median trimmed mad min   max range skew kurtosis   se
## X1    1 66 3.79 12.33      0    0.31   0   0 66.67 66.67 3.44    11.77 1.52</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP:</p>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 100%. Across the dataset, 3.86% of cells had missing data and 87.88% of cases had nonmissing data.</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Across the 66 cases for which the scoring protocol was applied, missingness ranged from 0 to 67%.</p>
</blockquote>
</blockquote>
<p>We need to decide what is our retention threshhold. Twenty percent seems to be a general rule of thumb. Let’s delete all cases with missingness at 20% or greater.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="score.html#cb58-1" tabindex="-1"></a><span class="co"># update df to have only those with at least 20% of complete data</span></span>
<span id="cb58-2"><a href="score.html#cb58-2" tabindex="-1"></a><span class="co"># (this is an arbitrary decision)</span></span>
<span id="cb58-3"><a href="score.html#cb58-3" tabindex="-1"></a>scored <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(scored, prop_miss <span class="sc">&lt;=</span> <span class="dv">20</span>)</span>
<span id="cb58-4"><a href="score.html#cb58-4" tabindex="-1"></a></span>
<span id="cb58-5"><a href="score.html#cb58-5" tabindex="-1"></a><span class="co"># the variable selection just lops off the proportion missing</span></span>
<span id="cb58-6"><a href="score.html#cb58-6" tabindex="-1"></a>scored <span class="ot">&lt;-</span> (<span class="fu">select</span>(scored, iBIPOC_pr<span class="sc">:</span>ClimateBL))</span>
<span id="cb58-7"><a href="score.html#cb58-7" tabindex="-1"></a></span>
<span id="cb58-8"><a href="score.html#cb58-8" tabindex="-1"></a><span class="co"># this produces the number of cases retained</span></span>
<span id="cb58-9"><a href="score.html#cb58-9" tabindex="-1"></a><span class="fu">nrow</span>(scored)</span></code></pre></div>
<pre><code>## [1] 61</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP:</p>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 100%. Across the dataset, 3.86% of cells had missing data and 87.88% of cases had nonmissing data.</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Across the 66 cases for which the scoring protocol was applied, missingness ranged from 0 to 67%. After eliminating cases with greater than 20% missing, the dataset analyzed included 61 cases.</p>
</blockquote>
</blockquote>
<p>With a decision about the number of cases we are going to include, we can continue to analyze missingness.</p>
</div>
<div id="revisiting-missing-analysis-at-the-scale-level" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Revisiting Missing Analysis at the Scale Level<a href="score.html#revisiting-missing-analysis-at-the-scale-level" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We work with a df that includes only the variables in our model. In our case this is easy. In other cases (i.e., maybe there is an ID number) it might be good to create a subset just for this analysis.</p>
<p>Again, we look at missingness as the proportion of</p>
<ul>
<li>individual cells across the scored dataset, and</li>
<li>rows/cases with nonmissing data</li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="score.html#cb60-1" tabindex="-1"></a><span class="co"># percent missing across df</span></span>
<span id="cb60-2"><a href="score.html#cb60-2" tabindex="-1"></a>formattable<span class="sc">::</span><span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">is.na</span>(scored)))</span></code></pre></div>
<pre><code>## [1] 0.55%</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="score.html#cb62-1" tabindex="-1"></a><span class="co"># percent of rows with nonmissing data</span></span>
<span id="cb62-2"><a href="score.html#cb62-2" tabindex="-1"></a>formattable<span class="sc">::</span><span class="fu">percent</span>(<span class="fu">mean</span>(<span class="fu">complete.cases</span>(scored)))</span></code></pre></div>
<pre><code>## [1] 96.72%</code></pre>
<p>CUMULATIVE CAPTURE FOR WRITING IT UP:</p>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 100%. Across the dataset, 3.86% of cells had missing data and 87.88% of cases had nonmissing data.</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Across the 66 cases for which the scoring protocol was applied, missingness ranged from 0 to 67%. After eliminating cases with greater than 20% missing, the dataset analyzed included 61 cases. In this dataset we had less than 1% (0.55%) missing across the df; 97% of the rows had nonmissing data.</p>
</blockquote>
</blockquote>
<p>Let’s look again at missing patterns and mechanisms.</p>
<div id="scale-level-patterns-of-missing-data" class="section level3 hasAnchor" number="2.8.1">
<h3><span class="header-section-number">2.8.1</span> Scale Level: Patterns of Missing Data<a href="score.html#scale-level-patterns-of-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Returning to the <em>mice</em> package, we can use the <em>md.pattern()</em> function to examine a matrix with the number of columns + 1 in which each row corresponds to a missing data pattern (1 = observed, 0 = missing). The rows and columns are sorted in increasing amounts of missing information. The last column and row contain row and column counts, respectively.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="score.html#cb64-1" tabindex="-1"></a>mice_ScaleLvl <span class="ot">&lt;-</span> mice<span class="sc">::</span><span class="fu">md.pattern</span>(scored, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">rotate.names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="02-Scoring_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="score.html#cb65-1" tabindex="-1"></a>mice_ScaleLvl</span></code></pre></div>
<pre><code>##    cmBlack Belonging ResponseBL StigmaBL ClimateBL iBIPOC_pr  
## 59       1         1          1        1         1         1 0
## 2        1         1          1        1         1         0 1
##          0         0          0        0         0         2 2</code></pre>
<p>At the scale-level, this is much easier to interpret. There are <em>2</em> rows of data because there are only <em>2</em> patterns of missingness. The most common pattern is non-missing data (<em>n</em> = 59).</p>
<p>If our statistical choice uses listwise deletion (i.e., the case is eliminated if one or more variables in the model has missing data), our sample size will be 59. As we will earn in later chapters, there are alternatives (i.e., specifying a FIML option in analyses that use maximum likelihood estimators) that can use all of the cases – even those with missing data.</p>
</div>
<div id="r-eady-for-analysis" class="section level3 hasAnchor" number="2.8.2">
<h3><span class="header-section-number">2.8.2</span> R-eady for Analysis<a href="score.html#r-eady-for-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>At this stage the data is ready for analysis (data diagnostics). With the AIA approach <span class="citation">(<a href="#ref-parent_handling_2013">Parent, 2013</a>)</span> the following preliminary analyses would involve pairwise deletion (i.e., the row/case is dropped for that analysis, but included for all others):</p>
<div class="float">
<img src="images/Ch02/wrkflow_AIAready.jpg" alt="An image of our stage in the workflow for scrubbing and scoring data." />
<div class="figcaption">An image of our stage in the workflow for scrubbing and scoring data.</div>
</div>
<ul>
<li>data diagnostics
<ul>
<li>psychometric properties of scales, such as alpha coefficients</li>
<li>assessing assumptions such as univariate and multivariate normality, outliers, etc.</li>
</ul></li>
<li>preliminary analyses
<ul>
<li>descriptives (means/standard deviations, frequencies)</li>
<li>correlation matrices</li>
</ul></li>
</ul>
<p>AIA can also be used with primary analyses. Examples of how to manage missingness include:</p>
<ul>
<li>ANOVA/regression models
<ul>
<li>if completed with ordinary least squares, pairwise deletion would be utilized</li>
</ul></li>
<li>SEM/CFA models with observed, latent, or hybrid models
<ul>
<li>if FIML (we’ll discuss later) is specified, all cases are used, even when there is missingness</li>
</ul></li>
<li>EFA models
<ul>
<li>these can handle item-level missingness</li>
</ul></li>
<li>Hierarchical linear modeling/multilevel modeling/mixed effects modeling
<ul>
<li>While all data needs to be present for a given cluster/wave, it is permissible to have varying numbers of clusters/waves per case</li>
</ul></li>
</ul>
</div>
</div>
<div id="the-apa-style-write-up" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> The APA Style Write-Up<a href="score.html#the-apa-style-write-up" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="results" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Results<a href="score.html#results" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<blockquote>
<blockquote>
<p>All analyses were completed in R Studio (v. RStudio 2023.06.1+524 “Mountain Hydrangea”) with R (v. 4.3.1).</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p><strong>Missing Data Analysis and Treatment of Missing Data</strong></p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Available item analysis (AIA; <span class="citation">(<a href="#ref-parent_handling_2013">Parent, 2013</a>)</span>) is a strategy for managing missing data that uses available data for analysis and excludes cases with missing data points only for analyses in which the data points would be directly involved. Parent (2013) suggested that AIA is equivalent to more complex methods (e.g., multiple imputation) across a number of variations of sample size, magnitude of associations among items, and degree of missingness. Thus, we utilized Parent’s recommendations to guide our approach to managing missing data. Missing data analyses were conducted with tools in base R as well as the R packages, <em>psych</em> (v. 2.3.6) and <em>mice</em> (v. 3.16.0).</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Across cases that were deemed eligible on the basis of the inclusion/exclusion criteria, missingness ranged from 0 to 67%. Across the dataset, 3.86% of cells had missing data and 87.88% of cases had nonmissing data. At this stage in the analysis, we allowed all cases with less than 90% missing to continue to the scoring stage. Guided by Parent’s <span class="citation">(<a href="#ref-parent_handling_2013">2013</a>)</span> AIA approach, scales with three items were scored if at least two items were non-missing; the scale with four items was scored if it at least three non-missing items; and the scale with six items was scored if it had at least five non-missing items.</p>
</blockquote>
</blockquote>
<blockquote>
<blockquote>
<p>Across the 66 cases for which the scoring protocol was applied, missingness ranged from 0 to 67%. After eliminating cases with greater than 20% missing, the dataset analyzed included 61 cases. In this dataset we had less than 1% (0.55%) missing across the data set; 97% of the rows had nonmissing data.</p>
</blockquote>
</blockquote>
</div>
<div id="practice-problems-1" class="section level2 hasAnchor" number="2.11">
<h2><span class="header-section-number">2.11</span> Practice Problems<a href="score.html#practice-problems-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The three problems described below are designed to be continuations from the previous chapter (Scrubbing). You will likely encounter challenges that were not covered in this chapter. Search for and try out solutions, knowing that there are multiple paths through the analysis. The overall notion of the suggestions for practice are to (a) properly format three variables, (b) evaluate item-level missingness, (c) score any scales, (c) evaluate scale-level missingness, (d) provide an APA-style write-up, and (e) explain it to someone.</p>
<div id="problem-1-reworking-the-chapter-problem" class="section level3 hasAnchor" number="2.11.1">
<h3><span class="header-section-number">2.11.1</span> Problem #1: Reworking the Chapter Problem<a href="score.html#problem-1-reworking-the-chapter-problem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you chose this option in the prior chapter, you imported the data from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, and wrote up the preliminary results.</p>
</div>
<div id="problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1" class="section level3 hasAnchor" number="2.11.2">
<h3><span class="header-section-number">2.11.2</span> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables<a href="score.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you chose this option in the prior chapter, you chose a minimum of three variables from the <em>Rate-a-Recent-Course</em> survey to include in a simple statistical model. You imported the dat from Qualtrics, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest and wrote up the preliminary results.</p>
</div>
<div id="problem-3-other-data-1" class="section level3 hasAnchor" number="2.11.3">
<h3><span class="header-section-number">2.11.3</span> Problem #3: Other data<a href="score.html#problem-3-other-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you chose this option in the prior chapter, you used raw data that was available to you. You imported it into R, applied inclusion/exclusion criteria, renamed variables, downsized the df to the variables of interest, and wrote up the preliminary results.</p>
</div>
<div id="grading-rubric-1" class="section level3 hasAnchor" number="2.11.4">
<h3><span class="header-section-number">2.11.4</span> Grading Rubric<a href="score.html#grading-rubric-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="75%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center">Points Possible</th>
<th align="center">Points Earned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Proper formatting of the items(s) in your first predictor variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Proper formatting of the items(s) in your second predictor variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Proper formatting of the items(s) your third predictor variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Proper formatting of your dependent variable</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">4. Evaluate and interpret item-level missingness</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">5. Score any scales/subscales</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Represent your work in an APA-style write-up (added to the writeup in the previous chapter)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">8. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="center">45</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
<p>A <em>homeworked example</em> for the Scrubbing, Scoring, and DataDx lessons (combined) follows the <a href="DataDx.html#DataDx">Data Dx</a> lesson.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-bollen_perceived_1990" class="csl-entry">
Bollen, K. A., &amp; Hoyle, R. H. (1990). Perceived cohesion: <span>A</span> conceptual and empirical examination. <em>Social Forces</em>, <em>69</em>(2), 479–504. <a href="https://doi.org/10.2307/2579670">https://doi.org/10.2307/2579670</a>
</div>
<div id="ref-enders_applied_2010" class="csl-entry">
Enders, C. K. (2010). <em>Applied missing data analysis</em>. Guilford Press.
</div>
<div id="ref-hurtado_effects_1997" class="csl-entry">
Hurtado, S., &amp; Carter, D. F. (1997). Effects of college transition and perceptions of the campus racial climate on <span>Latino</span> college students’ sense of belonging. <em>Sociology of Education</em>, <em>70</em>, 324–345. <a href="https://doi.org/10.2307/2673270">https://doi.org/10.2307/2673270</a>
</div>
<div id="ref-kline_principles_2016" class="csl-entry">
Kline, R. B. (2016b). <em>Principles and practice of structural equation modeling</em> (4th ed.). Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4000663</a>
</div>
<div id="ref-little_statistical_2002" class="csl-entry">
Little, R. J. A., &amp; Rubin, D. B. (2002). <em>Statistical analysis with missing data</em> (Second edition.). Wiley. <a href="http://site.ebrary.com/id/10921256">http://site.ebrary.com/id/10921256</a>
</div>
<div id="ref-parent_handling_2013" class="csl-entry">
Parent, M. C. (2013). Handling item-level missing data: <span>Simpler</span> is just as good. <em>The Counseling Psychologist</em>, <em>41</em>(4), 568–600. <a href="https://doi.org/10.1177/0011000012445176">https://doi.org/10.1177/0011000012445176</a>
</div>
<div id="ref-szymanski_perceptions_2020" class="csl-entry">
Szymanski, D. M., &amp; Bissonette, D. (2020). Perceptions of the <span>LGBTQ</span> <span>College</span> <span>Campus</span> <span>Climate</span> <span>Scale</span>: <span>Development</span> and psychometric evaluation. <em>Journal of Homosexuality</em>, <em>67</em>(10), 1412–1428. <a href="https://doi.org/10.1080/00918369.2019.1591788">https://doi.org/10.1080/00918369.2019.1591788</a>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scrub.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="DataDx.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ReC_MultMod.pdf", "ReC_MultMod.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
