<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Simple Mediation | ReCentering Psych Stats: Multivariate Modeling</title>
  <meta name="description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Simple Mediation | ReCentering Psych Stats: Multivariate Modeling" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://lhbikos.github.io/ReC_MultivModel/images/ReC_multivariate_bkcvr.png" />
  <meta property="og:description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="github-repo" content="lhbikos/extRas" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Simple Mediation | ReCentering Psych Stats: Multivariate Modeling" />
  
  <meta name="twitter:description" content="“Multivariate Modeling” is a mini-volume in the ReCentering Psych Stats series. The first portion of the book includes lessons on scrubbing and scoring data, data diagnostics (including managing missingness), and multiple imputation. The second portion of the book introduces conditional process analysis, using the R package lavaan. Lessons include simple mediation, complex mediation, simple moderation, and moderated mediation." />
  <meta name="twitter:image" content="https://lhbikos.github.io/ReC_MultivModel/images/ReC_multivariate_bkcvr.png" />

<meta name="author" content="Lynette H. Bikos, PhD, ABPP" />


<meta name="date" content="2023-09-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="MED.html"/>
<link rel="next" href="CompMed.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ReCentering Psych Stats</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>BOOK COVER</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>PREFACE</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#copyright-with-open-access"><i class="fa fa-check"></i>Copyright with Open Access</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>ACKNOWLEDGEMENTS</a></li>
<li class="chapter" data-level="" data-path="dataprep.html"><a href="dataprep.html"><i class="fa fa-check"></i>DATA PREP</a></li>
<li class="chapter" data-level="1" data-path="scrub.html"><a href="scrub.html"><i class="fa fa-check"></i><b>1</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="1.1" data-path="scrub.html"><a href="scrub.html#navigating-this-lesson"><i class="fa fa-check"></i><b>1.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="scrub.html"><a href="scrub.html#learning-objectives"><i class="fa fa-check"></i><b>1.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.1.2" data-path="scrub.html"><a href="scrub.html#planning-for-practice"><i class="fa fa-check"></i><b>1.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="1.1.3" data-path="scrub.html"><a href="scrub.html#readings-resources"><i class="fa fa-check"></i><b>1.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="1.1.4" data-path="scrub.html"><a href="scrub.html#packages"><i class="fa fa-check"></i><b>1.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="scrub.html"><a href="scrub.html#workflow-for-scrubbing"><i class="fa fa-check"></i><b>1.2</b> Workflow for Scrubbing</a></li>
<li class="chapter" data-level="1.3" data-path="scrub.html"><a href="scrub.html#research-vignette"><i class="fa fa-check"></i><b>1.3</b> Research Vignette</a></li>
<li class="chapter" data-level="1.4" data-path="scrub.html"><a href="scrub.html#working-the-problem"><i class="fa fa-check"></i><b>1.4</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="scrub.html"><a href="scrub.html#intravenous-qualtrics"><i class="fa fa-check"></i><b>1.4.1</b> intRavenous Qualtrics</a></li>
<li class="chapter" data-level="1.4.2" data-path="scrub.html"><a href="scrub.html#about-the-rate-a-recent-course-survey"><i class="fa fa-check"></i><b>1.4.2</b> About the <em>Rate-a-Recent-Course</em> Survey</a></li>
<li class="chapter" data-level="1.4.3" data-path="scrub.html"><a href="scrub.html#the-codebook"><i class="fa fa-check"></i><b>1.4.3</b> The Codebook</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="scrub.html"><a href="scrub.html#scrubbing"><i class="fa fa-check"></i><b>1.5</b> Scrubbing</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="scrub.html"><a href="scrub.html#tools-for-data-manipulations"><i class="fa fa-check"></i><b>1.5.1</b> Tools for Data Manipulations</a></li>
<li class="chapter" data-level="1.5.2" data-path="scrub.html"><a href="scrub.html#inclusion-and-exclusion-criteria"><i class="fa fa-check"></i><b>1.5.2</b> Inclusion and Exclusion Criteria</a></li>
<li class="chapter" data-level="1.5.3" data-path="scrub.html"><a href="scrub.html#renaming-variables"><i class="fa fa-check"></i><b>1.5.3</b> Renaming Variables</a></li>
<li class="chapter" data-level="1.5.4" data-path="scrub.html"><a href="scrub.html#downsizing-the-dataframe"><i class="fa fa-check"></i><b>1.5.4</b> Downsizing the Dataframe</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="scrub.html"><a href="scrub.html#toward-the-apa-style-write-up"><i class="fa fa-check"></i><b>1.6</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="scrub.html"><a href="scrub.html#methodprocedure"><i class="fa fa-check"></i><b>1.6.1</b> Method/Procedure</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scrub.html"><a href="scrub.html#practice-problems"><i class="fa fa-check"></i><b>1.7</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="scrub.html"><a href="scrub.html#problem-1-rework-the-chapter-problem"><i class="fa fa-check"></i><b>1.7.1</b> Problem #1: Rework the Chapter Problem</a></li>
<li class="chapter" data-level="1.7.2" data-path="scrub.html"><a href="scrub.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables"><i class="fa fa-check"></i><b>1.7.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="1.7.3" data-path="scrub.html"><a href="scrub.html#problem-3-other-data"><i class="fa fa-check"></i><b>1.7.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="1.7.4" data-path="scrub.html"><a href="scrub.html#grading-rubric"><i class="fa fa-check"></i><b>1.7.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="scrub.html"><a href="scrub.html#bonus-track"><i class="fa fa-check"></i><b>1.8</b> Bonus Track:</a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="scrub.html"><a href="scrub.html#importing-data-from-an-exported-qualtrics-.csv-file"><i class="fa fa-check"></i><b>1.8.1</b> Importing data from an exported Qualtrics .csv file</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="score.html"><a href="score.html"><i class="fa fa-check"></i><b>2</b> Scoring</a>
<ul>
<li class="chapter" data-level="2.1" data-path="score.html"><a href="score.html#navigating-this-lesson-1"><i class="fa fa-check"></i><b>2.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="score.html"><a href="score.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="score.html"><a href="score.html#planning-for-practice-1"><i class="fa fa-check"></i><b>2.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="2.1.3" data-path="score.html"><a href="score.html#readings-resources-1"><i class="fa fa-check"></i><b>2.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="2.1.4" data-path="score.html"><a href="score.html#packages-1"><i class="fa fa-check"></i><b>2.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="score.html"><a href="score.html#workflow-for-scoring"><i class="fa fa-check"></i><b>2.2</b> Workflow for Scoring</a></li>
<li class="chapter" data-level="2.3" data-path="score.html"><a href="score.html#research-vignette-1"><i class="fa fa-check"></i><b>2.3</b> Research Vignette</a></li>
<li class="chapter" data-level="2.4" data-path="score.html"><a href="score.html#on-missing-data"><i class="fa fa-check"></i><b>2.4</b> On Missing Data</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="score.html"><a href="score.html#data-loss-mechanisms"><i class="fa fa-check"></i><b>2.4.1</b> Data Loss Mechanisms</a></li>
<li class="chapter" data-level="2.4.2" data-path="score.html"><a href="score.html#diagnosing-missing-data-mechanisms"><i class="fa fa-check"></i><b>2.4.2</b> Diagnosing Missing Data Mechanisms</a></li>
<li class="chapter" data-level="2.4.3" data-path="score.html"><a href="score.html#managing-missing-data"><i class="fa fa-check"></i><b>2.4.3</b> Managing Missing Data</a></li>
<li class="chapter" data-level="2.4.4" data-path="score.html"><a href="score.html#available-information-analysis-aia"><i class="fa fa-check"></i><b>2.4.4</b> Available Information Analysis (AIA)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="score.html"><a href="score.html#working-the-problem-1"><i class="fa fa-check"></i><b>2.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="score.html"><a href="score.html#missing-data-analysis-whole-df-and-item-level"><i class="fa fa-check"></i><b>2.5.1</b> Missing Data Analysis: Whole df and Item level</a></li>
<li class="chapter" data-level="2.5.2" data-path="score.html"><a href="score.html#analyzing-missing-data-patterns"><i class="fa fa-check"></i><b>2.5.2</b> Analyzing Missing Data Patterns</a></li>
<li class="chapter" data-level="2.5.3" data-path="score.html"><a href="score.html#can-we-identify-the-missing-mechanisms"><i class="fa fa-check"></i><b>2.5.3</b> Can we identify the missing mechanisms?</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="score.html"><a href="score.html#scoring"><i class="fa fa-check"></i><b>2.6</b> Scoring</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="score.html"><a href="score.html#reverse-scoring"><i class="fa fa-check"></i><b>2.6.1</b> Reverse scoring</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="score.html"><a href="score.html#missing-analysis-scale-level"><i class="fa fa-check"></i><b>2.7</b> Missing Analysis: Scale level</a></li>
<li class="chapter" data-level="2.8" data-path="score.html"><a href="score.html#revisiting-missing-analysis-at-the-scale-level"><i class="fa fa-check"></i><b>2.8</b> Revisiting Missing Analysis at the Scale Level</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="score.html"><a href="score.html#scale-level-patterns-of-missing-data"><i class="fa fa-check"></i><b>2.8.1</b> Scale Level: Patterns of Missing Data</a></li>
<li class="chapter" data-level="2.8.2" data-path="score.html"><a href="score.html#r-eady-for-analysis"><i class="fa fa-check"></i><b>2.8.2</b> R-eady for Analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="score.html"><a href="score.html#the-apa-style-write-up"><i class="fa fa-check"></i><b>2.9</b> The APA Style Write-Up</a></li>
<li class="chapter" data-level="2.10" data-path="score.html"><a href="score.html#results"><i class="fa fa-check"></i><b>2.10</b> Results</a></li>
<li class="chapter" data-level="2.11" data-path="score.html"><a href="score.html#practice-problems-1"><i class="fa fa-check"></i><b>2.11</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="2.11.1" data-path="score.html"><a href="score.html#problem-1-reworking-the-chapter-problem"><i class="fa fa-check"></i><b>2.11.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="2.11.2" data-path="score.html"><a href="score.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-1"><i class="fa fa-check"></i><b>2.11.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="2.11.3" data-path="score.html"><a href="score.html#problem-3-other-data-1"><i class="fa fa-check"></i><b>2.11.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="2.11.4" data-path="score.html"><a href="score.html#grading-rubric-1"><i class="fa fa-check"></i><b>2.11.4</b> Grading Rubric</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="DataDx.html"><a href="DataDx.html"><i class="fa fa-check"></i><b>3</b> Data Dx</a>
<ul>
<li class="chapter" data-level="3.1" data-path="DataDx.html"><a href="DataDx.html#navigating-this-lesson-2"><i class="fa fa-check"></i><b>3.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="DataDx.html"><a href="DataDx.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="DataDx.html"><a href="DataDx.html#planning-for-practice-2"><i class="fa fa-check"></i><b>3.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="3.1.3" data-path="DataDx.html"><a href="DataDx.html#readings-resources-2"><i class="fa fa-check"></i><b>3.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="3.1.4" data-path="DataDx.html"><a href="DataDx.html#packages-2"><i class="fa fa-check"></i><b>3.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="DataDx.html"><a href="DataDx.html#workflow-for-preliminary-data-diagnostics"><i class="fa fa-check"></i><b>3.2</b> Workflow for Preliminary Data Diagnostics</a></li>
<li class="chapter" data-level="3.3" data-path="DataDx.html"><a href="DataDx.html#research-vignette-2"><i class="fa fa-check"></i><b>3.3</b> Research Vignette</a></li>
<li class="chapter" data-level="3.4" data-path="DataDx.html"><a href="DataDx.html#internal-consistency-of-scalessubscales"><i class="fa fa-check"></i><b>3.4</b> Internal Consistency of Scales/Subscales</a></li>
<li class="chapter" data-level="3.5" data-path="DataDx.html"><a href="DataDx.html#distributional-characteristics-of-the-variables"><i class="fa fa-check"></i><b>3.5</b> Distributional Characteristics of the Variables</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="DataDx.html"><a href="DataDx.html#evaluating-univariate-normality"><i class="fa fa-check"></i><b>3.5.1</b> Evaluating Univariate Normality</a></li>
<li class="chapter" data-level="3.5.2" data-path="DataDx.html"><a href="DataDx.html#pairs-panels"><i class="fa fa-check"></i><b>3.5.2</b> Pairs Panels</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="DataDx.html"><a href="DataDx.html#evaluating-multivariate-normality"><i class="fa fa-check"></i><b>3.6</b> Evaluating Multivariate Normality</a></li>
<li class="chapter" data-level="3.7" data-path="DataDx.html"><a href="DataDx.html#a-few-words-on-transformations"><i class="fa fa-check"></i><b>3.7</b> A Few Words on Transformations</a></li>
<li class="chapter" data-level="3.8" data-path="DataDx.html"><a href="DataDx.html#the-apa-style-write-up-1"><i class="fa fa-check"></i><b>3.8</b> The APA Style Write-Up</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="DataDx.html"><a href="DataDx.html#data-diagnostics"><i class="fa fa-check"></i><b>3.8.1</b> Data Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="DataDx.html"><a href="DataDx.html#a-quick-regression-of-our-research-vignette"><i class="fa fa-check"></i><b>3.9</b> A Quick Regression of our Research Vignette</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="DataDx.html"><a href="DataDx.html#results-1"><i class="fa fa-check"></i><b>3.9.1</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="DataDx.html"><a href="DataDx.html#practice-problems-2"><i class="fa fa-check"></i><b>3.10</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="DataDx.html"><a href="DataDx.html#problem-1-reworking-the-chapter-problem-1"><i class="fa fa-check"></i><b>3.10.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="3.10.2" data-path="DataDx.html"><a href="DataDx.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-2"><i class="fa fa-check"></i><b>3.10.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="3.10.3" data-path="DataDx.html"><a href="DataDx.html#problem-3-other-data-2"><i class="fa fa-check"></i><b>3.10.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="3.10.4" data-path="DataDx.html"><a href="DataDx.html#grading-rubric-2"><i class="fa fa-check"></i><b>3.10.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="DataDx.html"><a href="DataDx.html#homeworked-example"><i class="fa fa-check"></i><b>3.11</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="DataDx.html"><a href="DataDx.html#scrubbing-1"><i class="fa fa-check"></i><b>3.11.1</b> Scrubbing</a></li>
<li class="chapter" data-level="3.11.2" data-path="DataDx.html"><a href="DataDx.html#scoring-1"><i class="fa fa-check"></i><b>3.11.2</b> Scoring</a></li>
<li class="chapter" data-level="3.11.3" data-path="DataDx.html"><a href="DataDx.html#data-dx"><i class="fa fa-check"></i><b>3.11.3</b> Data Dx</a></li>
<li class="chapter" data-level="3.11.4" data-path="DataDx.html"><a href="DataDx.html#results-2"><i class="fa fa-check"></i><b>3.11.4</b> Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multimp.html"><a href="multimp.html"><i class="fa fa-check"></i><b>4</b> Multiple Imputation (A Brief Demo)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multimp.html"><a href="multimp.html#navigating-this-lesson-3"><i class="fa fa-check"></i><b>4.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="multimp.html"><a href="multimp.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.1.2" data-path="multimp.html"><a href="multimp.html#planning-for-practice-3"><i class="fa fa-check"></i><b>4.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="4.1.3" data-path="multimp.html"><a href="multimp.html#readings-resources-3"><i class="fa fa-check"></i><b>4.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="4.1.4" data-path="multimp.html"><a href="multimp.html#packages-3"><i class="fa fa-check"></i><b>4.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="multimp.html"><a href="multimp.html#workflow-for-multiple-imputation"><i class="fa fa-check"></i><b>4.2</b> Workflow for Multiple Imputation</a></li>
<li class="chapter" data-level="4.3" data-path="multimp.html"><a href="multimp.html#research-vignette-3"><i class="fa fa-check"></i><b>4.3</b> Research Vignette</a></li>
<li class="chapter" data-level="4.4" data-path="multimp.html"><a href="multimp.html#multiple-imputation-a-super-brief-review"><i class="fa fa-check"></i><b>4.4</b> Multiple Imputation – a Super Brief Review</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="multimp.html"><a href="multimp.html#steps-in-multiple-imputation"><i class="fa fa-check"></i><b>4.4.1</b> Steps in Multiple Imputation</a></li>
<li class="chapter" data-level="4.4.2" data-path="multimp.html"><a href="multimp.html#statistical-approaches-to-multiple-imputation"><i class="fa fa-check"></i><b>4.4.2</b> Statistical Approaches to Multiple Imputation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="multimp.html"><a href="multimp.html#working-the-problem-2"><i class="fa fa-check"></i><b>4.5</b> Working the Problem</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="multimp.html"><a href="multimp.html#selecting-and-formatting-variables"><i class="fa fa-check"></i><b>4.5.1</b> Selecting and Formatting Variables</a></li>
<li class="chapter" data-level="4.5.2" data-path="multimp.html"><a href="multimp.html#creating-composite-variables"><i class="fa fa-check"></i><b>4.5.2</b> Creating Composite Variables</a></li>
<li class="chapter" data-level="4.5.3" data-path="multimp.html"><a href="multimp.html#the-multiple-imputation"><i class="fa fa-check"></i><b>4.5.3</b> The Multiple Imputation</a></li>
<li class="chapter" data-level="4.5.4" data-path="multimp.html"><a href="multimp.html#creating-scale-scores"><i class="fa fa-check"></i><b>4.5.4</b> Creating Scale Scores</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="multimp.html"><a href="multimp.html#multiple-regression-with-multiply-imputed-data"><i class="fa fa-check"></i><b>4.6</b> Multiple Regression with Multiply Imputed Data</a></li>
<li class="chapter" data-level="4.7" data-path="multimp.html"><a href="multimp.html#toward-the-apa-style-write-up-1"><i class="fa fa-check"></i><b>4.7</b> Toward the APA Style Write-up</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="multimp.html"><a href="multimp.html#methoddata-diagnostics"><i class="fa fa-check"></i><b>4.7.1</b> Method/Data Diagnostics</a></li>
<li class="chapter" data-level="4.7.2" data-path="multimp.html"><a href="multimp.html#results-3"><i class="fa fa-check"></i><b>4.7.2</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="multimp.html"><a href="multimp.html#multiple-imputation-considerations"><i class="fa fa-check"></i><b>4.8</b> Multiple imputation considerations</a></li>
<li class="chapter" data-level="4.9" data-path="multimp.html"><a href="multimp.html#practice-problems-3"><i class="fa fa-check"></i><b>4.9</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="multimp.html"><a href="multimp.html#problem-1-reworking-the-chapter-problem-2"><i class="fa fa-check"></i><b>4.9.1</b> Problem #1: Reworking the Chapter Problem</a></li>
<li class="chapter" data-level="4.9.2" data-path="multimp.html"><a href="multimp.html#problem-2-use-the-rate-a-recent-course-survey-choosing-different-variables-3"><i class="fa fa-check"></i><b>4.9.2</b> Problem #2: Use the <em>Rate-a-Recent-Course</em> Survey, Choosing Different Variables</a></li>
<li class="chapter" data-level="4.9.3" data-path="multimp.html"><a href="multimp.html#problem-3-other-data-3"><i class="fa fa-check"></i><b>4.9.3</b> Problem #3: Other data</a></li>
<li class="chapter" data-level="4.9.4" data-path="multimp.html"><a href="multimp.html#grading-rubric-3"><i class="fa fa-check"></i><b>4.9.4</b> Grading Rubric</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="multimp.html"><a href="multimp.html#homeworked-example-1"><i class="fa fa-check"></i><b>4.10</b> Homeworked Example</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="multimp.html"><a href="multimp.html#scrubbing-2"><i class="fa fa-check"></i><b>4.10.1</b> Scrubbing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="MED.html"><a href="MED.html"><i class="fa fa-check"></i>MEDIATION</a></li>
<li class="chapter" data-level="5" data-path="SimpleMed.html"><a href="SimpleMed.html"><i class="fa fa-check"></i><b>5</b> Simple Mediation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="SimpleMed.html"><a href="SimpleMed.html#navigating-this-lesson-4"><i class="fa fa-check"></i><b>5.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="SimpleMed.html"><a href="SimpleMed.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="SimpleMed.html"><a href="SimpleMed.html#planning-for-practice-4"><i class="fa fa-check"></i><b>5.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="5.1.3" data-path="SimpleMed.html"><a href="SimpleMed.html#readings-resources-4"><i class="fa fa-check"></i><b>5.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="5.1.4" data-path="SimpleMed.html"><a href="SimpleMed.html#packages-4"><i class="fa fa-check"></i><b>5.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="SimpleMed.html"><a href="SimpleMed.html#estimating-indirect-effects-the-analytic-approach-often-termed-mediation"><i class="fa fa-check"></i><b>5.2</b> Estimating Indirect Effects (the analytic approach often termed <em>mediation</em>)</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="SimpleMed.html"><a href="SimpleMed.html#the-definitional-and-conceptual"><i class="fa fa-check"></i><b>5.2.1</b> The definitional and conceptual</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="SimpleMed.html"><a href="SimpleMed.html#workflow-for-simple-mediation"><i class="fa fa-check"></i><b>5.3</b> Workflow for Simple Mediation</a></li>
<li class="chapter" data-level="5.4" data-path="SimpleMed.html"><a href="SimpleMed.html#simple-mediation-in-lavaan-a-focus-on-the-mechanics"><i class="fa fa-check"></i><b>5.4</b> Simple Mediation in <em>lavaan</em>: A focus on the mechanics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="SimpleMed.html"><a href="SimpleMed.html#simulate-fake-data"><i class="fa fa-check"></i><b>5.4.1</b> Simulate Fake Data</a></li>
<li class="chapter" data-level="5.4.2" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-mediation-model"><i class="fa fa-check"></i><b>5.4.2</b> Specify Mediation Model</a></li>
<li class="chapter" data-level="5.4.3" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output"><i class="fa fa-check"></i><b>5.4.3</b> Interpret the Output</a></li>
<li class="chapter" data-level="5.4.4" data-path="SimpleMed.html"><a href="SimpleMed.html#a-table-and-a-figure"><i class="fa fa-check"></i><b>5.4.4</b> A Table and a Figure</a></li>
<li class="chapter" data-level="5.4.5" data-path="SimpleMed.html"><a href="SimpleMed.html#results-4"><i class="fa fa-check"></i><b>5.4.5</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="SimpleMed.html"><a href="SimpleMed.html#research-vignette-4"><i class="fa fa-check"></i><b>5.5</b> Research Vignette</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="SimpleMed.html"><a href="SimpleMed.html#simulate-data-from-the-journal-article"><i class="fa fa-check"></i><b>5.5.1</b> Simulate Data from the Journal Article</a></li>
<li class="chapter" data-level="5.5.2" data-path="SimpleMed.html"><a href="SimpleMed.html#specify-the-model-in-lavaan"><i class="fa fa-check"></i><b>5.5.2</b> Specify the Model in <em>lavaan</em></a></li>
<li class="chapter" data-level="5.5.3" data-path="SimpleMed.html"><a href="SimpleMed.html#interpret-the-output-1"><i class="fa fa-check"></i><b>5.5.3</b> Interpret the Output</a></li>
<li class="chapter" data-level="5.5.4" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table"><i class="fa fa-check"></i><b>5.5.4</b> A Figure and a Table</a></li>
<li class="chapter" data-level="5.5.5" data-path="SimpleMed.html"><a href="SimpleMed.html#results-5"><i class="fa fa-check"></i><b>5.5.5</b> Results</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="SimpleMed.html"><a href="SimpleMed.html#considering-covariates"><i class="fa fa-check"></i><b>5.6</b> Considering Covariates</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="SimpleMed.html"><a href="SimpleMed.html#a-figure-and-a-table-1"><i class="fa fa-check"></i><b>5.6.1</b> A Figure and a Table</a></li>
<li class="chapter" data-level="5.6.2" data-path="SimpleMed.html"><a href="SimpleMed.html#apa-style-write-up"><i class="fa fa-check"></i><b>5.6.2</b> APA Style Write-up</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="SimpleMed.html"><a href="SimpleMed.html#residual-and-related-questions"><i class="fa fa-check"></i><b>5.7</b> Residual and Related Questions…</a></li>
<li class="chapter" data-level="5.8" data-path="SimpleMed.html"><a href="SimpleMed.html#practice-problems-4"><i class="fa fa-check"></i><b>5.8</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="5.8.1" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed"><i class="fa fa-check"></i><b>5.8.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="5.8.2" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables"><i class="fa fa-check"></i><b>5.8.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="5.8.3" data-path="SimpleMed.html"><a href="SimpleMed.html#problem-3-use-other-data-that-is-available-to-you"><i class="fa fa-check"></i><b>5.8.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="CompMed.html"><a href="CompMed.html"><i class="fa fa-check"></i><b>6</b> Complex Mediation</a>
<ul>
<li class="chapter" data-level="6.1" data-path="CompMed.html"><a href="CompMed.html#navigating-this-lesson-5"><i class="fa fa-check"></i><b>6.1</b> Navigating this Lesson</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="CompMed.html"><a href="CompMed.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.1.2" data-path="CompMed.html"><a href="CompMed.html#planning-for-practice-5"><i class="fa fa-check"></i><b>6.1.2</b> Planning for Practice</a></li>
<li class="chapter" data-level="6.1.3" data-path="CompMed.html"><a href="CompMed.html#readings-resources-5"><i class="fa fa-check"></i><b>6.1.3</b> Readings &amp; Resources</a></li>
<li class="chapter" data-level="6.1.4" data-path="CompMed.html"><a href="CompMed.html#packages-5"><i class="fa fa-check"></i><b>6.1.4</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="CompMed.html"><a href="CompMed.html#complex-mediation"><i class="fa fa-check"></i><b>6.2</b> Complex Mediation</a></li>
<li class="chapter" data-level="6.3" data-path="CompMed.html"><a href="CompMed.html#parallel-mediation"><i class="fa fa-check"></i><b>6.3</b> Parallel Mediation</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="CompMed.html"><a href="CompMed.html#a-mechanical-example"><i class="fa fa-check"></i><b>6.3.1</b> A Mechanical Example</a></li>
<li class="chapter" data-level="6.3.2" data-path="CompMed.html"><a href="CompMed.html#research-vignette-5"><i class="fa fa-check"></i><b>6.3.2</b> Research Vignette</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="CompMed.html"><a href="CompMed.html#serial-multiple-mediator-model"><i class="fa fa-check"></i><b>6.4</b> Serial Multiple Mediator Model</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="CompMed.html"><a href="CompMed.html#we-stick-with-the-lewis-et-al.--lewis_applying_2017-example-but-modify-it."><i class="fa fa-check"></i><b>6.4.1</b> We stick with the Lewis et al. <span class="citation">(2017)</span> example, but modify it.</a></li>
<li class="chapter" data-level="6.4.2" data-path="CompMed.html"><a href="CompMed.html#specify-the-lavaan-model"><i class="fa fa-check"></i><b>6.4.2</b> Specify the <em>lavaan</em> model</a></li>
<li class="chapter" data-level="6.4.3" data-path="CompMed.html"><a href="CompMed.html#figures-and-tables-2"><i class="fa fa-check"></i><b>6.4.3</b> Figures and Tables</a></li>
<li class="chapter" data-level="6.4.4" data-path="CompMed.html"><a href="CompMed.html#apa-style-writeup-2"><i class="fa fa-check"></i><b>6.4.4</b> APA Style Writeup</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="CompMed.html"><a href="CompMed.html#troubleshooting-and-faqs"><i class="fa fa-check"></i><b>6.5</b> Troubleshooting and FAQs</a></li>
<li class="chapter" data-level="6.6" data-path="CompMed.html"><a href="CompMed.html#practice-problems-5"><i class="fa fa-check"></i><b>6.6</b> Practice Problems</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="CompMed.html"><a href="CompMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed-1"><i class="fa fa-check"></i><b>6.6.1</b> Problem #1: Rework the research vignette as demonstrated, but change the random seed</a></li>
<li class="chapter" data-level="6.6.2" data-path="CompMed.html"><a href="CompMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables-1"><i class="fa fa-check"></i><b>6.6.2</b> Problem #2: Rework the research vignette, but swap one or more variables</a></li>
<li class="chapter" data-level="6.6.3" data-path="CompMed.html"><a href="CompMed.html#problem-3-use-other-data-that-is-available-to-you-1"><i class="fa fa-check"></i><b>6.6.3</b> Problem #3: Use other data that is available to you</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ReCentering Psych Stats: Multivariate Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="SimpleMed" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Simple Mediation<a href="SimpleMed.html#SimpleMed" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><a href="https://spu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?pid=7ffb03e6-b34b-4e0b-8f10-ad080180b069">Screencasted Lecture Link</a></p>
<p>The focus of this lecture is to estimate indirect effects (aka “mediation”). We examine the logic/design required to support the argument that <em>mediation</em> is the <em>mechanism</em> that explains the X –&gt; Y relationship. We also work three examples (one with covariates).</p>
<p>At the outset, please note that although I rely heavily on Hayes <span class="citation">(<a href="#ref-hayes_introduction_2018">2018</a>)</span> text and materials, I am using the R package <em>lavaan</em> in these chapters. Very recently, Hayes has introduced a <a href="https://www.processmacro.org/index.html">PROCESS macro for R</a>. Because I am not yet up-to-speed on using this macro (it is not a typical R package) and because we will use <em>lavaan</em> for confirmatory factor analysis and structural equation modeling, I have chosen to utilize the <em>lavaan</em> package. A substantial difference is that the PROCESS macros use ordinary least squares and <em>lavaan</em> uses maximum likelihood estimators.</p>
<div id="navigating-this-lesson-4" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Navigating this Lesson<a href="SimpleMed.html#navigating-this-lesson-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There is about 1 hour and 10 minutes of lecture. If you work through the materials with me it would be plan for an additional 1.5 hours.</p>
<p>While the majority of R objects and data you will need are created within the R script that sources the chapter, ocasionally there are some that cannot be created from within the R framework. Additionally, sometimes links fail. All original materials are provided at the <a href="https://github.com/lhbikos/ReC_MultivModel">Github site</a> that hosts the book. More detailed guidelines for ways to access all these materials are provided in the OER’s <a href="#ReCintro">introduction</a></p>
<div id="learning-objectives-4" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Learning Objectives<a href="SimpleMed.html#learning-objectives-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Learning objectives from this lecture include the following:</p>
<ul>
<li>Define mediation and indirect effect.</li>
<li>Distinguish the role of a mediating variable from independent variables, covariates, and moderators.</li>
<li>Identify the conditions upon which there can be justification to support the presence of a mediated effect.</li>
<li>Articulate the arguments for and against using the term, “mediation.”</li>
<li>Using the R package <em>lavaan</em>,
<ul>
<li>specify a model with indirect effects,</li>
<li>identify and interpret B weights, <em>p</em> values, and <em>CIs</em> for total, direct, and indirect effects,</li>
<li>calculate the total effects of X and M on Y,</li>
<li>identify the proportion of variance accounted for in predicting M and Y.</li>
</ul></li>
<li>Hand calculate the values of an indirect, direct, and total effects from statistical output or a figure (just the <span class="math inline">\(B\)</span> or <span class="math inline">\(\beta\)</span>, not the significance level)</li>
</ul>
</div>
<div id="planning-for-practice-4" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Planning for Practice<a href="SimpleMed.html#planning-for-practice-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following suggestions for practice will involve specifying, testing, and interpreting a model with a single indirect effect (mediator).</p>
<ul>
<li>Rework the problem in the chapter by changing the random seed in the code that simulates the data. This should provide minor changes to the data, but the results will likely be very similar.</li>
<li>There are a number of variables in the dataset and there were a handful of simple mediations conducted in the journal article that sources the research vignette. Swap out one or more variables in the model of simple mediation and compare your solution to the one in the chapter and/or the research article.</li>
<li>Conduct a simple mediation with data to which you have access. This could include data you simulate on your own or from a published article.</li>
</ul>
</div>
<div id="readings-resources-4" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Readings &amp; Resources<a href="SimpleMed.html#readings-resources-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In preparing this chapter, I drew heavily from the following resource(s). Other resources are cited (when possible, linked) in the text with complete citations in the reference list.</p>
<ul>
<li>Hayes, A. F. (2018). <em>Introduction to mediation, moderation, and conditional process anlaysis: A regression-based approach</em>. New York, NY: Guilford Press. Available as an ebook from the SPU library: <a href="https://ebookcentral-proquest-com.ezproxy.spu.edu/lib/spu/detail.action?docID=5109647" class="uri">https://ebookcentral-proquest-com.ezproxy.spu.edu/lib/spu/detail.action?docID=5109647</a>
<ul>
<li><strong>Chapter 3, Simple mediation</strong>: Hayes’ text is another great example of a teaching tool that is accessible at both procedural and conceptual levels. I especially appreciate his attention to the controversies (even those directed toward his work). We deviate from his text in that we are not using the PROCESS macro…and I’ll address those concerns in the lecture.</li>
<li><strong>Chapter 4, Causality and confounds</strong>: A great chapter that addresses “What happened to Baron &amp; Kenny”; partial v complete mediation; and conditions required for claims of causality. Procedurally, our focus in this chapter is on the role of covariates.</li>
<li><strong>Appendix A: Using Process</strong>: An essential tool for PROCESS users because, even when we are in the R environment, this is the “idea book.” That is, the place where all the path models are presented in figures.</li>
</ul></li>
<li>Kim, P. Y., Kendall, D. L., &amp; Cheon, H.-S. (2017). Racial microaggressions, cultural mistrust, and mental health outcomes among Asian American college students. <em>American Journal of Orthopsychiatry, 87</em>(6), 663–670. <a href="https://doi-org.ezproxy.spu.edu/10.1037/ort0000203" class="uri">https://doi-org.ezproxy.spu.edu/10.1037/ort0000203</a></li>
</ul>
</div>
<div id="packages-4" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> Packages<a href="SimpleMed.html#packages-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The script below will (a) check to see if the following packages are installed on your computer and, if not (b) install them.</p>
<!-- TODO: Build out this section. -->
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="SimpleMed.html#cb236-1" tabindex="-1"></a><span class="co">#will install the package if not already installed</span></span>
<span id="cb236-2"><a href="SimpleMed.html#cb236-2" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(lavaan)){<span class="fu">install.packages</span>(<span class="st">&quot;lavaan&quot;</span>)}</span>
<span id="cb236-3"><a href="SimpleMed.html#cb236-3" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(semPlot)){<span class="fu">install.packages</span>(<span class="st">&quot;semPlot&quot;</span>)}</span>
<span id="cb236-4"><a href="SimpleMed.html#cb236-4" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(tidyverse)){<span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)}</span>
<span id="cb236-5"><a href="SimpleMed.html#cb236-5" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(psych)){<span class="fu">install.packages</span>(<span class="st">&quot;psych&quot;</span>)}</span>
<span id="cb236-6"><a href="SimpleMed.html#cb236-6" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(formattable)){<span class="fu">install.packages</span>(<span class="st">&quot;formattable&quot;</span>)}</span>
<span id="cb236-7"><a href="SimpleMed.html#cb236-7" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(semTable)){<span class="fu">install.packages</span>(<span class="st">&quot;semTable&quot;</span>)}</span></code></pre></div>
</div>
</div>
<div id="estimating-indirect-effects-the-analytic-approach-often-termed-mediation" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Estimating Indirect Effects (the analytic approach often termed <em>mediation</em>)<a href="SimpleMed.html#estimating-indirect-effects-the-analytic-approach-often-termed-mediation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="the-definitional-and-conceptual" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> The definitional and conceptual<a href="SimpleMed.html#the-definitional-and-conceptual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As in Hayes text <span class="citation">(<a href="#ref-hayes_introduction_2018">2018</a>)</span>, we will differentiate between <em>moderation</em> and <em>mediation</em>. <em>Conditional process analysis</em> involves both! With each of these, we are seeking to understand the <em>mechanism</em> at work that leads to the relationship (be it correlational, predictive, or causal)</p>
<p>Even though this process has sometimes been termed <em>causal modeling</em>, Hayes argues that his <em>statistical approach</em> is not claiming to determine <em>cause</em>; that is really left to the argument of the research design.</p>
<p><strong>Moderation</strong> (a review):</p>
<ul>
<li>Answers questions of <em>when</em> or <em>for whom</em> and is often the source of the answer, <em>it depends</em>.</li>
<li>Think of our <em>interaction</em> effects in ANOVA and regression</li>
<li>The effect of X on some variable Y is moderated by W if its size, sign, or strength depends on, or can be predicted, by W. Then we can say, “W is a <em>moderator</em> of X’s effect on Y” or “W and X <em>interact</em> in their influence on Y.”</li>
<li>The image below illustrates moderation with <em>conceptual</em> and <em>statistical</em> diagrams. Note that three predictors (IV, DV, their interaction) point to the DV.</li>
</ul>
<div class="float">
<img src="images/SimpleMed/ModConcStat.jpg" alt="Image of Hayes’style conceptual and statistical diagrams of a simple moderation" />
<div class="figcaption">Image of Hayes’style conceptual and statistical diagrams of a simple moderation</div>
</div>
<p>The classic plot of moderation results is often the best way to detect that an interaction was included in the analysis and helps understand the <em>conditional</em> (e.g., for whom, under what conditions) nature of the analysis.</p>
<div class="float">
<img src="images/SimpleMed/SimpleInteraction.jpg" alt="Image of classic interaction graph that illustrates a moderated effect. The IV is on the X axis, DV on the Y axis, and two intersecting lines represent the differential/moderated effect of the IV on the DV by the moderator" />
<div class="figcaption">Image of classic interaction graph that illustrates a moderated effect. The IV is on the X axis, DV on the Y axis, and two intersecting lines represent the differential/moderated effect of the IV on the DV by the moderator</div>
</div>
<p><strong>Mediation</strong>:</p>
<ul>
<li>Answers questions of <em>how</em> (I also think <em>through</em> and <em>via</em> to describe the proposed mediating mechanism)</li>
<li>Paths in a mediation model are <em>direct</em> (X does not pass through M on its way to Y) and <em>indirect</em> (X passes through M on its way to Y). Once we get into the statistics, we will also be focused on <em>total</em> effects.</li>
<li>Hayes thinks in terms of <em>antecedent</em> and <em>consequent</em> variables. In a 3-variable, simple mediation, X and M are the antecedent variables; X and M are the consequent variables.<br />
</li>
<li>There is substantial debate and controversy about whether we can say “the effect of X on Y is <em>mediated</em> through M” or whether we should say, “There is a statistically significant indirect effect of X on Y thru M.” Hayes comes down on the “use mediation language” side of the debate.<br />
</li>
<li>In sum, a simple mediation model is any causal system in which at least one causal antecedent X variable is proposed as influencing an outcome Y through a single intervening variable, M. In such a model there are two pathways by which X can influence Y.</li>
<li>The figure below doubles as both the conceptual and statistical diagram of evaluating a simple mediation – a simple indirect effect.</li>
</ul>
<div class="float">
<img src="images/SimpleMed/SimpleMed.jpg" alt="Image of Hayes’style conceptual diagram of a simple moderation" />
<div class="figcaption">Image of Hayes’style conceptual diagram of a simple moderation</div>
</div>
<p><strong>Conditional process analysis</strong>:</p>
<ul>
<li>Used when the research goal is to understand the boundary conditions of the mechanism(s) by which a variable transmits its effect on another.<br />
</li>
<li>Typically, simultaneously, assesses the influence of mediating (indirect effects) and moderating (interactional effects) in a model-building fashion.</li>
<li>In a conditional process model, the moderator(s) may be hypothesized to influence one or more of the paths.</li>
</ul>
<p>We will work toward building a conditional process model, a moderated mediation, over the next several chapters.</p>
<div class="float" id="id">
<img src="images/SimpleMed/CPAmodel.jpg" class="class" width="250" height="180" alt="Image of conditional process analysis model where the moderator is hypothesized to change the a path; the path between the IV and mediator" />
<div class="figcaption">Image of conditional process analysis model where the moderator is hypothesized to change the a path; the path between the IV and mediator</div>
</div>
</div>
</div>
<div id="workflow-for-simple-mediation" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Workflow for Simple Mediation<a href="SimpleMed.html#workflow-for-simple-mediation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The workflow for a simple mediation is straightforward, however the figure below (i.e., the very traditional figure used to represent mediation) is very helpful in understanding the logic beneath mediation as the explanatory mechanism.</p>
<div class="float">
<img src="images/SimpleMed/MedRationale.jpg" alt="Image of conditional process analysis model where the mediator is hypothesized to change the a path; the path between the IV and mediator" />
<div class="figcaption">Image of conditional process analysis model where the mediator is hypothesized to change the a path; the path between the IV and mediator</div>
</div>
<p>The top figure represents the bivariate relationship between the independent and dependent variable. The result of a simple linear regression (one predictor) represent the <em>total</em> effect of the IV on the DV. We can calculate this by simply regressing the DV onto the IV. The resulting <span class="math inline">\(B\)</span> weight is known as the <em>c</em> path. A bivariate correlation coefficient results in the same value – only it is standardized (so would be the same as the <span class="math inline">\(\beta\)</span> weight).</p>
<p>The lower figure represents that the relationship between the IV and DV is <em>mediated</em> by a third variable. We assign three labels to the paths: <em>a</em>, between the IV and mediator; <em>b</em>, between the mediator and DV; and <em>c’</em> (c prime) between the IV and DV.</p>
<p>Statistically speaking, a mediated relationship is supported when the value of <em>c’</em> is statistically significantly lower than <em>c</em>. If this occurs, then we can say that the mediator is sharing some of the variance in the prediction of the DV.</p>
<p>You might already be imagining potential challenges to this model. For example, which variable should be the IV and which one should be the mediator? Can we switch them? You can – and you will likely have very similar (if not identical) results. Good research design is what provides support for suggesting that mediation is the proper, casual, mechanism regarding the relationship between the IV and DV. An excellent review of the challenges of establishing a robust mediation model is provided by Kline <span class="citation">(<a href="#ref-kline_mediation_2015">2015</a>)</span>, where he suggests the following as the minimally required elements of a mediation design:</p>
<ul>
<li>the IV is an experimental variable with random assignment to conditions;</li>
<li>the mediator is an individual difference variable that is not manipulated and is measured at a later time;and</li>
<li>the DV is measured at a third occasion</li>
</ul>
<p>These criteria are in addition to the rather standard criteria for establishing causality <span class="citation">(see <a href="#ref-stone-romero_research_2010">Stone-Romero &amp; Rosopa, 2010</a> for a review)</span>:</p>
<ul>
<li>temporal precedence,</li>
<li>statistical covariation, and</li>
<li>ruling out plausible rival hypotheses.</li>
</ul>
<p>Some journals take this very seriously. In fact <a href="https://www.journals.elsevier.com/journal-of-vocational-behavior/news/frequently-asked-questions-about-submitting-a-manuscript">FAQs</a> in the Journal of Vocational Behavior make it clear that they will very rarely publish a “mediation manuscript” unless it has a minimum of three waves.</p>
<p>Working through a mediation will help operationalize these concepts.</p>
</div>
<div id="simple-mediation-in-lavaan-a-focus-on-the-mechanics" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Simple Mediation in <em>lavaan</em>: A focus on the mechanics<a href="SimpleMed.html#simple-mediation-in-lavaan-a-focus-on-the-mechanics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The lavaan tutorial <span class="citation">(<a href="#ref-rosseel_lavaan_2020">Rosseel, 2020</a>)</span> provides a helpful model of how writing code to estimate an indirect effect. Using the lavaan tutorial as our guide, let’s start with just a set of fake data with variable names that represent X (predictor, IV, antecedent), M (mediator, atencedent, consequent), and Y (outcome, DV, consequent).</p>
<div id="simulate-fake-data" class="section level3 hasAnchor" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Simulate Fake Data<a href="SimpleMed.html#simulate-fake-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The code below is asking to create a dataset with a sample size of 100. The dataset has 3 variables, conveniently named X (predictor, antecedent, IV), M (mediator), and Y (outome, consequent, DV). The R code asks for random selection of numbers with a normal distribution. You can see that the M variable will be related to the X variable by + .5; and the Y variable will be related to the M variable by + .7. This rather ensures a statistically significant indirect effect.</p>
<!-- TODO: Return and replace with data from our mediation) -->
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="SimpleMed.html#cb237-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">210410</span>)</span>
<span id="cb237-2"><a href="SimpleMed.html#cb237-2" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb237-3"><a href="SimpleMed.html#cb237-3" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fl">0.5</span><span class="sc">*</span>X <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb237-4"><a href="SimpleMed.html#cb237-4" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fl">0.7</span><span class="sc">*</span>M <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb237-5"><a href="SimpleMed.html#cb237-5" tabindex="-1"></a>Data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X =</span> X, <span class="at">Y =</span> Y, <span class="at">M =</span> M)</span></code></pre></div>
</div>
<div id="specify-mediation-model" class="section level3 hasAnchor" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Specify Mediation Model<a href="SimpleMed.html#specify-mediation-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The package we are using is <em>lavaan</em>. Hayes’ model is <em>path analysis</em>, which can be a form of structural equation modeling. As a quick reminder, in SPSS, PROCESS is limited to ordinary least squares regression. We will use maximum likliehood estimators for the Hayes/PROCESS examples, but <em>lavaan</em> can take us further than PROCESS because</p>
<ul>
<li>We can (and, in later chapters, will) do latent variable modeling.</li>
<li>We can have more specificity and flexibility than the prescribed PROCESS models allow. I say this with all due respect to Hayes – there is also a good deal of flexibility to be able to add multiple mediators and covariates within most of the Hayes’ prescribed models.</li>
</ul>
<p>Hayes text is still a great place to start because the conceptual and procedural information is clear and transferable to the R environment.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="SimpleMed.html#cb238-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code></pre></div>
<pre><code>## This is lavaan 0.6-16
## lavaan is FREE software! Please report any bugs.</code></pre>
<p>Our atheoretical dataset makes it easy to identify which variable belongs in each role (X,Y,M). When specifying the paths in lavaan, here’s what to keep in mind:</p>
<ul>
<li>Name your model/object (below is X, “&lt;-” means “is defined by”)</li>
<li>The model exists between 2 single quotation marks (the odd looking ’ and ’ at the beginning and end).</li>
<li>The # of regression equations you need depends on the # of variables that have arrows pointing to them. In a simple mediation, there are 3 variables with 2 variables having arrows pointing to them – need 2 regression equations:
<ul>
<li>one for the Mediator</li>
<li>one for the DV (Y)</li>
</ul></li>
<li>Operator for a regression analysis is the (tilde, ~)</li>
<li>DV goes on left
<ul>
<li>In first equation we regress both the X and M onto Y</li>
<li>In second equation we regress M onto X</li>
</ul></li>
<li>The asterisk (*) is a handy tool to label variables (don’t confuse it as defining an interaction); this labeling as a, b, and c_p (in traditional mediation, the total effect is labeled with a and the direct effect is c’[c prime], but the script won’t allow and extra single quotation mark, hence c_p) is super helpful in interpreting the ouput</li>
<li>The indirect effect is created by multiplying the a and b paths.<br />
</li>
<li>The “:=” sign is used when creating a new variable that is a function of variables in the model, but not in the dataset (i.e., the a and b path).</li>
</ul>
<p>After specifying the model, we create an object that holds our results from the SEM. To obtain all the results from our of indirect effects, we also need to print a summary of the fit statistics, standardized estimates, r-squared, and confidence intervals.</p>
<p><em>Other authors will write the model code more sensibly, predicting the mediator first, and then the Y variable. However, I found that by doing it this way, the semPlot produces a more sensible figure.</em></p>
<p>Also, because we set a random seed, you should get the same results, but if it differs a little, don’t panic.
Also, in Hayes text the direct path from X to Y is c’ (“c prime”; where as c is reserved for the total effect of X on Y).</p>
<p>Let’s run the whole model.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="SimpleMed.html#cb240-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">210410</span>) <span class="co">#reset in case you choose to separate these sections</span></span>
<span id="cb240-2"><a href="SimpleMed.html#cb240-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb240-3"><a href="SimpleMed.html#cb240-3" tabindex="-1"></a><span class="st">          Y ~ b*M + c_p*X </span></span>
<span id="cb240-4"><a href="SimpleMed.html#cb240-4" tabindex="-1"></a><span class="st">          M ~ a*X</span></span>
<span id="cb240-5"><a href="SimpleMed.html#cb240-5" tabindex="-1"></a><span class="st">          </span></span>
<span id="cb240-6"><a href="SimpleMed.html#cb240-6" tabindex="-1"></a><span class="st">          indirect :=  a*b</span></span>
<span id="cb240-7"><a href="SimpleMed.html#cb240-7" tabindex="-1"></a><span class="st">          direct  := c_p</span></span>
<span id="cb240-8"><a href="SimpleMed.html#cb240-8" tabindex="-1"></a><span class="st">          total_c  := c_p + (a*b)</span></span>
<span id="cb240-9"><a href="SimpleMed.html#cb240-9" tabindex="-1"></a><span class="st">          &#39;</span></span>
<span id="cb240-10"><a href="SimpleMed.html#cb240-10" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(model, <span class="at">data =</span> Data, <span class="at">se=</span><span class="st">&quot;bootstrap&quot;</span>, <span class="at">missing=</span> <span class="st">&#39;fiml&#39;</span>)</span>
<span id="cb240-11"><a href="SimpleMed.html#cb240-11" tabindex="-1"></a>FDsummary <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit, <span class="at">standardized=</span>T, <span class="at">rsq=</span>T, <span class="at">fit=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span>
<span id="cb240-12"><a href="SimpleMed.html#cb240-12" tabindex="-1"></a>FD_ParamEsts <span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(fit, <span class="at">boot.ci.type =</span> <span class="st">&quot;bca.simple&quot;</span>, <span class="at">standardized=</span><span class="cn">TRUE</span>)</span>
<span id="cb240-13"><a href="SimpleMed.html#cb240-13" tabindex="-1"></a>FDsummary</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         7
## 
##   Number of observations                           100
##   Number of missing patterns                         1
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Model Test Baseline Model:
## 
##   Test statistic                                92.701
##   Degrees of freedom                                 3
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                       1.000
##                                                       
##   Robust Comparative Fit Index (CFI)             1.000
##   Robust Tucker-Lewis Index (TLI)                1.000
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -287.127
##   Loglikelihood unrestricted model (H1)       -287.127
##                                                       
##   Akaike (AIC)                                 588.253
##   Bayesian (BIC)                               606.489
##   Sample-size adjusted Bayesian (SABIC)        584.382
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: RMSEA &lt;= 0.050                       NA
##   P-value H_0: RMSEA &gt;= 0.080                       NA
##                                                       
##   Robust RMSEA                                   0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: Robust RMSEA &lt;= 0.050                NA
##   P-value H_0: Robust RMSEA &gt;= 0.080                NA
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                            Bootstrap
##   Number of requested bootstrap draws             1000
##   Number of successful bootstrap draws            1000
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   Y ~                                                                   
##     M          (b)    0.764    0.094    8.162    0.000    0.587    0.949
##     X        (c_p)   -0.209    0.110   -1.896    0.058   -0.420    0.014
##   M ~                                                                   
##     X          (a)    0.693    0.100    6.922    0.000    0.490    0.879
##    Std.lv  Std.all
##                   
##     0.764    0.719
##    -0.209   -0.163
##                   
##     0.693    0.574
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .Y                -0.044    0.109   -0.406    0.685   -0.265    0.158
##    .M                 0.106    0.107    0.995    0.320   -0.110    0.326
##    Std.lv  Std.all
##    -0.044   -0.034
##     0.106    0.086
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .Y                 1.031    0.151    6.841    0.000    0.732    1.320
##    .M                 1.037    0.141    7.374    0.000    0.747    1.320
##    Std.lv  Std.all
##     1.031    0.590
##     1.037    0.670
## 
## R-Square:
##                    Estimate
##     Y                 0.410
##     M                 0.330
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##     indirect          0.529    0.087    6.102    0.000    0.353    0.710
##     direct           -0.209    0.110   -1.895    0.058   -0.420    0.014
##     total_c           0.321    0.120    2.669    0.008    0.079    0.545
##    Std.lv  Std.all
##     0.529    0.413
##    -0.209   -0.163
##     0.321    0.250</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="SimpleMed.html#cb242-1" tabindex="-1"></a>FD_ParamEsts</span></code></pre></div>
<pre><code>##         lhs op       rhs    label    est    se      z pvalue ci.lower ci.upper
## 1         Y  ~         M        b  0.764 0.094  8.162  0.000    0.596    0.954
## 2         Y  ~         X      c_p -0.209 0.110 -1.896  0.058   -0.425    0.013
## 3         M  ~         X        a  0.693 0.100  6.922  0.000    0.496    0.885
## 4         Y ~~         Y           1.031 0.151  6.841  0.000    0.772    1.353
## 5         M ~~         M           1.037 0.141  7.374  0.000    0.813    1.381
## 6         X ~~         X           1.063 0.000     NA     NA    1.063    1.063
## 7         Y ~1                    -0.044 0.109 -0.406  0.685   -0.256    0.159
## 8         M ~1                     0.106 0.107  0.995  0.320   -0.103    0.332
## 9         X ~1                    -0.195 0.000     NA     NA   -0.195   -0.195
## 10 indirect :=       a*b indirect  0.529 0.087  6.102  0.000    0.373    0.716
## 11   direct :=       c_p   direct -0.209 0.110 -1.895  0.058   -0.425    0.013
## 12  total_c := c_p+(a*b)  total_c  0.321 0.120  2.669  0.008    0.090    0.560
##    std.lv std.all std.nox
## 1   0.764   0.719   0.719
## 2  -0.209  -0.163  -0.158
## 3   0.693   0.574   0.557
## 4   1.031   0.590   0.590
## 5   1.037   0.670   0.670
## 6   1.063   1.000   1.063
## 7  -0.044  -0.034  -0.034
## 8   0.106   0.086   0.086
## 9  -0.195  -0.189  -0.195
## 10  0.529   0.413   0.401
## 11 -0.209  -0.163  -0.158
## 12  0.321   0.250   0.243</code></pre>
</div>
<div id="interpret-the-output" class="section level3 hasAnchor" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Interpret the Output<a href="SimpleMed.html#interpret-the-output" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Note that in the script we ask (and get) two sets of parameter estimates. The second set (in the really nice dataframe) includes bootstrapped, bias-corrected confidence intervals. Bias-corrected confidence interals have the advantage of being more powerful and bias-free. Note, though, that when the CI crosses 0, the effect is NS.</p>
<p>So let’s look at this step-by-step.</p>
<ul>
<li>Overall, our model accounted for of the variance in the IV and of the variance in the mediator.</li>
<li>a path = 0.693, <span class="math inline">\(p\)</span> = 0.000</li>
<li>b path = 0.764, <span class="math inline">\(p\)</span> = 0.000</li>
<li>the indirect effect is a product of the a and b paths (0.693 * 0.764 = 0.529); while we don’t hand calculate it’s significance, we see that it is <span class="math inline">\(p\)</span> = 0.000</li>
<li>the direct effect (c’, c prime, or c_p) is the isolated effect of X on Y when including M. We hope this value is LOWER than the total effect because this means that including M shared some of the variance in predicting Y: c’ = -0.209, <span class="math inline">\(p\)</span> = 0.058, and it is no longer signifcant.</li>
<li>we also see the total effect; this value is
<ul>
<li>identical to the value of simply predicting Y on X (with no M it the model)</li>
<li>the value of a(b) + c_p: 0.693(0.764) + -0.209 = 0.321 (<span class="math inline">\(p\)</span> = 0.008)</li>
</ul></li>
</ul>
<p>Here’s a demonstration that the total effect is, simply, predicting Y from X (also, the correlation between X and Y:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="SimpleMed.html#cb244-1" tabindex="-1"></a>fitXY <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data =</span> Data)</span>
<span id="cb244-2"><a href="SimpleMed.html#cb244-2" tabindex="-1"></a><span class="fu">summary</span>(fitXY)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y ~ X, data = Data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2631 -0.8288  0.0902  0.9637  3.5891 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)   0.0370     0.1315   0.281    0.779  
## X             0.3208     0.1253   2.560    0.012 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.292 on 98 degrees of freedom
## Multiple R-squared:  0.06267,    Adjusted R-squared:  0.05311 
## F-statistic: 6.552 on 1 and 98 DF,  p-value: 0.012</code></pre>
<p>Which is the same as the bivariate correlation. The only trick is that the bivariate correlation produces a standardized result; so it would be the <span class="math inline">\(\beta\)</span>.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="SimpleMed.html#cb246-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:lavaan&#39;:
## 
##     cor2cov</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="SimpleMed.html#cb249-1" tabindex="-1"></a>XY_r <span class="ot">&lt;-</span> <span class="fu">corr.test</span>(Data[<span class="fu">c</span>(<span class="st">&quot;Y&quot;</span>, <span class="st">&quot;X&quot;</span>)])</span>
<span id="cb249-2"><a href="SimpleMed.html#cb249-2" tabindex="-1"></a>XY_r</span></code></pre></div>
<pre><code>## Call:corr.test(x = Data[c(&quot;Y&quot;, &quot;X&quot;)])
## Correlation matrix 
##      Y    X
## Y 1.00 0.25
## X 0.25 1.00
## Sample Size 
## [1] 100
## Probability values (Entries above the diagonal are adjusted for multiple tests.) 
##      Y    X
## Y 0.00 0.01
## X 0.01 0.00
## 
##  To see confidence intervals of the correlations, print with the short=FALSE option</code></pre>
</div>
<div id="a-table-and-a-figure" class="section level3 hasAnchor" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> A Table and a Figure<a href="SimpleMed.html#a-table-and-a-figure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can use the package <a href="https://rdrr.io/cran/semPlot/man/semPaths.html">semPlot</a> to create a figure that includes the values on the path.</p>
<p>Here’s what the base package gets us</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="SimpleMed.html#cb251-1" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb251-2"><a href="SimpleMed.html#cb251-2" tabindex="-1"></a><span class="fu">semPaths</span>(fit, <span class="co">#must identify the model you want to map</span></span>
<span id="cb251-3"><a href="SimpleMed.html#cb251-3" tabindex="-1"></a>         <span class="at">what =</span> <span class="st">&quot;est&quot;</span>, <span class="co">#&quot;est&quot; plots the estimates, but keeps it greyscale with no fading</span></span>
<span id="cb251-4"><a href="SimpleMed.html#cb251-4" tabindex="-1"></a>         <span class="co">#whatLabels = &quot;stand&quot;, #&quot;stand&quot; changes to standardized values</span></span>
<span id="cb251-5"><a href="SimpleMed.html#cb251-5" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">&#39;tree&#39;</span>, <span class="at">rotation =</span> <span class="dv">2</span>, <span class="co">#together, puts predictors on left, IVs on right </span></span>
<span id="cb251-6"><a href="SimpleMed.html#cb251-6" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.00</span>, <span class="co">#font size of parameter values</span></span>
<span id="cb251-7"><a href="SimpleMed.html#cb251-7" tabindex="-1"></a>         <span class="co">#edge.color = &quot;black&quot;, #overwrites the green/black coloring</span></span>
<span id="cb251-8"><a href="SimpleMed.html#cb251-8" tabindex="-1"></a>         <span class="at">sizeMan=</span><span class="dv">10</span>, <span class="co">#size of squares/observed/&quot;manifest&quot; variables</span></span>
<span id="cb251-9"><a href="SimpleMed.html#cb251-9" tabindex="-1"></a>         <span class="at">fade=</span><span class="cn">FALSE</span>, <span class="co">#if TRUE, there lines are faded such that weaker lines correspond with lower values -- a cool effect, but tough for journals</span></span>
<span id="cb251-10"><a href="SimpleMed.html#cb251-10" tabindex="-1"></a>         <span class="at">esize=</span><span class="dv">2</span>, </span>
<span id="cb251-11"><a href="SimpleMed.html#cb251-11" tabindex="-1"></a>         <span class="at">asize=</span><span class="dv">3</span>,</span>
<span id="cb251-12"><a href="SimpleMed.html#cb251-12" tabindex="-1"></a>         <span class="co">#label.prop = .5,</span></span>
<span id="cb251-13"><a href="SimpleMed.html#cb251-13" tabindex="-1"></a>         <span class="at">label.font =</span> <span class="fl">2.5</span>, <span class="co">#controls size (I think) of font for labels</span></span>
<span id="cb251-14"><a href="SimpleMed.html#cb251-14" tabindex="-1"></a>         <span class="at">label.scale =</span> <span class="cn">TRUE</span>, <span class="co">#if false, the labels will not scale to fit inside the nodes</span></span>
<span id="cb251-15"><a href="SimpleMed.html#cb251-15" tabindex="-1"></a>         <span class="at">nDigits =</span> <span class="dv">3</span>, <span class="co">#decimal places (default is 2)</span></span>
<span id="cb251-16"><a href="SimpleMed.html#cb251-16" tabindex="-1"></a>         <span class="at">residuals =</span> <span class="cn">FALSE</span>,<span class="co">#excludes residuals (and variances) from the path diagram</span></span>
<span id="cb251-17"><a href="SimpleMed.html#cb251-17" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="co">#specifies how many characters to abbreviate variable lables; default is 3.  If 0, uses your entire variable label and adjusts fontsize (which could be a downside)</span></span>
<span id="cb251-18"><a href="SimpleMed.html#cb251-18" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>, <span class="co">#gets rid of those annoying triangles (intercepts) in the path diagram)</span></span>
<span id="cb251-19"><a href="SimpleMed.html#cb251-19" tabindex="-1"></a>)</span>
<span id="cb251-20"><a href="SimpleMed.html#cb251-20" tabindex="-1"></a><span class="fu">title</span>(<span class="st">&quot;Fake Data:  Simple Mediation&quot;</span>)</span></code></pre></div>
<p><img src="05-SimpleMed_files/figure-html/FakyDaty%20Simple%20Plot-1.png" width="672" /></p>
<p>Hayes has great examples of APA style tables. I haven’t yet found a package that will turn this output into a journal-ready table, however the <em>semTable</em> package can at least write the output to a .csv file and you can further manipulate it into a table.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="SimpleMed.html#cb252-1" tabindex="-1"></a><span class="fu">library</span>(semTable)</span>
<span id="cb252-2"><a href="SimpleMed.html#cb252-2" tabindex="-1"></a>fitTab1 <span class="ot">&lt;-</span> <span class="fu">semTable</span>(fit, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">&quot;est&quot;</span>, <span class="st">&quot;se&quot;</span>, <span class="st">&quot;p&quot;</span>, <span class="st">&quot;rsquare&quot;</span>),  <span class="at">columnLabels =</span> <span class="fu">c</span>(<span class="at">eststars =</span> <span class="st">&quot;Estimate&quot;</span>), <span class="at">paramSets =</span> <span class="fu">c</span>(<span class="st">&quot;composites&quot;</span>, <span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;slopes&quot;</span>, <span class="st">&quot;intercepts&quot;</span>, <span class="st">&quot;residualvariances&quot;</span>), <span class="at">file =</span> <span class="st">&quot;fitTABLE&quot;</span>, <span class="at">type =</span> <span class="st">&quot;csv&quot;</span>, <span class="at">print.results =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="results-4" class="section level3 hasAnchor" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Results<a href="SimpleMed.html#results-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A simple mediation model examined the degree to which M mediated the relation of X on Y. Using the <em>lavaan</em> package (v 0.6-7) in R, coefficients for each path, the indirect effect, and total effects were calculated. These values are presented in Table 1 and illustrated in Figure 1. Results suggested that of the variance in M and of the variance in Y were accounted for in the model. The indirect effect (<span class="math inline">\(B\)</span> = 0.529, <span class="math inline">\(p\)</span> = 0.000) was statistically significant; the direct effect (<span class="math inline">\(B\)</span> = -0.209, <span class="math inline">\(p\)</span> = 0.058) was not. Comparing the nonsignificant direct effect to the statistically significant total effect (<span class="math inline">\(B\)</span> = 0.321, <span class="math inline">\(p\)</span> = 0.008) is consistent with the notion that the effect of X on Y is explained through M.</p>
</div>
</div>
<div id="research-vignette-4" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Research Vignette<a href="SimpleMed.html#research-vignette-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The research vignette comes from the Kim, Kendall, and Cheon’s <span class="citation">(<a href="#ref-kim_racial_2017">2017</a>)</span>, “Racial Microaggressions, Cultural Mistrust, and Mental Health Outcomes Among Asian American College Students.” Participants were 156 Asian American undergraduate students in the Pacific Northwest. The researchers posited the a priori hypothesis that cultural mistrust would mediate the relationship between racial microaggressions and two sets of outcomes: mental health (e.g., depression, anxiety, well-being) and help-seeking.</p>
<p>Variables used in the study included:</p>
<ul>
<li><strong>REMS</strong>: Racial and Ethnic Microaggressions Scale (Nadal, 2011). The scale includes 45 items on a 2-point scale where 0 indicates no experience of a microaggressive event and 1 indicates it was experienced at least once within the past six months. Higher scores indicate more experience of microaggressions.</li>
<li><strong>CMI</strong>: Cultural Mistrust Inventory (Terrell &amp; Terrell, 1981). This scale was adapted to assess cultural mistrust harbored among Asian Americans toward individuals from the mainstream U.S. culture (e.g., Whites). The CMI includes 47 items on a 7-point scale where higher scores indicate a higher degree of cultural mistrust.</li>
<li><strong>ANX</strong>, <strong>DEP</strong>, <strong>PWB</strong>: Subscales of the Mental Health Inventory (Veit &amp; Ware, 1983) that assess the mental health outcomes of anxiety (9 items), depression (4 items), and psychological well-being (14 items). Higher scores (on a 6 point scale) indicate stronger endorsement of the mental health outcome being assessed.</li>
<li><strong>HlpSkg</strong>: The Attiudes Toward Seeking Professional Psychological Help – Short Form (Fischer &amp; Farina, 1995) includes 10 items on a 4-point scale (0 = disagree, 3 = agree) where higher scores indicate more favorable attitudes toward help seeking.</li>
</ul>
<div id="simulate-data-from-the-journal-article" class="section level3 hasAnchor" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Simulate Data from the Journal Article<a href="SimpleMed.html#simulate-data-from-the-journal-article" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, we simulate the data from the means, standard deviations, and correlation matrix from the journal article.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="SimpleMed.html#cb253-1" tabindex="-1"></a><span class="co">#Entering the intercorrelations, means, and standard deviations from the journal article</span></span>
<span id="cb253-2"><a href="SimpleMed.html#cb253-2" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">34</span>, <span class="fl">3.00</span>, <span class="fl">2.98</span>, <span class="fl">2.36</span>, <span class="fl">3.50</span>, <span class="fl">1.64</span>)</span>
<span id="cb253-3"><a href="SimpleMed.html#cb253-3" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">16</span>, .<span class="dv">83</span>, .<span class="dv">99</span>, .<span class="dv">90</span>, .<span class="dv">90</span>, .<span class="dv">53</span>)</span>
<span id="cb253-4"><a href="SimpleMed.html#cb253-4" tabindex="-1"></a>r_mat <span class="ot">&lt;-</span> <span class="fu">matrix</span> (<span class="fu">c</span>(<span class="dv">1</span>,   .<span class="dv">59</span>, .<span class="dv">26</span>,   .<span class="dv">34</span>,  <span class="sc">-</span>.<span class="dv">25</span>, <span class="sc">-</span>.<span class="dv">02</span>,</span>
<span id="cb253-5"><a href="SimpleMed.html#cb253-5" tabindex="-1"></a>                  .<span class="dv">59</span>, <span class="fl">1.00</span>, .<span class="dv">12</span>,   .<span class="dv">19</span>,  <span class="sc">-</span>.<span class="dv">28</span>, .<span class="dv">00</span>, </span>
<span id="cb253-6"><a href="SimpleMed.html#cb253-6" tabindex="-1"></a>                  .<span class="dv">26</span>,  .<span class="dv">12</span>, <span class="fl">1.00</span>, .<span class="dv">66</span>,  <span class="sc">-</span>.<span class="dv">55</span>, .<span class="dv">07</span>,</span>
<span id="cb253-7"><a href="SimpleMed.html#cb253-7" tabindex="-1"></a>                  .<span class="dv">34</span>,  .<span class="dv">19</span>, .<span class="dv">66</span>,  <span class="fl">1.00</span>, <span class="sc">-</span>.<span class="dv">66</span>, .<span class="dv">05</span>,</span>
<span id="cb253-8"><a href="SimpleMed.html#cb253-8" tabindex="-1"></a>                 <span class="sc">-</span>.<span class="dv">25</span>, <span class="sc">-</span>.<span class="dv">28</span>, <span class="sc">-</span>.<span class="dv">55</span>,<span class="sc">-</span>.<span class="dv">66</span>,  <span class="fl">1.00</span>, .<span class="dv">08</span>, </span>
<span id="cb253-9"><a href="SimpleMed.html#cb253-9" tabindex="-1"></a>                 <span class="sc">-</span>.<span class="dv">02</span>,  .<span class="dv">00</span>,  .<span class="dv">07</span>, .<span class="dv">05</span>, .<span class="dv">08</span>,  <span class="dv">1</span>), <span class="at">ncol =</span> <span class="dv">6</span>)</span>
<span id="cb253-10"><a href="SimpleMed.html#cb253-10" tabindex="-1"></a><span class="co">#Creating a covariance matrix</span></span>
<span id="cb253-11"><a href="SimpleMed.html#cb253-11" tabindex="-1"></a>cov_mat <span class="ot">&lt;-</span> sd <span class="sc">%*%</span> <span class="fu">t</span>(sd) <span class="sc">*</span> r_mat</span>
<span id="cb253-12"><a href="SimpleMed.html#cb253-12" tabindex="-1"></a></span>
<span id="cb253-13"><a href="SimpleMed.html#cb253-13" tabindex="-1"></a><span class="co">#Set random seed so that the following matrix always gets the same results.</span></span>
<span id="cb253-14"><a href="SimpleMed.html#cb253-14" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">210409</span>)</span>
<span id="cb253-15"><a href="SimpleMed.html#cb253-15" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:formattable&#39;:
## 
##     area</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="SimpleMed.html#cb256-1" tabindex="-1"></a>Kim_df <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">156</span>, <span class="at">mu=</span>mu, <span class="at">Sigma =</span> cov_mat, <span class="at">empirical =</span> <span class="cn">TRUE</span>)</span>
<span id="cb256-2"><a href="SimpleMed.html#cb256-2" tabindex="-1"></a><span class="fu">colMeans</span>(Kim_df)</span></code></pre></div>
<pre><code>## [1] 0.34 3.00 2.98 2.36 3.50 1.64</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="SimpleMed.html#cb258-1" tabindex="-1"></a><span class="co">#Checking our work against the original correlation matrix</span></span>
<span id="cb258-2"><a href="SimpleMed.html#cb258-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(Kim_df),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
## [1,]  1.00  0.59  0.26  0.34 -0.25 -0.02
## [2,]  0.59  1.00  0.12  0.19 -0.28  0.00
## [3,]  0.26  0.12  1.00  0.66 -0.55  0.07
## [4,]  0.34  0.19  0.66  1.00 -0.66  0.05
## [5,] -0.25 -0.28 -0.55 -0.66  1.00  0.08
## [6,] -0.02  0.00  0.07  0.05  0.08  1.00</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="SimpleMed.html#cb260-1" tabindex="-1"></a><span class="co">#renaming the variables</span></span>
<span id="cb260-2"><a href="SimpleMed.html#cb260-2" tabindex="-1"></a><span class="fu">as.data.frame</span>(Kim_df, <span class="at">row.names =</span> <span class="cn">NULL</span>, <span class="at">optional =</span> <span class="cn">FALSE</span>, <span class="at">make.names =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##              V1        V2        V3         V4       V5        V6
## 1    0.31480075 3.7742194 3.9885237  2.6561280 3.902766 1.2282205
## 2    0.12504376 2.4630397 3.1591179  1.7873208 4.434146 1.4990282
## 3    0.17784660 1.8376841 3.8176890  2.5481372 3.299962 1.3126023
## 4    0.75415493 4.8268167 3.2961255  2.1700517 3.274046 1.4857932
## 5    0.28473851 2.1622754 2.9837665  2.6213814 3.851441 1.4330810
## 6    0.37498180 4.1070853 3.4324724  3.0951215 2.880348 1.9417795
## 7    0.17693663 1.8937966 3.6027771  2.7026733 4.159506 1.5721610
## 8    0.29125231 2.6160275 2.9306768  2.0874299 4.148450 2.4368026
## 9    0.20511465 2.7325373 2.7857356  1.9796662 3.253885 1.8116435
## 10   0.53359317 3.2392905 3.0132959  2.0895764 4.367763 2.4243275
## 11   0.63114162 3.9771384 3.4587058  2.9438475 1.807563 1.2569630
## 12   0.40896721 3.6662876 4.0138230  3.3097403 2.742602 1.7651180
## 13   0.26224312 2.8483570 4.2526175  2.8099626 3.295733 1.9924000
## 14   0.32704221 3.1617904 3.1070588  2.4118363 3.810240 2.3476934
## 15   0.60748029 3.6350970 3.9352681  3.2005377 3.393395 1.7029545
## 16   0.55843862 3.7676612 2.6728071  1.8013062 2.456926 1.8749401
## 17   0.16189032 2.7778703 2.1929777  3.1968281 4.053990 1.4759460
## 18   0.09036787 2.5826597 1.7540157  1.4921435 3.472623 1.5609561
## 19   0.60989051 4.6660979 3.4085289  2.2633219 2.865315 1.3588810
## 20   0.45105455 2.5689387 3.5198695  3.5398776 2.862075 2.1906123
## 21   0.08222908 2.8395169 1.7860559  1.0991829 4.203118 1.5276039
## 22   0.24533439 1.5002846 4.7377924  4.0310332 1.560094 1.7210027
## 23   0.38076827 3.0562669 1.6113009  1.0246868 4.530600 0.9667363
## 24   0.20535295 2.9163293 4.1163801  3.3911153 2.241094 2.5286007
## 25   0.41877232 2.7303151 1.5616356  2.4506453 3.626496 1.3331132
## 26   0.26617565 3.2712843 3.1396021  2.5046344 3.107293 2.6373851
## 27   0.28769261 3.9226886 2.0225615  2.5273085 2.897739 1.4673821
## 28   0.39977557 2.9378013 4.5977776  2.2221782 2.777697 1.5796865
## 29   0.56682075 3.2977619 4.1540235  1.4287847 3.676300 2.6380399
## 30   0.52963158 3.4581461 3.8075875  2.7607609 3.345936 1.3725315
## 31   0.22833829 2.9526622 2.8162920  1.8302324 4.461217 1.6180715
## 32   0.20715467 2.6428462 0.6872940  0.6175158 5.945886 1.2083258
## 33   0.41239292 2.9599932 2.6683891  2.5953392 4.100208 1.7439009
## 34   0.17706607 1.9297199 1.6580187  1.4474162 3.547635 0.9385664
## 35   0.44076050 3.7674252 0.6451316  0.9195607 4.872259 2.9042943
## 36   0.31629873 2.1146493 3.7536880  3.0360594 2.838068 1.0597817
## 37   0.37035488 3.8020496 2.7486592  0.2643106 4.290151 1.7539316
## 38   0.18525000 2.7299318 1.3546404 -0.2523240 4.721493 1.2751736
## 39   0.50115577 3.1349456 3.2421449  3.6172850 2.243026 1.7142033
## 40   0.46397513 3.0130363 1.6878921  2.1082437 3.980620 1.8878141
## 41   0.35589931 3.8035799 2.6925134  2.7952193 2.433082 1.7502752
## 42   0.44021737 2.9537302 2.5509321  2.1958486 4.282946 1.6619111
## 43   0.32847707 2.7533998 2.1885928  2.1955374 4.179124 1.2966225
## 44   0.56599738 3.8086684 2.6614906  1.7883525 3.534684 0.9109111
## 45   0.63298561 5.4722538 2.6246473  2.0323609 4.245740 1.6019083
## 46   0.36671192 3.8373379 1.2029473  1.0808787 4.120857 1.4083544
## 47   0.65026343 4.4611344 3.3155709  3.2096415 3.275165 1.8197487
## 48   0.21525053 1.4784055 0.6087000  1.5537867 3.773753 1.6499578
## 49   0.27368491 1.1111501 1.2805981  1.9063158 4.896829 0.9122461
## 50   0.10696105 1.8148086 3.8605081  2.9060923 3.723161 2.1977074
## 51   0.33966450 3.4810637 3.1089231  3.2156230 2.771850 1.6027278
## 52   0.57280640 3.1872778 3.0340553  2.9384369 3.690575 1.7279573
## 53   0.15508574 2.1099147 2.3821604  2.0299025 3.666993 1.8155390
## 54   0.40500505 2.5808052 3.8734464  2.9063157 3.539234 1.6241724
## 55   0.12820991 2.1598440 3.3058396  2.2974267 3.559505 2.0272936
## 56   0.33136509 3.5787209 0.5054556  1.3450229 3.588936 2.6649975
## 57   0.37281298 1.9809393 2.4679268  2.0532096 2.693133 1.8264299
## 58   0.54951382 2.5396186 1.9478418  1.9405555 3.707789 1.2143895
## 59   0.42571472 3.8397686 3.4512906  2.5756583 2.748384 1.0366664
## 60   0.45118332 2.6936624 4.3733104  2.6169130 2.954446 0.4413846
## 61   0.53225789 2.6442805 4.3567514  2.7931458 3.160311 2.5012683
## 62   0.32424735 3.6281840 3.6375053  1.7813392 3.975108 1.1801099
## 63   0.56918841 3.2878176 2.3571347  1.9000358 3.707492 1.5158290
## 64   0.39689825 2.8722661 3.3891630  3.6161698 4.068442 1.9059061
## 65   0.50916945 3.0716802 3.0138930  3.3409739 3.174682 1.9282731
## 66   0.37381045 2.8613972 2.5346525  2.1169429 4.467001 1.1984569
## 67   0.44510070 3.4257946 3.1816739  2.7318242 3.732238 1.6831477
## 68   0.39299460 3.2010693 3.0060414  2.7628540 3.740873 2.4609643
## 69   0.44653298 3.1644675 3.6843226  3.1614193 3.279748 0.8922136
## 70   0.21899834 3.1967184 3.2764076  2.6424565 2.771732 2.2746857
## 71   0.25699825 4.2762230 3.7504485  2.6255869 3.432270 1.9718086
## 72   0.40767690 3.9634931 1.7851558  2.0298828 4.034073 0.8764307
## 73   0.47161399 3.3279451 5.5579604  3.6499364 2.663229 1.9991762
## 74   0.16250469 3.2773109 2.3015365  2.7213271 2.207900 0.6357077
## 75   0.21824252 1.9657893 3.6326756  2.3072120 3.714804 1.7842104
## 76   0.35899955 4.7632581 2.7294744  1.6372696 3.315482 1.7298316
## 77   0.27873590 3.7828931 3.4194274  2.6702150 3.061570 2.5602023
## 78   0.32614924 2.4435997 3.0606050  1.7580998 4.515989 1.0150848
## 79   0.44731840 2.6447258 2.4664493  3.3599532 3.161522 1.8540898
## 80   0.38029332 2.8780152 2.5960868  2.4639264 4.166040 1.5279508
## 81   0.29347514 2.0532644 2.5949659  2.3422173 4.566912 1.7580519
## 82   0.33449008 1.6763340 4.0745945  2.4576674 1.670886 0.3301944
## 83  -0.13333427 1.8646838 1.8605537  0.8743076 3.859640 1.2873846
## 84   0.35487008 3.1329063 5.1607506  4.4201740 3.263059 1.5195622
## 85   0.58713616 3.5871929 3.5483750  4.3854551 2.030597 0.9455332
## 86   0.45786163 3.1040782 5.0810000  2.4448840 2.710524 1.1693378
## 87   0.11330940 2.7322124 2.9335807  2.6275255 4.450236 2.6072942
## 88   0.44777502 3.9562751 2.8594018  1.2333628 5.032948 2.1101670
## 89   0.20234249 3.5441251 1.4882324  0.3852576 4.367248 0.4775579
## 90   0.34962746 3.0855190 2.6132050  3.0958749 3.614912 2.4456362
## 91   0.35472400 1.3014022 2.6016511  1.1155728 4.948843 1.1118416
## 92   0.23522461 2.2139784 2.9370279  2.1549473 4.138606 1.7861832
## 93   0.42014755 4.1320485 2.7372095  1.4261881 2.536445 0.7664355
## 94   0.15876267 3.2073345 1.5006009  0.2652437 4.404531 1.3220635
## 95  -0.09879649 0.8656131 2.7234710  0.6494040 5.941681 2.7164183
## 96   0.38591913 4.9543775 3.8013379  2.7004684 2.425454 1.7873045
## 97   0.44230619 3.2033360 4.2147040  3.6971513 2.430067 1.4020194
## 98   0.29716688 2.3867630 2.9367032  2.4687254 4.053484 1.4651382
## 99   0.25872796 2.2176660 1.2114582  1.1411757 4.777005 1.5079464
## 100  0.06517719 2.7807617 3.4760948  2.0910964 4.221674 2.1545484
## 101  0.16162849 3.8400098 1.7971752  2.4634779 2.940266 1.0140635
## 102  0.64606063 4.3452532 4.0757378  4.4425493 2.503920 1.4400385
## 103  0.43953190 2.6128498 2.7762497  2.4062207 3.726635 0.2829370
## 104  0.32010790 3.0664919 2.4460013  2.0391555 3.790884 0.8317398
## 105  0.23294638 2.8678142 3.3969138  3.1130449 2.096275 1.6124933
## 106  0.50169163 3.1905757 3.6799971  3.4794417 2.458951 1.5971075
## 107  0.29363188 2.6876792 2.9182203  2.2699264 1.957908 2.5447356
## 108  0.26214714 3.4488353 3.8895770  2.8992699 2.788475 1.6974445
## 109  0.37009802 3.7469694 2.9289129  2.9753900 2.931447 1.8848354
## 110  0.29730729 3.1534935 3.3337636  3.0937892 2.581927 2.3980973
## 111  0.24470529 3.2782295 2.8703885  2.2915569 3.751316 1.5109690
## 112  0.54659869 3.9875404 4.8961430  4.0922097 1.973596 1.2552789
## 113  0.10697366 1.7824763 1.9450107  2.5996601 4.482268 2.2628556
## 114  0.26811871 2.5759431 2.8436596  0.8909314 3.820002 1.0753586
## 115  0.43803765 2.4273121 3.3702456  2.6467107 4.705230 2.7045322
## 116 -0.06773831 1.0890615 2.1039908  1.6805607 3.898468 1.4121238
## 117  0.67609125 3.4169175 3.0278088  2.4529501 3.759270 2.6841150
## 118  0.22489645 3.3639686 4.2235025  3.4781409 2.397229 1.2734251
## 119  0.48300880 2.7120258 3.2456654  2.1793229 3.866140 2.4408081
## 120  0.21667980 3.0603200 0.7108609  1.4644661 5.260412 1.9287701
## 121  0.06512801 1.5886292 2.3749889  0.9180135 4.825579 1.5245304
## 122  0.61003798 3.6223559 2.4047411  2.1696687 2.872875 1.8673206
## 123  0.22977532 3.0189730 2.4342990  2.1243346 3.603260 1.0869989
## 124  0.36422147 2.7425189 3.1556307  1.5394070 4.365395 2.0480712
## 125  0.22933372 2.2046979 2.6570211  2.8655072 2.491654 1.0139864
## 126  0.43238708 4.3102068 1.4277537  1.8567860 3.762495 1.5152676
## 127  0.38990877 2.7218866 2.2477225  1.0646075 4.641716 1.0071908
## 128  0.21753221 1.5882455 1.7407732  1.8213958 3.979175 2.0259607
## 129  0.24771023 1.8672735 2.1881830  1.7507315 4.963161 1.0898960
## 130  0.75408295 4.1289706 3.5474464  3.7791487 2.890496 1.5877356
## 131  0.41644783 2.3299547 3.2208705  2.4181467 4.168489 2.0548755
## 132  0.51769871 4.8743013 3.0157732  3.4737052 3.199802 1.1111757
## 133  0.35717215 2.5981651 2.8779430  2.8980202 3.187424 1.7153314
## 134  0.26920553 3.6847735 3.5523502  2.1903271 2.951610 1.5712546
## 135  0.16434131 1.2258814 3.0293592  1.9656563 3.951977 1.6376233
## 136  0.31628364 2.9034206 1.6436139  1.1249672 4.345822 2.1125579
## 137  0.43040767 3.5183625 3.1331817  1.5718843 3.896956 0.9777469
## 138  0.09448973 1.9683952 2.4498808  1.8165286 3.656073 1.3069823
## 139  0.35002893 3.5852879 2.5912530  1.6491977 5.409283 1.5340238
## 140  0.42296660 3.0640201 3.3574675  2.0421916 3.569581 0.8512156
## 141  0.24932068 3.4213164 2.7485416  3.6280473 2.312726 1.2516653
## 142  0.53062494 3.6640311 5.0907192  4.5694108 1.350203 1.8851816
## 143  0.27962118 3.3932218 2.7264126  1.6711386 3.765364 2.2954985
## 144  0.23322586 3.3279561 3.1592797  1.8154681 1.526867 2.0054852
## 145  0.37962928 2.9616314 3.0021556  2.2003911 3.365035 1.6114163
## 146  0.58980078 3.4742094 4.9949216  3.5702922 1.845780 1.9212095
## 147  0.19270590 2.2602334 2.8233585  0.9669035 4.679490 2.3836889
## 148  0.31012390 2.1745958 4.0843806  3.6022376 3.523946 1.6006189
## 149  0.32504460 3.3473480 2.5347074  2.3469577 3.709119 1.5668096
## 150  0.15226205 2.0648724 5.0295232  2.4532674 2.093509 2.0246498
## 151  0.28115818 1.9376116 3.6657196  2.5134560 2.871831 1.2246409
## 152  0.31936688 3.2432213 4.9907982  2.7616598 4.100608 1.8425462
## 153  0.26239276 3.3908566 2.7704343  2.4932497 2.810725 2.4545378
## 154  0.18193724 3.1099861 2.9947179  3.4509396 2.180071 1.4960772
## 155  0.24134651 2.5263768 2.2951753  1.7940080 3.185113 1.7917425
## 156  0.22502241 2.8972357 4.7873242  4.3623474 1.775025 1.0875423</code></pre>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="SimpleMed.html#cb262-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.2     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ ggplot2::%+%()   masks psych::%+%()
## ✖ ggplot2::alpha() masks psych::alpha()
## ✖ dplyr::filter()  masks stats::filter()
## ✖ dplyr::lag()     masks stats::lag()
## ✖ dplyr::select()  masks MASS::select()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="SimpleMed.html#cb264-1" tabindex="-1"></a>Kim_df <span class="ot">&lt;-</span> Kim_df<span class="sc">%&gt;%</span></span>
<span id="cb264-2"><a href="SimpleMed.html#cb264-2" tabindex="-1"></a>  as.data.frame <span class="sc">%&gt;%</span></span>
<span id="cb264-3"><a href="SimpleMed.html#cb264-3" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">REMS =</span> V1, <span class="at">CMI =</span> V2, <span class="at">ANX =</span> V3, <span class="at">DEP =</span> V4, <span class="at">PWB =</span> V5, <span class="at">HlpSk =</span> V6)</span></code></pre></div>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="SimpleMed.html#cb265-1" tabindex="-1"></a><span class="co">#look at the first 6 rows of the new df</span></span>
<span id="cb265-2"><a href="SimpleMed.html#cb265-2" tabindex="-1"></a><span class="fu">head</span>(Kim_df)</span></code></pre></div>
<pre><code>##        REMS      CMI      ANX      DEP      PWB    HlpSk
## 1 0.3148008 3.774219 3.988524 2.656128 3.902766 1.228220
## 2 0.1250438 2.463040 3.159118 1.787321 4.434146 1.499028
## 3 0.1778466 1.837684 3.817689 2.548137 3.299962 1.312602
## 4 0.7541549 4.826817 3.296125 2.170052 3.274046 1.485793
## 5 0.2847385 2.162275 2.983767 2.621381 3.851441 1.433081
## 6 0.3749818 4.107085 3.432472 3.095121 2.880348 1.941779</code></pre>
<p>Let’s check the descriptives to see if they align with those in the article.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="SimpleMed.html#cb267-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb267-2"><a href="SimpleMed.html#cb267-2" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Kim_df)</span></code></pre></div>
<pre><code>##       vars   n mean   sd median trimmed  mad   min  max range  skew kurtosis
## REMS     1 156 0.34 0.16   0.33    0.34 0.16 -0.13 0.75  0.89  0.03     0.16
## CMI      2 156 3.00 0.83   3.06    3.00 0.72  0.87 5.47  4.61  0.01     0.13
## ANX      3 156 2.98 0.99   2.99    2.98 0.83  0.51 5.56  5.05 -0.02     0.12
## DEP      4 156 2.36 0.90   2.41    2.36 0.83 -0.25 4.57  4.82 -0.05     0.10
## PWB      5 156 3.50 0.90   3.61    3.51 0.97  1.35 5.95  4.60 -0.04    -0.23
## HlpSk    6 156 1.64 0.53   1.61    1.63 0.49  0.28 2.90  2.62  0.07    -0.24
##         se
## REMS  0.01
## CMI   0.07
## ANX   0.08
## DEP   0.07
## PWB   0.07
## HlpSk 0.04</code></pre>
<p>There are a number of reasons I love the Kim et al. <span class="citation">(<a href="#ref-kim_racial_2017">2017</a>)</span> manuscript. One is that their approach was openly one that tested <em>alternate models</em>. Byrne <span class="citation">(<a href="#ref-byrne_structural_2016">2016</a>)</span> credits Joreskog <span class="citation">(<a href="#ref-bollen_testing_1993">Joreskog, 1993</a>)</span> with classifying the researcher’s model testing approach in three ways. If someone is <em>strictly confirmatory</em>, they only test the model they proposed and then accept or reject it without further alteration. While this is the tradition of null hypothesis significance testing, it contributes to the “file drawer problem” of unpublished, non-significant, findings. Additionally, the data are them discarded – potentially losing valuable resource. The <em>alternative models</em> approach is to propose a handful of competing models before beginning the analysis and then evaluating to see if one model is superior to the other. The third option is <em>model generating</em>. In this case the researcher begins with a theoretically proposed model. In the presence of poor fit, the researcher seeks to identify the source of misfit – respecifying it to best represent the sample data. The researcher must use caution to produce a model that fits well and is meaningful.</p>
<p>Several of the Kim et al. <span class="citation">(<a href="#ref-kim_racial_2017">2017</a>)</span> models were non-significant. To demonstrate a model that is statistically significant, I will test the hypothesis that racial microaggressions (REMS, the X variable) influence depression (DEP, the Y variable) through cultural mistrust (CMI, the M variable).</p>
<div class="float">
<img src="images/SimpleMed/Kim_SimpMed.jpg" alt="Image of the simple mediation model from Kim et al." />
<div class="figcaption">Image of the simple mediation model from Kim et al.</div>
</div>
</div>
<div id="specify-the-model-in-lavaan" class="section level3 hasAnchor" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Specify the Model in <em>lavaan</em><a href="SimpleMed.html#specify-the-model-in-lavaan" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I am a big fan of “copying the model.” In specifying my model I used our simple mediation template above</p>
<ul>
<li>replaced the Y, X, and M with variables names</li>
<li>replacing the name of the df</li>
<li>updated the object names (so I could use them in the same .rmd file)</li>
</ul>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="SimpleMed.html#cb269-1" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb269-2"><a href="SimpleMed.html#cb269-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">210410</span>) <span class="co">#reset in case you choose to separate these sections</span></span>
<span id="cb269-3"><a href="SimpleMed.html#cb269-3" tabindex="-1"></a>Kim_model <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb269-4"><a href="SimpleMed.html#cb269-4" tabindex="-1"></a><span class="st">          PWB ~ b*CMI + c_p*REMS </span></span>
<span id="cb269-5"><a href="SimpleMed.html#cb269-5" tabindex="-1"></a><span class="st">          CMI ~a*REMS</span></span>
<span id="cb269-6"><a href="SimpleMed.html#cb269-6" tabindex="-1"></a><span class="st">          </span></span>
<span id="cb269-7"><a href="SimpleMed.html#cb269-7" tabindex="-1"></a><span class="st">          indirect :=  a*b</span></span>
<span id="cb269-8"><a href="SimpleMed.html#cb269-8" tabindex="-1"></a><span class="st">          direct  := c_p</span></span>
<span id="cb269-9"><a href="SimpleMed.html#cb269-9" tabindex="-1"></a><span class="st">          total_c  := c_p + (a*b)</span></span>
<span id="cb269-10"><a href="SimpleMed.html#cb269-10" tabindex="-1"></a><span class="st">          &#39;</span></span></code></pre></div>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="SimpleMed.html#cb270-1" tabindex="-1"></a>Kim_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(Kim_model, <span class="at">data =</span> Kim_df, <span class="at">se=</span><span class="st">&quot;bootstrap&quot;</span>, <span class="at">missing=</span> <span class="st">&#39;fiml&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="SimpleMed.html#cb271-1" tabindex="-1"></a>Kim_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(Kim_fit, <span class="at">standardized=</span>T, <span class="at">rsq=</span>T, <span class="at">fit=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span>
<span id="cb271-2"><a href="SimpleMed.html#cb271-2" tabindex="-1"></a>Kim_ParamEsts <span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(Kim_fit, <span class="at">boot.ci.type =</span> <span class="st">&quot;bca.simple&quot;</span>, <span class="at">standardized=</span><span class="cn">TRUE</span>)</span>
<span id="cb271-3"><a href="SimpleMed.html#cb271-3" tabindex="-1"></a>Kim_summary</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         7
## 
##   Number of observations                           156
##   Number of missing patterns                         1
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Model Test Baseline Model:
## 
##   Test statistic                                81.362
##   Degrees of freedom                                 3
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                       1.000
##                                                       
##   Robust Comparative Fit Index (CFI)             1.000
##   Robust Tucker-Lewis Index (TLI)                1.000
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -355.521
##   Loglikelihood unrestricted model (H1)       -355.521
##                                                       
##   Akaike (AIC)                                 725.042
##   Bayesian (BIC)                               746.391
##   Sample-size adjusted Bayesian (SABIC)        724.234
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: RMSEA &lt;= 0.050                       NA
##   P-value H_0: RMSEA &gt;= 0.080                       NA
##                                                       
##   Robust RMSEA                                   0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: Robust RMSEA &lt;= 0.050                NA
##   P-value H_0: Robust RMSEA &gt;= 0.080                NA
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                            Bootstrap
##   Number of requested bootstrap draws             1000
##   Number of successful bootstrap draws            1000
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   PWB ~                                                                 
##     CMI        (b)   -0.220    0.108   -2.046    0.041   -0.423   -0.006
##     REMS     (c_p)   -0.732    0.513   -1.427    0.154   -1.786    0.270
##   CMI ~                                                                 
##     REMS       (a)    3.061    0.300   10.188    0.000    2.475    3.655
##    Std.lv  Std.all
##                   
##    -0.220   -0.203
##    -0.732   -0.130
##                   
##     3.061    0.590
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .PWB               4.410    0.272   16.220    0.000    3.821    4.910
##    .CMI               1.959    0.118   16.598    0.000    1.717    2.187
##    Std.lv  Std.all
##     4.410    4.916
##     1.959    2.368
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .PWB               0.733    0.082    8.912    0.000    0.564    0.889
##    .CMI               0.446    0.050    8.979    0.000    0.349    0.549
##    Std.lv  Std.all
##     0.733    0.911
##     0.446    0.652
## 
## R-Square:
##                    Estimate
##     PWB               0.089
##     CMI               0.348
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##     indirect         -0.675    0.330   -2.043    0.041   -1.314   -0.018
##     direct           -0.732    0.513   -1.426    0.154   -1.786    0.270
##     total_c          -1.406    0.421   -3.339    0.001   -2.192   -0.545
##    Std.lv  Std.all
##    -0.675   -0.120
##    -0.732   -0.130
##    -1.406   -0.250</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="SimpleMed.html#cb273-1" tabindex="-1"></a>Kim_ParamEsts</span></code></pre></div>
<pre><code>##         lhs op       rhs    label    est    se      z pvalue ci.lower ci.upper
## 1       PWB  ~       CMI        b -0.220 0.108 -2.046  0.041   -0.435   -0.013
## 2       PWB  ~      REMS      c_p -0.732 0.513 -1.427  0.154   -1.852    0.202
## 3       CMI  ~      REMS        a  3.061 0.300 10.188  0.000    2.467    3.643
## 4       PWB ~~       PWB           0.733 0.082  8.912  0.000    0.595    0.935
## 5       CMI ~~       CMI           0.446 0.050  8.979  0.000    0.362    0.564
## 6      REMS ~~      REMS           0.025 0.000     NA     NA    0.025    0.025
## 7       PWB ~1                     4.410 0.272 16.220  0.000    3.880    4.934
## 8       CMI ~1                     1.959 0.118 16.598  0.000    1.703    2.185
## 9      REMS ~1                     0.340 0.000     NA     NA    0.340    0.340
## 10 indirect :=       a*b indirect -0.675 0.330 -2.043  0.041   -1.364   -0.077
## 11   direct :=       c_p   direct -0.732 0.513 -1.426  0.154   -1.852    0.202
## 12  total_c := c_p+(a*b)  total_c -1.406 0.421 -3.339  0.001   -2.263   -0.605
##    std.lv std.all std.nox
## 1  -0.220  -0.203  -0.203
## 2  -0.732  -0.130  -0.816
## 3   3.061   0.590   3.699
## 4   0.733   0.911   0.911
## 5   0.446   0.652   0.652
## 6   0.025   1.000   0.025
## 7   4.410   4.916   4.916
## 8   1.959   2.368   2.368
## 9   0.340   2.132   0.340
## 10 -0.675  -0.120  -0.752
## 11 -0.732  -0.130  -0.816
## 12 -1.406  -0.250  -1.568</code></pre>
</div>
<div id="interpret-the-output-1" class="section level3 hasAnchor" number="5.5.3">
<h3><span class="header-section-number">5.5.3</span> Interpret the Output<a href="SimpleMed.html#interpret-the-output-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Overall, our model accounted for of the variance in the IV and of the variance in the mediator.</li>
<li>a path = 3.061, <span class="math inline">\(p\)</span> = 0.000</li>
<li>b path = -0.220, <span class="math inline">\(p\)</span> = 0.041</li>
<li>the indirect effect is a product of the a and b paths (-0.675); while we don’t hand calculate it’s significance, we see that it is <span class="math inline">\(p\)</span> = 0.041; the bias-corrected bootstrapped confidence intervals can sometimes be more lenient than <span class="math inline">\(p\)</span> values; it is important they don’t cross zero. They don’t: CI95 -1.364 to -0.077<br />
</li>
<li>the direct effect (c’, c prime, or c_p) is the isolated effect of X on Y when including M. We hope this value is LOWER than the total effect because this means that including M shared some of the variance in predicting Y: c’ = -0.732, <span class="math inline">\(p\)</span> = 0.154, and it is no longer signifcant.</li>
<li>we also see the total effect; this value is</li>
<li>identical to the value of simply predicting Y on X (with no M it the model)</li>
<li>the value of a(b) + c_p: 3.061(-0.220) + -0.732 = -1.406 (<span class="math inline">\(p\)</span> = 0.001)</li>
</ul>
</div>
<div id="a-figure-and-a-table" class="section level3 hasAnchor" number="5.5.4">
<h3><span class="header-section-number">5.5.4</span> A Figure and a Table<a href="SimpleMed.html#a-figure-and-a-table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I make it a practice to immediately plot what I did. Because the plotting packages use our models, this can be a helpful self-check of our work.</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="SimpleMed.html#cb275-1" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span>
<span id="cb275-2"><a href="SimpleMed.html#cb275-2" tabindex="-1"></a><span class="fu">semPaths</span>(Kim_fit, <span class="co">#must identiy the model you want to map</span></span>
<span id="cb275-3"><a href="SimpleMed.html#cb275-3" tabindex="-1"></a>         <span class="at">what =</span> <span class="st">&quot;est&quot;</span>, <span class="co">#&quot;est&quot; plots the estimates, but keeps it greyscale with no fading</span></span>
<span id="cb275-4"><a href="SimpleMed.html#cb275-4" tabindex="-1"></a>         <span class="co">#whatLabels = &quot;stand&quot;, #&quot;stand&quot; changes to standardized values</span></span>
<span id="cb275-5"><a href="SimpleMed.html#cb275-5" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">&#39;tree&#39;</span>, <span class="at">rotation =</span> <span class="dv">2</span>, <span class="co">#together, puts predictors on left, IVs on right </span></span>
<span id="cb275-6"><a href="SimpleMed.html#cb275-6" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.00</span>, <span class="co">#font size of parameter values</span></span>
<span id="cb275-7"><a href="SimpleMed.html#cb275-7" tabindex="-1"></a>         <span class="co">#edge.color = &quot;black&quot;, #overwrites the green/black coloring</span></span>
<span id="cb275-8"><a href="SimpleMed.html#cb275-8" tabindex="-1"></a>         <span class="at">sizeMan=</span><span class="dv">10</span>, <span class="co">#size of squares/observed/&quot;manifest&quot; variables</span></span>
<span id="cb275-9"><a href="SimpleMed.html#cb275-9" tabindex="-1"></a>         <span class="at">fade=</span><span class="cn">FALSE</span>, <span class="co">#if TRUE, there lines are faded such that weaker lines correspond with lower values -- a cool effect, but tough for journals</span></span>
<span id="cb275-10"><a href="SimpleMed.html#cb275-10" tabindex="-1"></a>         <span class="at">esize=</span><span class="dv">2</span>, </span>
<span id="cb275-11"><a href="SimpleMed.html#cb275-11" tabindex="-1"></a>         <span class="at">asize=</span><span class="dv">3</span>,</span>
<span id="cb275-12"><a href="SimpleMed.html#cb275-12" tabindex="-1"></a>         <span class="co">#label.prop = .5,</span></span>
<span id="cb275-13"><a href="SimpleMed.html#cb275-13" tabindex="-1"></a>         <span class="at">label.font =</span> <span class="fl">2.5</span>, <span class="co">#controls size (I think) of font for labels</span></span>
<span id="cb275-14"><a href="SimpleMed.html#cb275-14" tabindex="-1"></a>         <span class="at">label.scale =</span> <span class="cn">TRUE</span>, <span class="co">#if false, the labels will not scale to fit inside the nodes</span></span>
<span id="cb275-15"><a href="SimpleMed.html#cb275-15" tabindex="-1"></a>         <span class="at">nDigits =</span> <span class="dv">3</span>, <span class="co">#decimal places (default is 2)</span></span>
<span id="cb275-16"><a href="SimpleMed.html#cb275-16" tabindex="-1"></a>         <span class="at">residuals =</span> <span class="cn">FALSE</span>,<span class="co">#excludes residuals (and variances) from the path diagram</span></span>
<span id="cb275-17"><a href="SimpleMed.html#cb275-17" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="co">#specifies how many characters to abbreviate variable lables; default is 3.  If 0, uses your entire variable label and adjusts fontsize (which could be a downside)</span></span>
<span id="cb275-18"><a href="SimpleMed.html#cb275-18" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>, <span class="co">#gets rid of those annoying triangles (intercepts) in the path diagram)</span></span>
<span id="cb275-19"><a href="SimpleMed.html#cb275-19" tabindex="-1"></a>)</span>
<span id="cb275-20"><a href="SimpleMed.html#cb275-20" tabindex="-1"></a><span class="fu">title</span>(<span class="st">&quot;Depression by Racial Microaggressions via Cultural Mistrust&quot;</span>)</span></code></pre></div>
<p><img src="05-SimpleMed_files/figure-html/semPLOT%20of%20PMI-1.png" width="672" /></p>
<p>The semTable package can be used to write results to an outfile.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="SimpleMed.html#cb276-1" tabindex="-1"></a><span class="fu">library</span>(semTable)</span>
<span id="cb276-2"><a href="SimpleMed.html#cb276-2" tabindex="-1"></a>fitTab1 <span class="ot">&lt;-</span> <span class="fu">semTable</span>(Kim_fit, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">&quot;est&quot;</span>, <span class="st">&quot;se&quot;</span>, <span class="st">&quot;p&quot;</span>, <span class="st">&quot;rsquare&quot;</span>),  <span class="at">columnLabels =</span> <span class="fu">c</span>(<span class="at">eststars =</span> <span class="st">&quot;Estimate&quot;</span>), <span class="at">paramSets =</span> <span class="fu">c</span>(<span class="st">&quot;composites&quot;</span>, <span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;slopes&quot;</span>, <span class="st">&quot;intercepts&quot;</span>, <span class="st">&quot;residualvariances&quot;</span>), <span class="at">file =</span> <span class="st">&quot;pmi_fitTABLE&quot;</span>, <span class="at">type =</span> <span class="st">&quot;csv&quot;</span>, <span class="at">print.results =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>For the purpose of the OER, and because it’s good trainng, I also think it can be useful to make our own table. For me, it facilitates my conceptual understanding of (a) what the statistic is doing and (b) the results of our specific data.</p>
<p>Table 1</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Model Coefficients Assessing Cultural Mistrust as a Mediator Between Racial Microaggressions and Well-Being</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col width="22%" />
<col width="36%" />
<col width="6%" />
<col width="35%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="center">Cultural Mistrust (M)</td>
<td align="center"></td>
<td align="center">Well-Being (Y)</td>
</tr>
</tbody>
</table>
<table style="width:100%;">
<colgroup>
<col width="15%" />
<col width="6%" />
<col width="11%" />
<col width="12%" />
<col width="12%" />
<col width="6%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left">Antecedent</td>
<td align="center">path</td>
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center"><span class="math inline">\(SE\)</span></td>
<td align="center"><span class="math inline">\(p\)</span></td>
<td align="center">path</td>
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center"><span class="math inline">\(SE\)</span></td>
<td align="center"><span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td align="left">constant</td>
<td align="center"><span class="math inline">\(i_{M}\)</span></td>
<td align="center">1.959</td>
<td align="center">0.118</td>
<td align="center">0.000</td>
<td align="center"><span class="math inline">\(i_{Y}\)</span></td>
<td align="center">4.410</td>
<td align="center">0.272</td>
<td align="center">0.000</td>
</tr>
<tr class="odd">
<td align="left">REMS (X)</td>
<td align="center"><span class="math inline">\(a\)</span></td>
<td align="center">3.061</td>
<td align="center">0.300</td>
<td align="center">0.000</td>
<td align="center"><span class="math inline">\(c&#39;\)</span></td>
<td align="center">-0.732</td>
<td align="center">0.513</td>
<td align="center">0.154</td>
</tr>
<tr class="even">
<td align="left">CMI (M)</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(b\)</span></td>
<td align="center">-0.220</td>
<td align="center">0.108</td>
<td align="center">0.041</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="22%" />
<col width="36%" />
<col width="6%" />
<col width="35%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="center"><span class="math inline">\(R^2\)</span> =</td>
<td align="center"></td>
<td align="center"><span class="math inline">\(R^2\)</span> =</td>
</tr>
</tbody>
</table>
</div>
<div id="results-5" class="section level3 hasAnchor" number="5.5.5">
<h3><span class="header-section-number">5.5.5</span> Results<a href="SimpleMed.html#results-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A simple mediation model examined the degree to which cultural mistrust mediated the relation of racial microaggressions on depressive symptoms Using the <em>lavaan</em> package (v 0.6-7) in R, coefficients for each path, the indirect effect, and total effects were calculated. These values are presented in Table 1 and illustrated in Figure 1. Results suggested that of the variance in cultural mistrust and of the variance in depression were accounted for by the model. When the mediator was included in the model, bias-corrected confidence intervals surrounding the indirect effect (<span class="math inline">\(B\)</span> = -0.675, <span class="math inline">\(p\)</span> = 0.041, CI95 -1.364 to -0.077) were not quite statistically significant. Consistent with mediation, the value of the total effect was larger in magnitude and statistically significant (<span class="math inline">\(B\)</span> = -1.406, <span class="math inline">\(p\)</span> = 0.001, CI95 -2.263 to -0.605) than the smaller and non-significant direct effect (<span class="math inline">\(B\)</span> = -0.732, <span class="math inline">\(p\)</span> = 0.154, CI95 -1.852 to 0.202).</p>
</div>
</div>
<div id="considering-covariates" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Considering Covariates<a href="SimpleMed.html#considering-covariates" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hayes Chapter 4 <span class="citation">(<a href="#ref-hayes_introduction_2018">2018</a>)</span> considers the role of covariates (e.g., other variables that could account for some of the variance in the model). When previous research (or commonsense, or detractors) suggest you should include them…its worth a try. If they are non-significant and/or your variables continue to explain variance over-and-above their contribution, then you have gained ground in ruling out plausible rival hypotheses and are adding to causal evidence.</p>
<p>They are relatively easy to specify in <em>lavaan</em>. Just look at to where the arrows point and then write the path!</p>
<p>Let’s say we are concerned that anxiety covaries with cultural mistrust and PWB We’ll add it as a covariate to both.</p>
<div class="float">
<img src="images/SimpleMed/Kim_wCovs.jpg" alt="Image of the simple mediation model from Kim et al." />
<div class="figcaption">Image of the simple mediation model from Kim et al.</div>
</div>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="SimpleMed.html#cb277-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">210410</span>)</span>
<span id="cb277-2"><a href="SimpleMed.html#cb277-2" tabindex="-1"></a>Kim_fit_covs <span class="ot">&lt;-</span> <span class="st">&#39;</span></span>
<span id="cb277-3"><a href="SimpleMed.html#cb277-3" tabindex="-1"></a><span class="st">          PWB ~ b*CMI + c_p*REMS </span></span>
<span id="cb277-4"><a href="SimpleMed.html#cb277-4" tabindex="-1"></a><span class="st">          CMI ~a*REMS</span></span>
<span id="cb277-5"><a href="SimpleMed.html#cb277-5" tabindex="-1"></a><span class="st">          CMI ~ covM*ANX</span></span>
<span id="cb277-6"><a href="SimpleMed.html#cb277-6" tabindex="-1"></a><span class="st">          PWB ~ covY*ANX</span></span>
<span id="cb277-7"><a href="SimpleMed.html#cb277-7" tabindex="-1"></a></span>
<span id="cb277-8"><a href="SimpleMed.html#cb277-8" tabindex="-1"></a><span class="st">          indirect :=  a*b</span></span>
<span id="cb277-9"><a href="SimpleMed.html#cb277-9" tabindex="-1"></a><span class="st">          direct  := c_p</span></span>
<span id="cb277-10"><a href="SimpleMed.html#cb277-10" tabindex="-1"></a><span class="st">          total_c  := c_p + (a*b)</span></span>
<span id="cb277-11"><a href="SimpleMed.html#cb277-11" tabindex="-1"></a><span class="st">          &#39;</span></span>
<span id="cb277-12"><a href="SimpleMed.html#cb277-12" tabindex="-1"></a>Kim_fit_covs <span class="ot">&lt;-</span> <span class="fu">sem</span>(Kim_fit_covs, <span class="at">data =</span> Kim_df, <span class="at">se=</span><span class="st">&quot;bootstrap&quot;</span>, <span class="at">missing =</span> <span class="st">&#39;fiml&#39;</span>)</span>
<span id="cb277-13"><a href="SimpleMed.html#cb277-13" tabindex="-1"></a>Kcov_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(Kim_fit_covs, <span class="at">standardized=</span>T, <span class="at">rsq=</span>T, <span class="at">fit=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span>
<span id="cb277-14"><a href="SimpleMed.html#cb277-14" tabindex="-1"></a>Kcov_ParEsts<span class="ot">&lt;-</span> <span class="fu">parameterEstimates</span>(Kim_fit_covs, <span class="at">boot.ci.type =</span> <span class="st">&quot;bca.simple&quot;</span>, <span class="at">standardized=</span><span class="cn">TRUE</span>)</span>
<span id="cb277-15"><a href="SimpleMed.html#cb277-15" tabindex="-1"></a>Kcov_sum</span></code></pre></div>
<pre><code>## lavaan 0.6.16 ended normally after 1 iteration
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
## 
##   Number of observations                           156
##   Number of missing patterns                         1
## 
## Model Test User Model:
##                                                       
##   Test statistic                                 0.000
##   Degrees of freedom                                 0
## 
## Model Test Baseline Model:
## 
##   Test statistic                               134.067
##   Degrees of freedom                                 5
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                       1.000
##                                                       
##   Robust Comparative Fit Index (CFI)             1.000
##   Robust Tucker-Lewis Index (TLI)                1.000
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -329.168
##   Loglikelihood unrestricted model (H1)       -329.168
##                                                       
##   Akaike (AIC)                                 676.337
##   Bayesian (BIC)                               703.785
##   Sample-size adjusted Bayesian (SABIC)        675.297
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: RMSEA &lt;= 0.050                       NA
##   P-value H_0: RMSEA &gt;= 0.080                       NA
##                                                       
##   Robust RMSEA                                   0.000
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.000
##   P-value H_0: Robust RMSEA &lt;= 0.050                NA
##   P-value H_0: Robust RMSEA &gt;= 0.080                NA
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                            Bootstrap
##   Number of requested bootstrap draws             1000
##   Number of successful bootstrap draws            1000
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##   PWB ~                                                                 
##     CMI        (b)   -0.250    0.092   -2.702    0.007   -0.445   -0.078
##     REMS     (c_p)    0.131    0.479    0.273    0.785   -0.830    1.103
##   CMI ~                                                                 
##     REMS       (a)    3.109    0.318    9.762    0.000    2.483    3.732
##     ANX     (covM)   -0.030    0.058   -0.515    0.607   -0.144    0.083
##   PWB ~                                                                 
##     ANX     (covY)   -0.480    0.064   -7.502    0.000   -0.606   -0.355
##    Std.lv  Std.all
##                   
##    -0.250   -0.230
##     0.131    0.023
##                   
##     3.109    0.599
##    -0.030   -0.036
##                   
##    -0.480   -0.528
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .PWB               5.636    0.277   20.365    0.000    5.091    6.157
##    .CMI               2.032    0.185   10.992    0.000    1.647    2.376
##    Std.lv  Std.all
##     5.636    6.283
##     2.032    2.457
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##    .PWB               0.524    0.058    9.086    0.000    0.404    0.631
##    .CMI               0.445    0.050    8.926    0.000    0.345    0.548
##    Std.lv  Std.all
##     0.524    0.651
##     0.445    0.651
## 
## R-Square:
##                    Estimate
##     PWB               0.349
##     CMI               0.349
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|) ci.lower ci.upper
##     indirect         -0.776    0.290   -2.680    0.007   -1.376   -0.223
##     direct            0.131    0.479    0.273    0.785   -0.830    1.103
##     total_c          -0.646    0.404   -1.600    0.110   -1.436    0.099
##    Std.lv  Std.all
##    -0.776   -0.138
##     0.131    0.023
##    -0.646   -0.115</code></pre>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="SimpleMed.html#cb279-1" tabindex="-1"></a>Kcov_ParEsts</span></code></pre></div>
<pre><code>##         lhs op       rhs    label    est    se      z pvalue ci.lower ci.upper
## 1       PWB  ~       CMI        b -0.250 0.092 -2.702  0.007   -0.456   -0.085
## 2       PWB  ~      REMS      c_p  0.131 0.479  0.273  0.785   -0.863    1.070
## 3       CMI  ~      REMS        a  3.109 0.318  9.762  0.000    2.433    3.718
## 4       CMI  ~       ANX     covM -0.030 0.058 -0.515  0.607   -0.143    0.083
## 5       PWB  ~       ANX     covY -0.480 0.064 -7.502  0.000   -0.601   -0.353
## 6       PWB ~~       PWB           0.524 0.058  9.086  0.000    0.438    0.669
## 7       CMI ~~       CMI           0.445 0.050  8.926  0.000    0.365    0.568
## 8      REMS ~~      REMS           0.025 0.000     NA     NA    0.025    0.025
## 9      REMS ~~       ANX           0.041 0.000     NA     NA    0.041    0.041
## 10      ANX ~~       ANX           0.974 0.000     NA     NA    0.974    0.974
## 11      PWB ~1                     5.636 0.277 20.365  0.000    5.083    6.152
## 12      CMI ~1                     2.032 0.185 10.992  0.000    1.620    2.357
## 13     REMS ~1                     0.340 0.000     NA     NA    0.340    0.340
## 14      ANX ~1                     2.980 0.000     NA     NA    2.980    2.980
## 15 indirect :=       a*b indirect -0.776 0.290 -2.680  0.007   -1.380   -0.226
## 16   direct :=       c_p   direct  0.131 0.479  0.273  0.785   -0.863    1.070
## 17  total_c := c_p+(a*b)  total_c -0.646 0.404 -1.600  0.110   -1.512    0.035
##    std.lv std.all std.nox
## 1  -0.250  -0.230  -0.230
## 2   0.131   0.023   0.146
## 3   3.109   0.599   3.758
## 4  -0.030  -0.036  -0.036
## 5  -0.480  -0.528  -0.535
## 6   0.524   0.651   0.651
## 7   0.445   0.651   0.651
## 8   0.025   1.000   0.025
## 9   0.041   0.260   0.041
## 10  0.974   1.000   0.974
## 11  5.636   6.283   6.283
## 12  2.032   2.457   2.457
## 13  0.340   2.132   0.340
## 14  2.980   3.020   2.980
## 15 -0.776  -0.138  -0.866
## 16  0.131   0.023   0.146
## 17 -0.646  -0.115  -0.720</code></pre>
<div id="a-figure-and-a-table-1" class="section level3 hasAnchor" number="5.6.1">
<h3><span class="header-section-number">5.6.1</span> A Figure and a Table<a href="SimpleMed.html#a-figure-and-a-table-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s look at a figure to see see if we did what we think we did. And to also get a graphic representation of our results. The semplot package does this easily, but the figure is more statistical than conceptual and would require more tinkering for a journal article.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="SimpleMed.html#cb281-1" tabindex="-1"></a><span class="fu">semPaths</span>(Kim_fit_covs, <span class="co">#must identiy the model you want to map</span></span>
<span id="cb281-2"><a href="SimpleMed.html#cb281-2" tabindex="-1"></a>         <span class="at">what =</span> <span class="st">&quot;est&quot;</span>, <span class="co">#&quot;est&quot; plots the estimates, but keeps it greyscale with no fading</span></span>
<span id="cb281-3"><a href="SimpleMed.html#cb281-3" tabindex="-1"></a>         <span class="co">#whatLabels = &quot;stand&quot;, #&quot;stand&quot; changes to standardized values</span></span>
<span id="cb281-4"><a href="SimpleMed.html#cb281-4" tabindex="-1"></a>         <span class="at">layout =</span> <span class="st">&#39;tree&#39;</span>, <span class="at">rotation =</span> <span class="dv">2</span>, <span class="co">#together, puts predictors on left, IVs on right </span></span>
<span id="cb281-5"><a href="SimpleMed.html#cb281-5" tabindex="-1"></a>         <span class="at">edge.label.cex =</span> <span class="fl">1.00</span>, <span class="co">#font size of parameter values</span></span>
<span id="cb281-6"><a href="SimpleMed.html#cb281-6" tabindex="-1"></a>         <span class="co">#edge.color = &quot;black&quot;, #overwrites the green/black coloring</span></span>
<span id="cb281-7"><a href="SimpleMed.html#cb281-7" tabindex="-1"></a>         <span class="at">sizeMan=</span><span class="dv">10</span>, <span class="co">#size of squares/observed/&quot;manifest&quot; variables</span></span>
<span id="cb281-8"><a href="SimpleMed.html#cb281-8" tabindex="-1"></a>         <span class="at">fade=</span><span class="cn">FALSE</span>, <span class="co">#if TRUE, there lines are faded such that weaker lines correspond with lower values -- a cool effect, but tough for journals</span></span>
<span id="cb281-9"><a href="SimpleMed.html#cb281-9" tabindex="-1"></a>         <span class="at">esize=</span><span class="dv">2</span>, </span>
<span id="cb281-10"><a href="SimpleMed.html#cb281-10" tabindex="-1"></a>         <span class="at">asize=</span><span class="dv">3</span>,</span>
<span id="cb281-11"><a href="SimpleMed.html#cb281-11" tabindex="-1"></a>         <span class="co">#label.prop = .5,</span></span>
<span id="cb281-12"><a href="SimpleMed.html#cb281-12" tabindex="-1"></a>         <span class="at">label.font =</span> <span class="fl">2.5</span>, <span class="co">#controls size (I think) of font for labels</span></span>
<span id="cb281-13"><a href="SimpleMed.html#cb281-13" tabindex="-1"></a>         <span class="at">label.scale =</span> <span class="cn">TRUE</span>, <span class="co">#if false, the labels will not scale to fit inside the nodes</span></span>
<span id="cb281-14"><a href="SimpleMed.html#cb281-14" tabindex="-1"></a>         <span class="at">nDigits =</span> <span class="dv">3</span>, <span class="co">#decimal places (default is 2)</span></span>
<span id="cb281-15"><a href="SimpleMed.html#cb281-15" tabindex="-1"></a>         <span class="at">residuals =</span> <span class="cn">FALSE</span>,<span class="co">#excludes residuals (and variances) from the path diagram</span></span>
<span id="cb281-16"><a href="SimpleMed.html#cb281-16" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="co">#specifies how many characters to abbreviate variable lables; default is 3.  If 0, uses your entire variable label and adjusts fontsize (which could be a downside)</span></span>
<span id="cb281-17"><a href="SimpleMed.html#cb281-17" tabindex="-1"></a>         <span class="at">intercepts =</span> <span class="cn">FALSE</span>, <span class="co">#gets rid of those annoying triangles (intercepts) in the path diagram)</span></span>
<span id="cb281-18"><a href="SimpleMed.html#cb281-18" tabindex="-1"></a>)</span>
<span id="cb281-19"><a href="SimpleMed.html#cb281-19" tabindex="-1"></a><span class="fu">title</span>(<span class="st">&quot;Entrepreneurial Withdrawal by eDistress via Negative Affect (&amp; some covariates(&quot;</span>)</span></code></pre></div>
<p><img src="05-SimpleMed_files/figure-html/semPLOT%20for%20model%20w%20covs-1.png" width="672" /></p>
<p>The path coefficients appear to be correct, but this is really a statistical map and doesn’t relay the concept of mediation well.</p>
<p>Below is code to create an outfile that could help with creating a table in a word document or spreadsheet. There will be output that is produced with SEM models that won’t be relevant for this project.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="SimpleMed.html#cb282-1" tabindex="-1"></a>KimCOVTab <span class="ot">&lt;-</span> <span class="fu">semTable</span>(Kim_fit_covs, <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">&quot;est&quot;</span>, <span class="st">&quot;se&quot;</span>, <span class="st">&quot;p&quot;</span>, <span class="st">&quot;rsquare&quot;</span>),  <span class="at">columnLabels =</span> <span class="fu">c</span>(<span class="at">eststars =</span> <span class="st">&quot;Estimate&quot;</span>), <span class="at">paramSets =</span> <span class="fu">c</span>(<span class="st">&quot;composites&quot;</span>, <span class="st">&quot;loadings&quot;</span>, <span class="st">&quot;slopes&quot;</span>, <span class="st">&quot;intercepts&quot;</span>, <span class="st">&quot;residualvariances&quot;</span>), <span class="at">file =</span> <span class="st">&quot;ESTRESScov_fitTABLE&quot;</span>, <span class="at">type =</span> <span class="st">&quot;csv&quot;</span>, <span class="at">print.results =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Table 2</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Model Coefficients Assessing Cultural Mistrust as a Mediator Between Racial Microaggressions and Well-Being</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<table>
<colgroup>
<col width="19%" />
<col width="32%" />
<col width="5%" />
<col width="42%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="center">Cultural Mistrust (M)</td>
<td align="center"></td>
<td align="center">Well-Being (Y)</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="13%" />
<col width="5%" />
<col width="11%" />
<col width="13%" />
<col width="13%" />
<col width="5%" />
<col width="10%" />
<col width="13%" />
<col width="12%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left">Antecedent</td>
<td align="center">path</td>
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center"><span class="math inline">\(SE\)</span></td>
<td align="center"><span class="math inline">\(p\)</span></td>
<td align="center">path</td>
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center"><span class="math inline">\(SE\)</span></td>
<td align="center"><span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td align="left">constant</td>
<td align="center"><span class="math inline">\(i_{M}\)</span></td>
<td align="center">2.032</td>
<td align="center">0.185</td>
<td align="center">0.000</td>
<td align="center"><span class="math inline">\(i_{Y}\)</span></td>
<td align="center">5.636</td>
<td align="center">0.277</td>
<td align="center">0.000</td>
</tr>
<tr class="odd">
<td align="left">REMS (X)</td>
<td align="center"><span class="math inline">\(a\)</span></td>
<td align="center">3.109</td>
<td align="center">0.318</td>
<td align="center">0.000</td>
<td align="center"><span class="math inline">\(c&#39;\)</span></td>
<td align="center">0.131</td>
<td align="center">0.479</td>
<td align="center">0.785</td>
</tr>
<tr class="even">
<td align="left">CMI (M)</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(b\)</span></td>
<td align="center">-0.250</td>
<td align="center">0.092</td>
<td align="center">0.007</td>
</tr>
<tr class="odd">
<td align="left">ANX (Cov)</td>
<td align="center"></td>
<td align="center">-0.030</td>
<td align="center">0.058</td>
<td align="center">0.607</td>
<td align="center"></td>
<td align="center">-0.480</td>
<td align="center">0.064</td>
<td align="center">0.000</td>
</tr>
</tbody>
</table>
<table>
<colgroup>
<col width="19%" />
<col width="38%" />
<col width="5%" />
<col width="36%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="center"><span class="math inline">\(R^2\)</span> =</td>
<td align="center"></td>
<td align="center"><span class="math inline">\(R^2\)</span> =</td>
</tr>
</tbody>
</table>
</div>
<div id="apa-style-write-up" class="section level3 hasAnchor" number="5.6.2">
<h3><span class="header-section-number">5.6.2</span> APA Style Write-up<a href="SimpleMed.html#apa-style-write-up" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are varying models for reporting the results of mediation. The Kim et al. <span class="citation">(<a href="#ref-kim_racial_2017">Paul Youngbin Kim et al., 2017</a>)</span> writeup is a great example. Rather than copying it directly, I have modeled my table after the ones in Hayes <span class="citation">(<a href="#ref-hayes_introduction_2018">2018</a>)</span> text. You’ll notice that information in the table and text are minimally overlapping. APA style cautions us against redundancy in text and table.</p>
<p><strong>Results</strong></p>
<p>A simple mediation model examined the degree to which cultural mistrust mediated the effect of racial microaggressions on psychological well-being. Using the <em>lavaan</em> package (v 0.6-7) in R, coefficients for the each path, the indirect effect, and total effects were calculated. The effect of covariate, anxiety, was mapped onto both the mediator and dependent variable. These values are presented in Table 3 and illustrated in Figure 3. Results suggested that of the variance in cultural mistrust and of the variance in well-being were accounted for by the model. Supporting the notion of a mediated model, there was a statistically significant indirect effect (<span class="math inline">\(B\)</span> = -0.776, <span class="math inline">\(p\)</span> = 0.007, CI95 -1.380 to -0.226) in combination with a non-significant direct effect (<span class="math inline">\(B\)</span> = 0.131, <span class="math inline">\(p\)</span> = 0.785, CI95 -0.863 to 1.070). Curiously, though, the total effect (<span class="math inline">\(B\)</span> = -0.646, <span class="math inline">\(p\)</span> = 0.110, CI95 -1.512 to 0.035) was also non-significant.</p>
</div>
</div>
<div id="residual-and-related-questions" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Residual and Related Questions…<a href="SimpleMed.html#residual-and-related-questions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>..that you might have; or at least I had, but if had answered them earlier it would have disrupt the flow.</p>
<ol style="list-style-type: decimal">
<li>Are you sure you can claim a significant indirect effect in the presence of a non-significant total effect? Hayes <span class="citation">(<a href="#ref-hayes_introduction_2018">2018</a>)</span> is.
<ul>
<li>In the section subtitled, “What about Baron &amp; Kenny” (chapter 4), Hayes argues from both logical/philosophical and statistical perspectives that the size of the total effect does not constrain or determine the size of the indirect effect. That is, an indirect effect can be different from zero even when the total effect is not (pp. 117-119).<br />
</li>
</ul></li>
<li>The output we get is different from the output in the journal article being used as the research vignette. Why? And should we worry about it?
<ul>
<li>We are simulating data. This gives us some advantages in that (unless we specify it), we never have missingness and our variables should be normally distributed. Because we are working from means, standard deviations, and correlations, our data will never be the same as the original researcher. That said, we can compare our results to the journal to <em>check out work.</em> In fact, in this very chapter, I got turned around (e.g., first accidentally swapping the mediator and IV; then using the wrong DV) and was able to compare my work against the journal article to correct my errors.</li>
</ul></li>
<li>Some of the statistics you are reporting are different than the ones in Hayes and the ones that use the PROCESS macro (e.g., what happened to the <em>F</em> test)?
<ul>
<li>The default estimator for <em>lavaan</em> is maximum likelihood (ML) and Hayes uses ordinary least squares (OLS). This affects both the values of coefficients, standard errors, AND the type of statistics that are reported.</li>
<li>You can ask for OLS regression by adding the statement “estimator =”GLS”. Even with this option, I have not discovered a way to obtain the <em>F</em> tests for the overall model. Researchers seem to be comfortable with this, even asking for less than we did (e.g., many do not request R square).</li>
<li>Best I can tell, researchers who do want this might use a combination of packages, using GLS estimators in <em>lavaan</em> (this easily gets them the bootstrapped CIs) and the move to a different regression package to get the intercepts and <em>F</em> tests. If I did this I would triple check to make sure that all the output really lined up.</li>
</ul></li>
<li>Why did we ignore the traditional fit statistics associated with structural equation modeling (e.g., CFI, RMSEA).
<ul>
<li>I hesitate to do this with models that do not include latent variables. Therefore, we asked for an “in-between” amount of info that should be sufficient for publication submission (any editor may have their own preferences and ask for more).</li>
</ul></li>
<li>What if I have missing data?
<ul>
<li>When we enter the <em>lavaan</em> world we do get options other than multiple imputation. In today’s example we used the “sem” fitting function. Unless otherwise specified, listwise deletion (deleting the entire case when one of its variables is used to estimate the model) is the default in <em>lavaan</em>. If data are MCAR or MAR, you can add the argument <em>missing = “ml”</em> (or its alias <em>missing = “fiml”</em>). More here <a href="https://users.ugent.be/~yrosseel/lavaan/lavaan2.pdf" class="uri">https://users.ugent.be/~yrosseel/lavaan/lavaan2.pdf</a> on the 1.7/Missing data in lavaan slide.</li>
<li>That said, the type of estimator matters. If you estimate your data with GLS (generalized least squares) or WLS (weighted least squares), you are required to have complete data (however you got it). We used maximum likelihood and, even though we had non-missing data, I used the <em>missing = “fiml”</em> code.</li>
</ul></li>
</ol>
</div>
<div id="practice-problems-4" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Practice Problems<a href="SimpleMed.html#practice-problems-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The three problems described below are designed to grow with the subsequent chapters on complex mediation and conditional process analysis (i.e,. moderated mediation). Therefore, I recommend that you select a dataset that includes at least four variables. If you are new to this topic, you may wish to select variables that are all continuously scaled. The IV and moderator (subsequent chapters) could be categorical (if they are dichotomous, please use 0/1 coding; if they have more than one category it is best if they are ordered). You will likely encounter challenges that were not covered in this chapter. Search for and try out solutions, knowing that there are multiple paths through the analysis.</p>
<p>The suggested practice problem for this chapter is to conduct a simple mediation.</p>
<div id="problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed" class="section level3 hasAnchor" number="5.8.1">
<h3><span class="header-section-number">5.8.1</span> Problem #1: Rework the research vignette as demonstrated, but change the random seed<a href="SimpleMed.html#problem-1-rework-the-research-vignette-as-demonstrated-but-change-the-random-seed" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If this topic feels a bit overwhelming, simply change the random seed in the data simulation, then rework the problem. This should provide minor changes to the data (maybe in the second or third decimal point), but the results will likely be very similar.</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Assign each variable to the X, Y, or M roles (ok but not required to include a cov)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Specify and run the lavaan model</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Use semPlot to create a figure</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Create a table that includes regression output for the M and Y variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Represent your work in an APA-style write-up</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Be able to hand-calculate the indirect, direct, and total effects from the a, b, &amp; c’ paths</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left"><strong>Totals</strong></td>
<td align="center">35</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-2-rework-the-research-vignette-but-swap-one-or-more-variables" class="section level3 hasAnchor" number="5.8.2">
<h3><span class="header-section-number">5.8.2</span> Problem #2: Rework the research vignette, but swap one or more variables<a href="SimpleMed.html#problem-2-rework-the-research-vignette-but-swap-one-or-more-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Use the simulated data, but select one of the other models that was evaluated in the Kim et al. <span class="citation">(<a href="#ref-kim_racial_2017">2017</a>)</span> study. Compare your results to those reported in the mansucript.</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Assign each variable to the X, Y, or M roles (ok but not required to include a cov)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Specify and run the lavaan model</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Use semPlot to create a figure</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Create a table that includes regression output for the M and Y variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Represent your work in an APA-style write-up</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Be able to hand-calculate the indirect, direct, and total effects from the a, b, &amp; c’ paths</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left"><strong>Totals</strong></td>
<td align="center">35</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>
</div>
<div id="problem-3-use-other-data-that-is-available-to-you" class="section level3 hasAnchor" number="5.8.3">
<h3><span class="header-section-number">5.8.3</span> Problem #3: Use other data that is available to you<a href="SimpleMed.html#problem-3-use-other-data-that-is-available-to-you" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using data for which you have permission and access (e.g., IRB approved data you have collected or from your lab; data you simulate from a published article; data from an open science repository; data from other chapters in this OER), complete a simple mediation.</p>
<table>
<colgroup>
<col width="76%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Assignment Component</th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1. Assign each variable to the X, Y, or M roles (ok but not required to include a cov)</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">2. Specify and run the lavaan model</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">3. Use semPlot to create a figure</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">4. Create a table that includes regression output for the M and Y variables</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">5. Represent your work in an APA-style write-up</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left">6. Explanation to grader</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="odd">
<td align="left">7. Be able to hand-calculate the indirect, direct, and total effects from the a, b, &amp; c’ paths</td>
<td align="center">5</td>
<td align="center">_____</td>
</tr>
<tr class="even">
<td align="left"><strong>Totals</strong></td>
<td align="center">35</td>
<td align="center">_____</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-byrne_structural_2016" class="csl-entry">
Byrne, B. M. (2016). <em>Structural <span>Equation</span> <span>Modeling</span> with <span>AMOS</span>: <span>Basic</span> <span>Concepts</span>, <span>Applications</span>, and <span>Programming</span>, <span>Third</span> <span>Edition</span></em>. Taylor &amp; Francis Group. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4556523">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=4556523</a>
</div>
<div id="ref-hayes_introduction_2018" class="csl-entry">
Hayes, A. F. (2018). <em>Introduction to <span>Mediation</span>, <span>Moderation</span>, and <span>Conditional</span> <span>Process</span> <span>Analysis</span>, <span>Second</span> <span>Edition</span>: <span>A</span> <span>Regression</span>-<span>Based</span> <span>Approach</span></em>. Guilford Publications. <a href="http://ebookcentral.proquest.com/lib/spu/detail.action?docID=5109647">http://ebookcentral.proquest.com/lib/spu/detail.action?docID=5109647</a>
</div>
<div id="ref-bollen_testing_1993" class="csl-entry">
Joreskog, K. G. (1993). Testing structural equation models. In K. A. Bollen &amp; J. S. Long (Eds.), <em>Testing <span>Structural</span> <span>Equation</span> <span>Models</span></em>. SAGE.
</div>
<div id="ref-kim_racial_2017" class="csl-entry">
Kim, Paul Youngbin, Kendall, D. L., &amp; Cheon, H.-S. (2017). Racial microaggressions, cultural mistrust, and mental health outcomes among asian american college students. <em>American Journal of Orthopsychiatry</em>, <em>87</em>(6), 663–670. <a href="https://doi.org/10.1037/ort0000203">https://doi.org/10.1037/ort0000203</a>
</div>
<div id="ref-kline_mediation_2015" class="csl-entry">
Kline, R. B. (2015). The mediation myth. <em>Basic and Applied Social Psychology</em>, <em>37</em>(4), 202–213. <a href="https://doi.org/10.1080/01973533.2015.1049349">https://doi.org/10.1080/01973533.2015.1049349</a>
</div>
<div id="ref-rosseel_lavaan_2020" class="csl-entry">
Rosseel, Y. (2020). <em>The lavaan tutorial</em>. <a href="http://lavaan.ugent.be/tutorial/tutorial.pdf">http://lavaan.ugent.be/tutorial/tutorial.pdf</a>
</div>
<div id="ref-stone-romero_research_2010" class="csl-entry">
Stone-Romero, E., &amp; Rosopa, P. (2010). Research design options for testing mediation models and their implications for facets of validity. <em>Journal of Managerial Psychology</em>, <em>25</em>, 697–712. <a href="https://doi.org/10.1108/02683941011075256">https://doi.org/10.1108/02683941011075256</a>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="MED.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="CompMed.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ReC_MultMod.pdf", "ReC_MultMod.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
